packages/synapse-react-client/package.json
- Will bump version in next commit
- Can consider adding tests back
=> Un-bump version and remove test from CI.

packages/synapse-react-client/src/lib/index.ts, packages/synapse-react-client/src/lib/utils/APIConstants.ts, packages/synapse-react-client/src/lib/utils/SynapseClient.ts, packages/synapse-react-client/src/lib/utils/synapseTypes/MembershipInvitation.ts, packages/synapse-react-client/src/lib/utils/synapseTypes/SignedToken/InviteeVerificationSignedToken.ts, packages/synapse-react-client/src/lib/utils/synapseTypes/SignedToken/JoinTeamSignedToken.ts, packages/synapse-react-client/src/lib/utils/synapseTypes/SignedToken/MembershipInvtnSignedToken.ts, packages/synapse-react-client/src/lib/utils/synapseTypes/SignedToken/SignedTokenInterface.ts
Prep the necessary service calls to support a user who does not have a Synapse account but was invited to a Synapse team (via email)
=> PORTALS-2443: export hex2ascii, add additional synapse types, and service calls

packages/synapse-react-client/src/lib/containers/auth/LoginFlowBackButton.tsx, packages/synapse-react-client/src/lib/containers/auth/LoginForm.tsx, packages/synapse-react-client/src/lib/containers/auth/LoginPage.tsx, packages/synapse-react-client/src/lib/containers/auth/RecoveryCodeForm.tsx, packages/synapse-react-client/src/lib/containers/auth/StandaloneLoginForm.tsx, packages/synapse-react-client/src/lib/containers/auth/TOTPForm.tsx, packages/synapse-react-client/src/lib/containers/auth/UsernamePasswordForm.tsx, packages/synapse-react-client/src/lib/utils/hooks/useLogin.ts, packages/synapse-react-client/test/lib/containers/Login.test.tsx, packages/synapse-react-client/test/lib/utils/hooks/useLogin.test.tsx
- Add and integrate RecoveryCodeForm.tsx
- Return isLoading state from useLogin, determined now by using `useMutation`
- Update UsernamePasswordForm to use HTML5 validation (required text fields)
https://user-images.githubusercontent.com/17580037/221054048-1b4da6cc-1cc7-4140-a3f2-bc1625dfacd6.mov
=> SWC-6391 - Add recovery code login

packages/synapse-react-client/src/lib/utils/hooks/useLogin.ts
=> SWC-6402 - clear the error message when we switch steps

packages/synapse-react-client/src/lib/containers/IconSvg.tsx, packages/synapse-react-client/src/lib/containers/auth/TwoFactorAuthSettingsPanel.tsx, packages/synapse-react-client/src/lib/containers/auth/TwoFactorEnrollmentForm.tsx, packages/synapse-react-client/src/lib/utils/SynapseClient.ts, packages/synapse-react-client/src/lib/utils/hooks/SynapseAPI/KeyFactory.ts, packages/synapse-react-client/src/lib/utils/hooks/SynapseAPI/auth/useTwoFactorEnrollment.ts, packages/synapse-react-client/stories/TwoFactorAuthSettingsPanel.stories.tsx, packages/synapse-react-client/test/lib/containers/auth/TwoFactorAuthSettingsPanel.test.tsx
=> SWC-6393 - Add 2FA panel for settings page

packages/synapse-react-client/esbuild.config.mjs, packages/synapse-react-client/package.json, packages/synapse-react-client/src/lib/containers/StorybookComponentWrapper.tsx, packages/synapse-react-client/src/lib/containers/auth/TwoFactorAuthSettingsPanel.tsx, packages/synapse-react-client/src/lib/containers/auth/TwoFactorBackupCodes.tsx, packages/synapse-react-client/src/lib/containers/auth/TwoFactorSecretDialog.tsx, packages/synapse-react-client/src/lib/style/components/_synapse-nav-drawer.scss, packages/synapse-react-client/src/lib/umd.index.ts, packages/synapse-react-client/src/lib/utils/hooks/useMediaPrintOnly.ts, pnpm-lock.yaml
- Export components in UMD build
- Change `@media print` strategy and add custom hook
- Update copy
- Upgrade esbuild
- Fix small padding annoyance in NavDrawer
=> SWC-6393 - Tweaks + fixes discovered while porting 2FA to SWC

apps/portals/src/index.tsx
=> Remove comma adding undesirable space after footer

.github/workflows/build-test.yml, README.md, apps/SageAccountWeb/craco.config.js, apps/SageAccountWeb/package.json, apps/portals/craco.config.js, apps/portals/package.json, apps/synapse-oauth-signin/craco.config.js, apps/synapse-oauth-signin/package.json, package.json, packages/synapse-react-client/test/lib/containers/dataaccess/AccessSubmissionDashboard.test.tsx, pnpm-lock.yaml
- Attempt to silence tests run by Nx (though it seems like the config isn't working for all projects)
- Emit HTML reports for each project
=> Improve CI developer experience

apps/SageAccountWeb/src/components/RegisterAccount2.tsx, apps/SageAccountWeb/src/style/_Register.scss
=> PORTALS-2562: polish items on email address verified page

apps/SageAccountWeb/src/components/StyledComponents.ts, packages/synapse-react-client/src/lib/containers/auth/AuthenticationMethodSelection.tsx, packages/synapse-react-client/src/lib/containers/auth/LoginForm.tsx
=> PORTALS-2559: polish items for sign in page

packages/synapse-react-client/package.json
* NFINT-836: add institution to tools card by @jay-hodgson in https://github.com/Sage-Bionetworks/synapse-web-monorepo/pull/69
* PORTALS-2580 - refactor for synapse-oauth-signin + misc fixes by @nickgros in https://github.com/Sage-Bionetworks/synapse-web-monorepo/pull/70
* SWC-6386 - migrate synapse-oauth-signin to monorepo by @nickgros in https://github.com/Sage-Bionetworks/synapse-web-monorepo/pull/71
* PORTALS-2592 by @jay-hodgson in https://github.com/Sage-Bionetworks/synapse-web-monorepo/pull/73
* Remove comma adding undesirable space after footer by @nickgros in https://github.com/Sage-Bionetworks/synapse-web-monorepo/pull/76
* SWC-6387 - Add SageAccountWeb to monorepo by @nickgros in https://github.com/Sage-Bionetworks/synapse-web-monorepo/pull/75
* PORTALS-2580 - Support Google …
=> Bump synapse-react-client to 3.1.29

apps/portals/src/configurations/adknowledgeportal/resources.ts
Increment the AD Portal file view version for data release 20.2
=> increment AD file view version

apps/SageAccountWeb/src/components/TermsOfUsePage.tsx
=> PORTALS-2563: polish T&C page

apps/portals/src/configurations/adknowledgeportal/scripts/exportS3ProductionBucketName.sh
This PR updates the destination bucket for prod.adknowledgeportal.synapse.org.
=> IT-2094: Deploy to new bucket

apps/SageAccountWeb/src/style/_core.scss
=> PORTALS-2565: polish items for certification quiz page

.github/workflows/deploy-sage-account-web.yml
- May need to update the workflow to deploy to staging on main, and update the role to allow deployments on other branches.
=> IT-2744 - Update SageAccountWeb deploy script to use OIDC integration

apps/SageAccountWeb/src/components/AccountSettings.tsx, apps/SageAccountWeb/src/components/SageResourcesPage.tsx, apps/SageAccountWeb/src/components/StyledComponents.ts, apps/SageAccountWeb/src/style/_AccountSetting.scss, apps/SageAccountWeb/src/style/_Register.scss, apps/SageAccountWeb/src/style/theme.ts
=> PORTALS-2616: border radius on account settings table of contents

apps/portals/src/configurations/adknowledgeportal/resources.ts
This is for a patch data release for the AD portal.
=> increment AD file view

apps/synapse-oauth-signin/src/App.tsx
The theme was missing, so many components were unstyled.
=> Add missing ThemeProvider to synapse-oauth-signin

packages/synapse-react-client/demo/containers/playground/ToastDemo.tsx
=> PORTALS-2475: fix Storybook demo of toast without button or link text

packages/synapse-react-client/src/lib/containers/access_requirements/HasAccessV2.tsx, packages/synapse-react-client/src/lib/containers/table/ExpandableTableDataCell.tsx, packages/synapse-react-client/src/lib/style/base/_core.scss, packages/synapse-react-client/src/lib/style/components/_access-requirement-list.scss, packages/synapse-react-client/src/lib/style/components/_expandable_table_data.scss
Before: 
https://user-images.githubusercontent.com/26949006/232628884-f786ad22-98c8-4aee-9d89-1c511255015b.mov
After: 
https://user-images.githubusercontent.com/26949006/232628842-57df8f4f-de76-4656-ba0a-ecb984375ef7.mov
=> PORTALS-2499, PORTALS-2502, PORTALS-2503

packages/synapse-react-client/package.json
* SWC-6420: update rss-parser (and update plotly in a failed attempt to… by @jay-hodgson in https://github.com/Sage-Bionetworks/synapse-web-monorepo/pull/132
* PORTALS-2597: buttons radius and text need to be consistent by @hallieswan in https://github.com/Sage-Bionetworks/synapse-web-monorepo/pull/126
* update elportal logo by @jay-hodgson in https://github.com/Sage-Bionetworks/synapse-web-monorepo/pull/134
* PORTALS-2621 - Fix NF stale data issue by resetting table query on prop change by @nickgros in https://github.com/Sage-Bionetworks/synapse-web-monorepo/pull/133
* PORTALS-2475: fix Storybook demo of toast without button or link text by @hallieswan in https://github.com/Sage-Bionetworks/synapse-web-monorepo/pull/129
* PORTALS-2478, PORTALS-2481, PORTALS-2482, PORTALS-2490, …
=> SRC 3.1.31

apps/SageAccountWeb/src/App.tsx, apps/SageAccountWeb/src/components/AccountSettings.tsx, apps/SageAccountWeb/src/components/OAuthClientManagementPage.tsx, apps/SageAccountWeb/src/components/PersonalAccessTokensPage.tsx, packages/synapse-react-client/src/lib/index.ts
=> PORTALS-2649

packages/synapse-react-client/package.json, packages/synapse-react-client/src/lib/containers/UserOrTeamBadge.tsx, packages/synapse-react-client/src/lib/containers/UserSearchBoxV2.tsx, packages/synapse-react-client/src/lib/utils/hooks/SynapseAPI/file/useFiles.ts, packages/synapse-react-client/src/lib/utils/hooks/useOverlay.tsx, pnpm-lock.yaml
- Fix bug in UserSearchBoxV2 where the popover would close the search results menu
- Fix bug where the Popover transition could result in a thrown error if the Popover was shown within a Dialog
- Add thrown error from code review
=> SWC-6412 - non-feature related bugfixes

packages/synapse-react-client/src/lib/containers/DialogBase.tsx, packages/synapse-react-client/src/lib/containers/markdown/MarkdownEditor.tsx, packages/synapse-react-client/src/lib/containers/markdown/UserMentionModal.tsx
Before: 
https://user-images.githubusercontent.com/26949006/236078939-c8c15577-605e-45a9-b13e-401f31229af4.mov
After: 
https://user-images.githubusercontent.com/26949006/236078932-5b7c928c-7cec-421b-bbcf-363db73f4819.mov
=> PORTALS-2624: refactor UserMentionModal to use MUI components

apps/SageAccountWeb/src/LoginPage.tsx, apps/portals/src/Navbar.tsx, apps/synapse-oauth-signin/src/OAuth2Form.tsx, packages/synapse-react-client/src/lib/components/styled/LeftRightPanel.tsx, packages/synapse-react-client/src/lib/containers/SystemUseNotification.tsx, packages/synapse-react-client/src/lib/containers/auth/LoginPage.tsx
OAuth sign in:
Portals:
One Sage:
Synapse.org (storybook):
=> SWC-6430: add system use notification and integrate into apps

apps/portals/run.sh, apps/portals/sitemap/generate-sitemap.cjs
- Missed when refactoring file name change
=> PORTALS-2628

apps/portals/src/portal-components/nf/BrowseToolsPage.tsx
=> PORTALS-2600: rebranding as NF Research Tools Central

packages/synapse-react-client/test/lib/containers/markdown/__snapshots__/MarkdownSynapse.integration.test.tsx.snap
=> PORTALS-2654

.github/workflows/deploy-sage-account-web.yml
The CI role names to assume will change due to PR
Sage-Bionetworks-IT/organizations-infra#859. update to the new role names
depends on Sage-Bionetworks-IT/organizations-infra#859
=> [IT-2768] Update role name for CI

packages/synapse-react-client/src/lib/containers/download_list_v2/DownloadCartPage.tsx, packages/synapse-react-client/src/lib/containers/download_list_v2/DownloadListActionsRequired.tsx, packages/synapse-react-client/src/lib/style/components/_download-cart-page.scss, packages/synapse-react-client/src/lib/utils/theme/palette/Palettes.ts, packages/synapse-react-client/test/lib/containers/markdown/__snapshots__/MarkdownSynapse.integration.test.tsx.snap
- Fix styling within download cart by dropping some bootstrap
- Always use white for contrast text
=> SWC-6410 - fix styling issues

apps/portals/src/configurations/challengeportal/synapseConfigs/challenges.ts, apps/portals/src/portal-components/ProjectDiscussionForum.tsx, apps/portals/src/portal-components/index.ts, apps/portals/src/types/portal-config.ts, apps/portals/src/types/portal-util-types.ts, packages/synapse-react-client/src/lib/containers/discussion_forum/ForumPage.tsx, packages/synapse-react-client/src/lib/containers/discussion_forum/ForumTable.tsx, packages/synapse-react-client/src/lib/utils/SynapseClient.ts, packages/synapse-react-client/src/lib/utils/functions/sqlFunctions.ts, packages/synapse-react-client/src/lib/utils/hooks/SynapseAPI/KeyFactory.ts, packages/synapse-react-client/src/lib/utils/hooks/SynapseAPI/entity/useExportToCavatica.ts, packages/synapse-react-client/src/lib/utils/hooks/SynapseAPI/entity/useGetEntityForum.ts, packages/synapse-react-client/src/lib/utils/synapseTypes/DiscussionBundle.ts, packages/synapse-react-client/test/lib/utils/hooks/SynapseAPI/useExportToCavatica.test.tsx
https://github.com/Sage-Bionetworks/synapse-web-monorepo/assets/1864447/a98d3572-5364-46b8-a7eb-a921c9a6c123
=> add Forum object, and a Community tab to the Challenge Details Page

packages/synapse-react-client/src/components/SynapseTable/TopLevelControls.tsx
=> PORTALS-2671: Add Send To Cavatica confirmation dialog

apps/portals/src/configurations/nf/synapseConfigs/tools.ts, packages/synapse-react-client/.storybook/preview.jsx, packages/synapse-react-client/src/components/StorybookComponentWrapper.tsx, packages/synapse-react-client/src/theme/DefaultTheme.tsx, packages/synapse-react-client/src/theme/typography/Link.ts, packages/synapse-react-client/test/containers/markdown/__snapshots__/MarkdownSynapse.integration.test.tsx.snap
- hard-code hover style for MUI buttons and links to override bs3 styling
- Add elportal to Storybook palettes
=> PORTALS-2665 - theme changes

packages/synapse-react-client/src/style/abstracts/_variables.scss
https://www.figma.com/file/0oPm5lLSUva8kyfVNMS6FA?node-id=213:7173#466693261
=> PORTALS-2688: small tweak from design around light grey color

packages/synapse-react-client/src/components/ChallengeDetailPage/ChallengeDetailPage.tsx, packages/synapse-react-client/src/components/ChallengeTeamWizard/ChallengeTeamWizard.tsx, packages/synapse-react-client/src/synapse-queries/team/useTeamMembers.ts
this causes the registration button to properly update state
=> PORTALS-2447: and invalidate on membership changes

packages/synapse-react-client/src/components/GenericCard/GenericCard.tsx, packages/synapse-react-client/src/components/QueryVisualizationWrapper.tsx, packages/synapse-react-client/src/components/widgets/facet-nav/SelectionCriteriaPills.tsx
- Group SelectionCriteriaPills when 5+ value filters are applied to one column
https://github.com/Sage-Bionetworks/synapse-web-monorepo/assets/17580037/b4ee1f69-5cff-44e0-8a35-57276561a2d9
https://github.com/Sage-Bionetworks/synapse-web-monorepo/assets/17580037/18a6806e-53e8-4c3f-80f3-662a57ab22f7
=> PORTALS-2691: Group SelectionCriteriaPills when 5+ apply to a single column

apps/SageAccountWeb/src/components/ProfileValidation/Attestation.tsx, packages/synapse-react-client/src/components/AccessRequirementList/ManagedACTAccessRequirementRequestFlow/DataAccessRequestAccessorsEditor.tsx, packages/synapse-react-client/src/components/AccessRequirementList/ManagedACTAccessRequirementRequestFlow/DataAccessRequestAccessorsFilesForm.tsx, packages/synapse-react-client/src/components/AccessRequirementList/ManagedACTAccessRequirementRequestFlow/UploadDocumentField.tsx, packages/synapse-react-client/src/components/DirectDownloadButton.tsx, packages/synapse-react-client/src/components/FileUpload/FileUpload.tsx, packages/synapse-react-client/src/synapse-client/SynapseClient.ts, packages/synapse-react-client/stories/FileUpload.stories.tsx, packages/synapse-react-client/stories/data-access-request/RequestDataAccessStep2.stories.tsx, packages/synapse-react-client/test/containers/AccessRequirementList/DataAccessRequestAccessorsFilesForm.test.tsx
- Sync dataAccessRequest updates with the server so file upload/download works
- Fix fileHandleAssociation errors
This branch will be merged into main, but is based off of the v3.1.36 commit. Once approved, I will locally publish a `v3.1.36-SWC-6467` release to merge into SWC production.
=> SWC-6467 - fix file upload/download on data access requests

packages/synapse-react-client/src/components/ChallengeSubmission/ChallengeSubmission.tsx
onSettled is deprecated and will be removed in the next major version of react query
=> move away from onSettled fixes lifecycle issue

.github/workflows/npmpublish.yml, packages/markdown-it-synapse/package.json, packages/synapse-react-client/package.json
- Run dry-run versions of steps on PR
- Remove unnecessary scripts from markdown-it-synapse
=> fix publish step

packages/synapse-react-client/src/synapse-queries/entity/useActionsRequiredForTableQuery.ts
- Fix issue where `selectFileColumn` would never be undefined, even if it should
=> PORTALS-2714

packages/synapse-react-client/src/components/QueryVisualizationWrapper.tsx, packages/synapse-react-client/src/components/SynapseTable/RowSelection/RowSelectionControls.tsx, packages/synapse-react-client/src/components/SynapseTable/SendToCavaticaConfirmationDialog.tsx, packages/synapse-react-client/src/components/SynapseTable/TopLevelControls/TopLevelControls.tsx, packages/synapse-react-client/src/components/SynapseTable/TopLevelControls/TopLevelControlsUtils.ts, packages/synapse-react-client/src/components/SynapseTable/table-top/DownloadOptions.tsx, packages/synapse-react-client/src/components/download_list/DownloadConfirmationUI.tsx, packages/synapse-react-client/src/components/download_list/TableQueryDownloadConfirmation.tsx, packages/synapse-react-client/src/components/widgets/facet-nav/SelectionCriteriaPills.tsx, packages/synapse-react-client/src/utils/functions/QueryFilterUtils.ts, packages/synapse-react-client/src/utils/functions/queryUtils.ts, packages/synapse-react-client/test/components/download_list/DownloadConfirmationUI.test.tsx, packages/synapse-react-client/test/containers/queryUtils.test.ts, packages/synapse-react-client/test/containers/table/SendToCavaticaConfirmationDialog.test.tsx, packages/synapse-react-client/test/containers/table/TopLevelControls/TopLevelControlsUtils.test.ts, packages/synapse-react-client/test/containers/table/table-top/DownloadOptions.test.tsx, packages/synapse-types/src/Table/QueryFilter.ts
=> PORTALS-2701: Ability to select files to add to Download List

.github/workflows/deploy-sage-account-web-staging.yml
Thought I had fixed that already...
=> PORTALS-2622: Fix app name

apps/portals/src/configurations/elportal/synapseConfigs/studies.ts
Change ELITE portal config (study details page)
=> PORTALS-2723

packages/synapse-react-client/src/components/DownloadCart/DownloadListTable.tsx
Related to: https://sagebionetworks.jira.com/browse/SWC-6332
Set conditional statement so that version number only gets shown in download cart when it is available
=> [bug fix] Showed version number when it is available

packages/synapse-react-client/package.json, packages/synapse-react-client/src/components/SynapseTable/ExpandCollapseButton.tsx, packages/synapse-react-client/src/components/SynapseTable/ExpandableTableDataCell.tsx, packages/synapse-react-client/src/components/SynapseTable/SynapseTable.tsx, packages/synapse-react-client/src/components/SynapseTable/SynapseTableCell/EntityIdList.tsx, packages/synapse-react-client/src/components/SynapseTable/SynapseTableCell/EvaluationIdRenderer.tsx, packages/synapse-react-client/src/components/SynapseTable/SynapseTableCell/JSON/ComplexJSONRenderer.tsx, packages/synapse-react-client/src/components/SynapseTable/SynapseTableCell/JSON/JSONArrayRenderer.tsx, packages/synapse-react-client/src/components/SynapseTable/SynapseTableCell/JSON/JSONObjectRenderer.tsx, packages/synapse-react-client/src/components/SynapseTable/SynapseTableCell/JSON/JSONPrimitiveRenderer.tsx, packages/synapse-react-client/src/components/SynapseTable/SynapseTableCell/JSON/JSONRendererUtils.ts, packages/synapse-react-client/src/components/SynapseTable/SynapseTableCell/JSON/JSONTableCellRenderer.tsx, packages/synapse-react-client/src/components/SynapseTable/SynapseTableCell/JSON/index.ts, packages/synapse-react-client/src/components/SynapseTable/SynapseTableCell/SynapseTableCell.tsx, packages/synapse-react-client/src/components/SynapseTable/SynapseTableCell/UserIdList.tsx, packages/synapse-react-client/src/components/SynapseTable/SynapseTableCell/index.ts, packages/synapse-react-client/src/components/SynapseTable/SynapseTableUtils.ts, packages/synapse-react-client/stories/QueryWrapperPlotNav.stories.tsx, packages/synapse-react-client/stories/SynapseTableCell.stories.tsx, packages/synapse-react-client/test/components/SynapseTable/SynapseTable.integration.test.tsx, packages/synapse-react-client/test/components/SynapseTable/SynapseTableCell/JSON/JSONRendererUtils.test.ts, packages/synapse-react-client/test/components/SynapseTable/SynapseTableCell/JSON/JSONTableCellRenderer.test.tsx, packages/synapse-react-client/test/components/SynapseTable/SynapseTableCell/JSON/__snapshots__/JSONTableCellRenderer.test.tsx.snap, packages/synapse-react-client/test/components/SynapseTable/SynapseTableUtils.test.ts, packages/synapse-react-client/test/containers/EntityIdList.test.tsx, packages/synapse-react-client/test/containers/EvaluationIdRenderer.test.tsx, packages/synapse-react-client/test/containers/UserIdList.test.tsx, packages/synapse-types/src/Table/ColumnType.ts, pnpm-lock.yaml
Basic JSON column support to match EL Portal/Cohort Builder designs and gracefully handle generic JSON usage in Synapse.org
https://github.com/Sage-Bionetworks/synapse-web-monorepo/assets/17580037/074a14fd-1237-4f22-92b8-347ba8250a09
=> SWC-6492 - Custom JSON table cell rendering

packages/synapse-react-client/src/components/SynapseNavDrawer.tsx
before: 
https://github.com/Sage-Bionetworks/synapse-web-monorepo/assets/26949006/1055b76a-8c4c-43dc-b1d4-5b077b958a5d
after: 
https://github.com/Sage-Bionetworks/synapse-web-monorepo/assets/26949006/a3352188-a012-418f-bffe-7c00e2c527e6
=> SWC-6495: fix unreadable success notification when creating a project

apps/portals/src/configurations/nf/resources.ts, apps/portals/src/configurations/nf/routesConfig.ts, apps/portals/src/configurations/nf/synapseConfigs/datasets.ts, packages/synapse-react-client/src/components/GenericCard/GenericCard.tsx, packages/synapse-react-client/src/components/widgets/facet-nav/FacetNav.tsx, packages/synapse-react-client/src/components/widgets/facet-nav/FacetPlotLegendList.tsx
And truncate in the facet chart legend via css rather than truncating the value
=> PORTALS-2750, PORTALS-2742: In NF, use Dataset Collection

packages/synapse-react-client/src/components/widgets/facet-nav/FacetNavPanel.tsx, packages/synapse-react-client/src/style/components/facet_nav/_facet-nav-panel.scss, packages/synapse-react-client/test/containers/widgets/facet-nav/FacetNavPanel.test.tsx
=> PORTALS-2742: another try

apps/portals/src/configurations/nf/resources.ts
Small follow-up update to PORTALS-2750 -- sorry, we found more datasets that needed to be added last-minute!
=> Bump NF dataset collection version

packages/synapse-react-client/src/components/widgets/facet-nav/FacetNav.tsx, packages/synapse-react-client/src/style/components/facet_nav/_facet-nav.scss
=> PORTALS-2638 - FacetNav visual updates

packages/synapse-react-client/src/components/SynapseTable/SynapseTable.tsx
=> PORTALS-2760 - deselect uses deep equality

apps/portals/src/_Core.scss, apps/portals/src/portal-components/csbc-home-page/Ecosystem.tsx, apps/portals/src/portal-components/csbc-home-page/style/_ecosystem.scss
=> PORTALS-2669 - Ecosystem component updates

apps/portals/src/configurations/elportal/routesConfig.tsx
=> PORTALS-2774 - Reorder routes so OrientationBanner appears in the correct location

packages/synapse-react-client/src/components/row_renderers/utils/CardFooter.tsx, packages/synapse-react-client/src/style/base/_core.scss, packages/synapse-react-client/src/style/components/_cards.scss
Also drop unnecessary `SRC-card-footer-header` style.
=> PORTALS-2743 - Fix link styling in header cards

packages/synapse-react-client/src/style/components/_cards.scss
=> PORTALS-2734

apps/portals/src/configurations/digitalhealth/resources.ts
=> Update resources.ts for data release

apps/portals/src/configurations/nf/resources.ts, packages/synapse-react-client/src/components/TimelinePlot/TimelinePlot.tsx, packages/synapse-react-client/src/components/row_renderers/ObservationCard.tsx, packages/synapse-react-client/src/style/components/row_renderers/_observation-card.scss
=> PORTALS-2806, add a DOI link if available

apps/portals/src/configurations/elportal/resources.ts
=> PLFM-8059: remove Diagnosis column

packages/synapse-react-client/src/components/TableColumnSchemaEditor/ImportTableColumnsButton.test.tsx, packages/synapse-react-client/src/components/TableColumnSchemaEditor/ImportTableColumnsButton.tsx, packages/synapse-react-client/src/components/TableColumnSchemaEditor/TableColumnSchemaEditor.integration.test.tsx, packages/synapse-react-client/src/components/TableColumnSchemaEditor/TableColumnSchemaEditor.stories.ts, packages/synapse-react-client/src/components/TableColumnSchemaEditor/TableColumnSchemaEditorUtils.ts, packages/synapse-react-client/src/components/TableColumnSchemaEditor/TableColumnSchemaForm.tsx, packages/synapse-react-client/src/utils/functions/EntityTypeUtils.ts
SWC-6548
https://github.com/Sage-Bionetworks/synapse-web-monorepo/assets/17580037/15cb2266-ac32-41a4-a25d-17adbcd87cf5
=> SWC-6548 - Add ability to import table columns

.github/actions/pnpm-setup-action/action.yml, .gitignore
The default path changed in Nx 17
=> Update gitignore and GitHub Action to reference new Nx cache path

apps/portals/src/configurations/elportal/synapseConfigs/studies.ts, packages/synapse-react-client/src/components/QueryWrapper/QueryWrapper.tsx, packages/synapse-react-client/src/components/QueryWrapper/TableRowSelectionState.ts, packages/synapse-react-client/src/components/QueryWrapperPlotNav/QueryWrapperPlotNav.tsx, packages/synapse-react-client/src/components/SynapseTable/RowSelection/RowSelectionUI.tsx, packages/synapse-react-client/src/style/components/_query-wrapper-plot-nav.scss
Based on Adam's css solution: https://www.loom.com/share/2cea4429e8b14335b9cea02846f0ac60
With additional changes to parameterize (Explore page vs Detail page that has multiple tables that allow selection)
=> PORTALS-2744

packages/synapse-react-client/src/components/SynapseHomepage/SynapseHomepage.tsx, packages/synapse-react-client/src/style/components/_synapse-homepage.scss, packages/synapse-react-client/src/theme/ThemeTypes.d.ts, packages/synapse-react-client/src/theme/palette/Palettes.ts
device | location | before | after 
:---:|:---:|:---:|:---:
desktop | top | <img width="1253" alt="top_fullSize_before" src="https://github.com/Sage-Bionetworks/synapse-web-monorepo/assets/26949006/8db8e9f9-c6e7-44a2-b220-fa994a3ba543"> | <img width="1257" alt="top_fullSize_after" src="https://github.com/Sage-Bionetworks/synapse-web-monorepo/assets/26949006/ace9065d-226d-4673-a803-7792e36c2300">
desktop | bottom | <img width="1251" alt="bottom_fullSize_before" src="https://github.com/Sage-Bionetworks/synapse-web-monorepo/assets/26949006/47a89a2a-226e-492d-a016-228747aceea2"> | <img width="1254" alt="bottom_fullSize_after" src="https://github.com/Sage-Bionetworks/synapse-web-monorepo/assets/26949006/253da359-e804-40f4-8fbc-5b68592e77c8">
mobile | top | <img width="444" …
=> SWC-6607: fix synapse homepage visual issues

apps/portals/src/configurations/nf/resources.ts
Fix mutations sql (current one points to a table that does not exist), and bump to latest portal fileview snapshot (113).
=> Fix mutations, update files vsn

apps/portals/src/configurations/adknowledgeportal/synapseConfigs/data.ts
Reverts Sage-Bionetworks/synapse-web-monorepo#602
=> Revert "PORTALS-2874: temporarily hide the Send to CAVATICA functionality for a data releas…"

packages/synapse-react-client/package.json, packages/synapse-react-client/src/components/DateTimePicker/DateTimePicker.tsx, packages/synapse-react-client/src/components/TableColumnSchemaEditor/TableColumnSchemaEditorUtils.ts, packages/synapse-react-client/src/components/TableColumnSchemaEditor/Validators/BooleanSchema.test.ts, packages/synapse-react-client/src/components/TableColumnSchemaEditor/Validators/BooleanSchema.ts, packages/synapse-react-client/src/components/TableColumnSchemaEditor/Validators/ColumnModelValidator.test.ts, packages/synapse-react-client/src/components/TableColumnSchemaEditor/Validators/ColumnModelValidator.ts, packages/synapse-react-client/src/components/TableColumnSchemaEditor/Validators/DatetimeSchema.ts, packages/synapse-react-client/src/components/TableColumnSchemaEditor/Validators/DefaultValueValidator.test.ts, packages/synapse-react-client/src/components/TableColumnSchemaEditor/Validators/DefaultValueValidator.ts, packages/synapse-react-client/src/components/TableColumnSchemaEditor/Validators/DoubleSchema.test.ts, packages/synapse-react-client/src/components/TableColumnSchemaEditor/Validators/DoubleSchema.ts, packages/synapse-react-client/src/components/TableColumnSchemaEditor/Validators/EntityIdSchema.test.ts, packages/synapse-react-client/src/components/TableColumnSchemaEditor/Validators/EntityIdSchema.ts, packages/synapse-react-client/src/components/TableColumnSchemaEditor/Validators/EnumValuesValidator.test.ts, packages/synapse-react-client/src/components/TableColumnSchemaEditor/Validators/EnumValuesValidator.ts, packages/synapse-react-client/src/components/TableColumnSchemaEditor/Validators/IntegerSchema.ts, packages/synapse-react-client/src/components/TableColumnSchemaEditor/Validators/OptionalStringSchema.ts, packages/synapse-react-client/src/components/TableColumnSchemaEditor/Validators/getZodSchemaForColumnType.ts, pnpm-lock.yaml
- Add validation functions for Table Column Schema editor
- Simplify DateTimePicker
=> SWC-6612: Add validation functions for Table Column Schema Editor

packages/synapse-react-client/src/components/TableColumnSchemaEditor/TableColumnSchemaEditor.integration.test.tsx, packages/synapse-react-client/src/components/TableColumnSchemaEditor/TableColumnSchemaEditorUtils.ts, packages/synapse-react-client/src/components/TableColumnSchemaEditor/Validators/ColumnModelValidator.ts
=> SWC-6622 - Handle case where restricted values for INTEGER columns could not be edited

packages/synapse-react-client/src/components/SynapseTable/SendToCavaticaConfirmationDialog.tsx
=> PORTALS-2868 - Update disclaimer copy

apps/portals/src/configurations/nf/resources.ts
We added some new datasets so incrementing to new snapshot. Cross-ref: [PORTALS-2886](https://sagebionetworks.jira.com/browse/PORTALS-2886)
[PORTALS-2886]: https://sagebionetworks.jira.com/browse/PORTALS-2886?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> Update config version for datasets

packages/synapse-react-client/src/components/SubmissionViewScopeEditor/SubmissionViewScopeEditor.stories.tsx, packages/synapse-react-client/src/components/SubmissionViewScopeEditor/SubmissionViewScopeEditor.test.tsx, packages/synapse-react-client/src/components/SubmissionViewScopeEditor/SubmissionViewScopeEditor.tsx, packages/synapse-react-client/src/synapse-queries/KeyFactory.ts, packages/synapse-react-client/src/synapse-queries/evaluation/useEvaluation.ts
https://github.com/Sage-Bionetworks/synapse-web-monorepo/assets/17580037/3522f494-8357-4a37-a1cf-1a3d609db4f5
=> SWC-6627 - Add SubmissionViewScopeEditor

packages/synapse-react-client/src/components/CreateTableViewWizard/CreateTableViewWizard.integration.test.tsx, packages/synapse-react-client/src/components/CreateTableViewWizard/CreateTableViewWizard.stories.tsx, packages/synapse-react-client/src/components/CreateTableViewWizard/CreateTableViewWizard.tsx, packages/synapse-react-client/src/components/CreateTableViewWizard/CreateTableViewWizardUtils.test.ts, packages/synapse-react-client/src/components/CreateTableViewWizard/CreateTableViewWizardUtils.ts, packages/synapse-react-client/src/components/CreateTableViewWizard/README.md, packages/synapse-react-client/src/components/CreateTableViewWizard/TableNameForm.tsx, packages/synapse-react-client/src/components/SqlDefinedTableEditor/SqlDefinedTableEditor.tsx, packages/synapse-react-client/src/components/TableColumnSchemaEditor/TableColumnSchemaEditor.integration.test.tsx, packages/synapse-react-client/src/components/TableColumnSchemaEditor/TableColumnSchemaEditor.stories.ts, packages/synapse-react-client/src/components/TableColumnSchemaEditor/TableColumnSchemaEditorTestUtils.ts, packages/synapse-react-client/src/components/TableColumnSchemaEditor/TableColumnSchemaForm.tsx, packages/synapse-react-client/src/mocks/entity/mockEvaluationQueue.ts, packages/synapse-react-client/src/mocks/entity/mockProject.ts, packages/synapse-react-client/src/mocks/mockAnnotationColumns.ts, packages/synapse-react-client/src/mocks/msw/handlers.ts, packages/synapse-react-client/src/mocks/msw/handlers/entityHandlers.ts, packages/synapse-react-client/src/mocks/msw/handlers/evaluationHandlers.ts, packages/synapse-react-client/src/mocks/msw/handlers/tableQueryHandlers.ts, packages/synapse-react-client/src/synapse-queries/entity/useEntity.ts, packages/synapse-react-client/src/synapse-queries/table/useColumnModel.ts, packages/synapse-react-client/src/umd.index.ts
Remaining feature work on the new CreateTableViewWizard
[View in Storybook](https://6464de5f2e01a2af614b79c7-axhnkhzweh.chromatic.com/?path=/story/synapse-create-table-wizard--demo)
=> SWC-6627 - Add CreateTableViewWizard

packages/synapse-react-client/src/components/OAuthClientManagement/CreateOAuthClient.integration.test.tsx, packages/synapse-react-client/src/components/OAuthClientManagement/CreateOAuthClient.tsx
https://github.com/Sage-Bionetworks/synapse-web-monorepo/assets/26949006/ce954a21-c3e9-4b99-a447-a49478e3fc5a
=> SWC-6434: add userinfo format choice to OAuth client editor

packages/synapse-react-client/src/components/QueryWrapperPlotNav/QueryWrapperSynapsePlot.tsx
https://github.com/Sage-Bionetworks/synapse-web-monorepo/assets/83617519/be609bd4-a7e6-4a2b-8fdf-8c8b290ca9d5
=> PORTALS-2885: render SynapsePlot only when showFacetVisualization is true

packages/synapse-react-client/package.json
Releasing to pull SRC changes for SWC-6627 into SWC
=> Release synapse-react-client v3.1.74

packages/synapse-react-client/src/components/Authentication/TwoFactorAuthSettingsPanel.test.tsx, packages/synapse-react-client/src/components/Authentication/TwoFactorAuthSettingsPanel.tsx
Supports https://github.com/Sage-Bionetworks/SynapseWebClient/pull/5271
=> SWC-6354 - Expose ability to hide 2FA panel title

packages/synapse-react-client/package.json
Releasing to pull SRC changes for SWC-6660 into SWC
=> Release synapse-react-client v3.1.75

packages/synapse-react-client/src/components/CreateTableViewWizard/CreateTableViewWizard.integration.test.tsx, packages/synapse-react-client/src/components/CreateTableViewWizard/CreateTableViewWizard.stories.tsx, packages/synapse-react-client/src/components/CreateTableViewWizard/CreateTableViewWizard.tsx, packages/synapse-react-client/src/components/EvaluationFinder/EvaluationFinder.test.tsx, packages/synapse-react-client/src/components/EvaluationFinder/EvaluationFinder.tsx
https://github.com/Sage-Bionetworks/synapse-web-monorepo/assets/17580037/c6cf0b19-46b6-4b6a-8397-8ad7fab0039f
=> SWC-6678 - Automatically add default columns for views

apps/SageAccountWeb/src/AppInitializer.tsx, apps/portals/src/AppInitializer.tsx, apps/synapse-oauth-signin/src/AppInitializer.tsx, packages/synapse-react-client/src/utils/AppUtils/AppUtils.ts
Not directly related to PORTALS-2670, but trying to do some cleanup to make PORTALS-2670 easier
=> PORTALS-2670 - Deduplicate frame-busting code with a new hook

apps/portals/src/_Core.scss, packages/synapse-react-client/src/components/UserCard/UserCard.integration.test.tsx, packages/synapse-react-client/src/components/UserCard/UserCard.stories.tsx, packages/synapse-react-client/src/components/UserCard/UserCardContextMenu.tsx, packages/synapse-react-client/src/components/UserCard/UserCardMedium.tsx, packages/synapse-react-client/src/style/base/_core.scss, packages/synapse-react-client/src/style/base/_modal.scss, packages/synapse-react-client/src/style/components/_login.scss, packages/synapse-react-client/src/template_style/_theme.scss
Fixes SWC-6541
- Reimplement UserCardContextMenu with MUI, fixing many bugs
- Remove many unused styles
=> SWC-6541 - Fix issues with UserCardContextMenu

apps/SageAccountWeb/src/components/RegisterAccount1.tsx, packages/synapse-react-client/src/components/ChallengeSubmission/SubmissionDirectoryList.tsx, packages/synapse-react-client/src/components/ChallengeTeamWizard/ChallengeTeamTable.tsx, packages/synapse-react-client/src/components/ChallengeTeamWizard/ChallengeTeamWizard.tsx, packages/synapse-react-client/src/synapse-client/SynapseClient.ts, packages/synapse-react-client/src/synapse-queries/entity/useGetEntityChildren.test.ts, packages/synapse-types/src/ChallengePagedResults.ts, packages/synapse-types/src/EntityChildren.ts, packages/synapse-types/src/MembershipInvitation.ts, packages/synapse-types/src/Team.ts, packages/synapse-types/src/TeamMember.ts
- Add various types for request objects that are used in Challenge Portal components.
This is part of an incremental set of changes that are designed to 
- Fix bugs and improve maintainability of the Challenge Portal components
- Allow us to upgrade react-query to v5
=> SWC-6545, PORTALS-2936 - Type improvements

packages/synapse-react-client/src/components/AccessRequirementList/AccessRequirementList.tsx, packages/synapse-react-client/src/components/ChallengeRequirementsModal/ChallengeRequirementsModal.tsx, packages/synapse-react-client/src/components/DialogBase.tsx
- Revert changes to dialog rendering in #720
- Change AccessRequirementList to accept custom dialog actions
- Update ChallengeRequirementsModal to pass the Register button as a custom action
=> PORTALS-2960 - Fix double title/actions in access requirement dialog

packages/synapse-react-client/src/components/ChallengeSubmission/AvailableEvaluationQueueList.stories.tsx, packages/synapse-react-client/src/components/ChallengeSubmission/AvailableEvaluationQueueList.test.tsx, packages/synapse-react-client/src/components/ChallengeSubmission/AvailableEvaluationQueueList.tsx, packages/synapse-react-client/src/components/ChallengeSubmission/index.ts, packages/synapse-react-client/src/mocks/entity/mockEvaluationQueue.ts, packages/synapse-react-client/src/mocks/faker/generateEvaluation.ts, packages/synapse-react-client/src/umd.index.ts
SWC integration in https://github.com/Sage-Bionetworks/SynapseWebClient/pull/5298.
https://github.com/Sage-Bionetworks/synapse-web-monorepo/assets/26949006/6f58dc5a-9a80-4bd5-ab4b-b5db9dd968d7
=> SWC-6684: add autocomplete input to handle case where there are many available evaluation queues

packages/synapse-react-client/src/components/ChallengeSubmission/EvaluationQueueList.tsx, packages/synapse-react-client/src/components/ChallengeSubmission/SubmissionCommitList.tsx, packages/synapse-react-client/src/components/ChallengeSubmission/SubmissionDirectoryList.tsx, packages/synapse-react-client/src/components/ChallengeTeamWizard/ChallengeTeamTable.tsx
=> PORTALS-2893 - Fix vertical alignment of radio buttons in Challenge portal table components

packages/synapse-react-client/src/components/SchemaDrivenAnnotationEditor/SchemaDrivenAnnotationEditor.tsx, packages/synapse-react-client/src/components/entity/metadata/AnnotationsTable.tsx, packages/synapse-react-client/src/components/entity/metadata/EntityModal.tsx, packages/synapse-react-client/src/synapse-client/SynapseClient.ts, packages/synapse-react-client/src/synapse-queries/KeyFactory.ts, packages/synapse-react-client/src/synapse-queries/dataaccess/useAccessRequirements.ts, packages/synapse-react-client/src/synapse-queries/entity/useEntity.ts, packages/synapse-react-client/src/utils/APIConstants.ts, packages/synapse-react-client/src/utils/functions/ArrayUtils.ts
SWC-6105
- Get annotations for specified version in AnnotationsTable.tsx
- Simplify entity query keys
=> SWC-6105 - Get annotations for specified version in AnnotationsTable.tsx

packages/synapse-react-client/demo/containers/playground/ColorPaletteInspector.tsx
=> make the color palette demo less overwhelming

apps/portals/src/portal-components/DetailsPage/_DetailsPage.scss
https://github.com/Sage-Bionetworks/synapse-web-monorepo/assets/26949006/647bc4ac-01af-4871-b45e-61acf860ec74
=> PORTALS-2553: make toc control sticky

packages/synapse-react-client/src/components/ReleaseCard/ReleaseCardLarge.tsx
https://github.com/Sage-Bionetworks/synapse-web-monorepo/assets/26949006/d59a88ff-a9cf-429d-8a56-a9461dce1974
=> PORTALS-2961: improve handling at small breakpoints based on design feedback

packages/synapse-react-client/src/components/SynapseTable/SearchV2.tsx
See PORTALS-2980
Fix regression caused in #769
=> PORTALS-2980

.github/workflows/build-and-deploy-app.yml, .github/workflows/build-and-deploy-portal.yml
This PR enables actual deployment of an app to an S3 bucket + update couple deps.
=> Enable deploy app

packages/synapse-react-client/src/components/TableColumnSchemaEditor/ColumnModelFormFields/DefaultValueField.test.tsx, packages/synapse-react-client/src/components/TableColumnSchemaEditor/ColumnModelFormFields/DefaultValueField.tsx
=> SWC-6718 - Fix issue where _LIST column default values were not shown

packages/synapse-react-client/src/components/DateTimePicker/DateTimePicker.tsx, packages/synapse-react-client/src/components/Evaluation/EvaluationRoundEditor.tsx, packages/synapse-react-client/src/components/TableColumnSchemaEditor/ColumnModelFormFields/DefaultValueField.test.tsx, packages/synapse-react-client/src/components/TableColumnSchemaEditor/ColumnModelFormFields/DefaultValueField.tsx, packages/synapse-react-client/src/components/TableColumnSchemaEditor/ColumnModelFormFields/MultiValueField.stories.tsx, packages/synapse-react-client/src/components/TableColumnSchemaEditor/ColumnModelFormFields/MultiValueField.test.tsx
=> SWC-6724 - Fix issue where DATE columns would incorrectly parse a string that was a unix timestamp

packages/synapse-react-client/src/components/HasAccess/HasAccessV2.tsx
Discovered while investigating SWC-6711
=> Replace useState + useEffect with useMemo in useGetFileHandleDownloadType

packages/synapse-react-client/src/components/EntityFinder/details/view/DetailsView.tsx, packages/synapse-react-client/src/style/components/entity_finder/_details-view.scss
=> SWC-6702: fix text overflow in name column of EntityFinder

apps/portals/src/configurations/genie/.env
Updating the content on the homepage banner.
=> Update GENIE homepage header

apps/portals/src/configurations/elportal/synapseConfigs/computational_tools.ts, apps/portals/src/configurations/elportal/synapseConfigs/projects.ts, apps/portals/src/configurations/elportal/synapseConfigs/studies.ts
grants and projects are many-to-many
=> PORTALS-3031 - changes to match new schema

packages/synapse-react-client/package.json
apparently the version checker action only looks at the commit message
=> Reset version

packages/synapse-react-client/package.json
Bumping again for an automatic release
=> Bump synapse-react-client to v3.2.9

.github/workflows/npmpublish.yml
See difficulties in #887, #888, #889, #890
=> Version check should check the diff for a version change

apps/portals/src/configurations/adknowledgeportal/resources.ts
Caught an error in our file view while reviewing on staging, so we created another snapshot with the correction and need to bump the version again.
=> increment AD file view - 24.4.1 release patch

apps/portals/src/configurations/nf/resources.ts
Hi! This is a somewhat urgent PR that fixes some broken data on prod and staging.
=> fix broken dataset versions: Update resources.ts

packages/synapse-react-client/src/components/AccessRequirementAclEditor/AccessRequirementAclEditor.test.tsx, packages/synapse-react-client/src/components/AccessRequirementAclEditor/AccessRequirementAclEditor.tsx, packages/synapse-react-client/src/components/CreateOrUpdateAccessRequirementWizard/CreateOrUpdateAccessRequirementWizard.integration.test.tsx, packages/synapse-react-client/src/components/CreateOrUpdateAccessRequirementWizard/CreateOrUpdateAccessRequirementWizard.stories.tsx, packages/synapse-react-client/src/components/CreateOrUpdateAccessRequirementWizard/CreateOrUpdateAccessRequirementWizard.tsx, packages/synapse-react-client/src/components/CreateOrUpdateAccessRequirementWizard/CreateOrUpdateAccessRequirementWizardUtils.ts, packages/synapse-react-client/src/components/CreateOrUpdateAccessRequirementWizard/index.ts, packages/synapse-react-client/src/mocks/msw/handlers/accessRequirementAclHandlers.ts, packages/synapse-react-client/src/umd.index.ts
Adds new wizard to create/update ARs. See https://github.com/Sage-Bionetworks/SynapseWebClient/pull/5368
=> SWC-6730: add create or update AR wizard

.github/workflows/deploy-to-chromatic.yml
Workaround for chromaui/chromatic-cli/issues/975
=> downgrade chromaui/action to v11.3.0

packages/synapse-react-client/src/components/Authentication/TwoFactorAuthSettingsPanel.test.tsx, packages/synapse-react-client/src/components/Authentication/TwoFactorAuthSettingsPanel.tsx
=> SWC-6841 - Show confirmation dialog before deactivating 2FA

packages/synapse-react-client/src/utils/AppUtils/session/ApplicationSessionManager.tsx, packages/synapse-react-client/src/utils/hooks/useDetectSSOCode.test.ts, packages/synapse-react-client/src/utils/hooks/useDetectSSOCode.ts
revert latest commit, but make one suggested code review change (prop name and default value)
=> PORTALS-3086

apps/SageAccountWeb/src/components/ProfileValidation/ProfileValidation.tsx
=> Fix broken links in profile validation flow

apps/synapse-oauth-signin/src/OAuth2Form.tsx, apps/synapse-oauth-signin/src/test/App.test.tsx
=> PORTALS-3089 - Show error if param(s) are missing

apps/synapse-oauth-signin/src/OAuth2Form.tsx, apps/synapse-oauth-signin/src/test/App.test.tsx
=> PORTALS-3094 - do not show error when signing in with IdP + 2FA

.github/workflows/deploy-sage-account-web-staging.yml
This PR updates the deployment targets for the staging stack.
Depends on: https://github.com/Sage-Bionetworks-IT/organizations-infra/pull/1155
=> IT-3681: Update bucket/distribution - staging

.github/workflows/deploy-app-prod.yml
This PR updates the bucket and and distributionID for the deployment of OneSage to production.
=> IT-3681: Update bucket and distID

apps/SageAccountWeb/src/AppInitializer.tsx
If on staging One Sage, point to the staging backend stack
=> PORTALS-3138

apps/SageAccountWeb/src/components/AccountSettings.tsx, packages/synapse-react-client/src/components/Authentication/UsernamePasswordForm.tsx, packages/synapse-react-client/src/components/ChangePassword/ChangePassword.integration.test.tsx, packages/synapse-react-client/src/components/ChangePassword/ChangePassword.tsx, packages/synapse-react-client/src/components/ChangePassword/useChangePasswordFormState.tsx
=> SWC-6844 - Features that rely on CHANGE_PASSWORD_2FA_CHECK_BYPASS feature flag should point to OneSage 

apps/SageAccountWeb/src/components/CertificationQuiz.tsx, packages/synapse-react-client/src/components/CertificationQuiz/CertificationAnswer.tsx, packages/synapse-react-client/src/components/CertificationQuiz/CertificationQuiz.integration.test.tsx, packages/synapse-react-client/src/components/CertificationQuiz/CertificationQuiz.tsx, packages/synapse-react-client/src/components/MuiContainer.tsx, packages/synapse-react-client/src/components/index.ts, packages/synapse-react-client/src/style/components/_certification-quiz.scss
https://sagebionetworks.jira.com/browse/PORTALS-3131
=> PORTALS-3131: clean up certification quiz (removes bootstrap)

apps/SageAccountWeb/src/AppInitializer.tsx, packages/synapse-react-client/src/synapse-client/SynapseClient.ts
This reverts commit 1df09cec5e30f3b6104513a1877b22dd31bb8207.
=> Revert "fix endpoints for staging"

apps/portals/src/configurations/nf/synapseConfigs/datasets.ts, packages/synapse-react-client/src/components/GenericCard/Linkify.test.tsx, packages/synapse-react-client/src/components/GenericCard/Linkify.tsx
Add cbioportal linkify rule, and additional column to NF dataset card
=> PORTALS-3140

packages/synapse-react-client/package.json, packages/synapse-react-client/src/utils/hooks/useLogin.test.tsx, packages/synapse-react-client/src/utils/hooks/useLogin.ts
- Fix case where 2FA could not be reset during OAuth
- Release synapse-react-client v3.2.22
=> SWC-6872 - Fix case where 2FA could not be reset during OAuth

apps/SageAccountWeb/src/components/ResetPassword.tsx, packages/synapse-react-client/src/components/Authentication/LoginForm.tsx, packages/synapse-react-client/src/synapse-client/SynapseClient.ts, packages/synapse-react-client/src/synapse-queries/auth/index.ts, packages/synapse-react-client/src/synapse-queries/auth/useResetPassword.ts, packages/synapse-react-client/src/utils/appendFinalQueryParamKey.test.ts, packages/synapse-react-client/src/utils/appendFinalQueryParamKey.ts
- Fix URL when resetting password from synapse.org
- Only allow sending one reset password request per email/username
=> PORTALS-3151, PORTALS-3152

apps/SageAccountWeb/package.json, apps/portals/package.json, apps/synapse-oauth-signin/package.json, package.json, packages/markdown-it-synapse/package.json, packages/synapse-react-client/package.json, packages/synapse-react-client/src/components/ChangePassword/ChangePassword.integration.test.tsx, packages/synapse-react-client/src/components/ChangePassword/ChangePasswordWithToken.integration.test.tsx, packages/synapse-react-client/src/components/ChangePassword/ChangePasswordWithToken.tsx, packages/synapse-react-client/src/components/ChangePassword/index.ts, packages/synapse-react-client/src/components/SynapseForm/SummaryTable.tsx, packages/synapse-types/package.json, packages/vite-config/package.json, pnpm-lock.yaml, shared/tsconfig.base.json
- Upgrade TypeScript to v5.5.2
- Update tsconfig.base.json to use new `configDir` feature
- Fix new lint error in SummaryTable.tsx
=> PORTALS-3168 - Upgrade TypeScript to v5.5

apps/SageAccountWeb/src/components/AccountSettings.tsx, packages/synapse-react-client/src/utils/hooks/useCookiePreferences.ts
=> SWC-6826: must set to sub domain to share cookie

packages/synapse-react-client/package.json
Contains 1 bug fix for date/time preference cookie, and cookie preferences cookie
=> Release SRC 3.2.28

apps/SageAccountWeb/src/components/AccountSettings.tsx, apps/SageAccountWeb/src/components/ProfileValidation/ProfileValidation.tsx
=> PORTALS-3175

apps/portals/adknowledgeportal/package.json, apps/portals/arkportal/package.json, apps/portals/bsmn/package.json, apps/portals/cancercomplexity/package.json, apps/portals/challengeportal/package.json, apps/portals/crc-researcher/package.json, apps/portals/digitalhealth/package.json, apps/portals/elportal/package.json, apps/portals/genie/package.json, apps/portals/nf/package.json, apps/portals/psychencode/package.json, apps/portals/stopadportal/package.json, apps/synapse-portal-framework/run.sh
it can (and should!) be run from the monorepo root.
=> PORTALS-2521 - attempt to fix run.sh

packages/synapse-react-client/src/components/Authentication/StandaloneLoginForm/Login.stories.ts, packages/synapse-react-client/src/components/EntityHeaderTable/EntityHeaderTable.tsx, packages/synapse-react-client/src/components/Forum/ForumTable.tsx, packages/synapse-react-client/src/components/OAuthClientManagement/OAuthManagement.tsx, packages/synapse-react-client/src/components/StyledTanStackTable/StyledTanStackTable.tsx, packages/synapse-react-client/src/components/SynapseTable/SynapseTable.integration.test.tsx, packages/synapse-react-client/src/components/Table/Table.tsx, packages/synapse-react-client/src/components/dataaccess/AccessRequirementTable.integration.test.tsx, packages/synapse-react-client/src/components/dataaccess/AccessRequirementTable.tsx, packages/synapse-react-client/src/components/dataaccess/UseAccessRequirementTable.tsx, packages/synapse-react-client/src/components/styled/ColumnHeader.tsx, packages/synapse-react-client/src/components/styled/StyledTableContainer.tsx, packages/synapse-react-client/src/components/trash/TrashCanList.tsx, packages/synapse-react-client/src/style/components/_governance-dashboard.scss
Addition of feature will be in a later PR
=> SWC-6896 - Refactor AccessRequirementTable to use @tanstack/react-table

apps/portals/adknowledgeportal/src/config/resources.ts
=> Bump ADTR fileview version for portal

packages/synapse-react-client/src/components/SynapseForm/SynapseFormWrapper.tsx, packages/synapse-react-client/src/style/components/synapse_form_wrapper/_synapse-form-wrapper.scss
=> PORTALS-3021 - Fix error handling & style issue in SynapseFormWrapper

packages/synapse-react-client/src/components/entity/page/action_menu/EntityActionMenu.test.tsx, packages/synapse-react-client/src/components/entity/page/action_menu/EntityActionMenu.tsx, packages/synapse-react-client/src/components/menu/DropdownMenu.tsx
Also show an icon if one was specified.
=> SWC-6798 - Allow the download menu to be collapsed down to one button

apps/synapse-portal-framework/src/components/crc-researcher/ParticipantsBarPlot.tsx, apps/synapse-portal-framework/src/components/crc-researcher/StatusLineChart.tsx, packages/synapse-react-client/src/components/Plot/DotPlot.test.ts, packages/synapse-react-client/src/components/Plot/DotPlot.tsx, packages/synapse-react-client/src/components/Plot/ThemesPlot.tsx, packages/synapse-react-client/src/utils/functions/SqlFunctions.ts
See final screenshot in https://sagebionetworks.jira.com/browse/PORTALS-3079?focusedCommentId=213602&page=com.atlassian.jira.plugin.system.issuetabpanels%3Acomment-tabpanel#comment-213602
=> PORTALS-3079 - Add offset to DotPlot, ThemesPlot should use log axis

apps/portals/adknowledgeportal/src/config/resources.ts
De-pegging this table from the snapshot version as well.
=> use live ADKP file view for metadata table

apps/SageAccountWeb/src/components/AccountSettings.tsx, apps/synapse-oauth-signin/src/mocks/handlers.ts, packages/synapse-react-client/src/synapse-client/SynapseClient.ts, packages/synapse-react-client/src/utils/APIConstants.ts
=> SWC-6929 - Delete token on logout

apps/portals/cancercomplexity/src/config/synapseConfigs/education.ts
* add `titleLinkConfig` for resources card
**Before**
**After**
=> CPO-1271: Link to listed educational resources

packages/synapse-react-client/src/components/ChangePassword/ChangePassword.integration.test.tsx, packages/synapse-react-client/src/components/ChangePassword/ChangePasswordWithToken.integration.test.tsx, packages/synapse-react-client/src/components/CreateTableViewWizard/CreateTableViewWizard.integration.test.tsx, packages/synapse-react-client/src/components/entity/metadata/AnnotationsTable.integration.test.tsx, packages/synapse-react-client/src/components/entity/page/title_bar/TitleBarProperties.integration.test.tsx, packages/synapse-react-client/src/mocks/msw/handlers/featureFlagHandlers.ts, packages/synapse-react-client/test/containers/EntityBadgeIcons.integration.test.tsx
server.ts -> handlers.ts -> featureFlagHandlers.ts -> server.ts
=> Fix issue where handlers had a dependency cycle that would cause Storybook to not work

packages/synapse-react-client/src/components/CardContainer/CardContainer.tsx, packages/synapse-react-client/src/components/QueryWrapperPlotNav/RowSetView.tsx, packages/synapse-react-client/src/components/UserCardList/UserCardList.tsx, packages/synapse-react-client/src/components/UserCardList/UserCardListRotate.tsx, packages/synapse-react-client/src/style/components/_query-wrapper-plot-nav.scss, packages/synapse-react-client/src/utils/context/FullContextProvider.tsx
- Update UserCardList to prevent merging the bundle
- Add comments/conditions to clarify strange-looking loader JSX in RowSetView
- Update FilterAndView classname to be RowSetView
- Add "just-in-case" suspense to FullContextProvider
=> PORTALS-2970 - changes from review

packages/synapse-react-client/src/components/error/ErrorPage.tsx
=> SWC-6763: fix mobile experience

packages/synapse-react-client/src/components/AclEditor/ResourceAccessItem.tsx, packages/synapse-react-client/src/components/TeamBadge.tsx, packages/synapse-react-client/src/components/UserOrTeamBadge/UserOrTeamBadge.tsx
=> SWC-7048 - User/team links in ACL editor should open in new page

apps/portals/adknowledgeportal/src/config/resources.ts
=> Bump ADKP version in resources.ts

packages/synapse-react-client/src/components/SynapseForm/SynapseForm.tsx, packages/synapse-react-client/src/components/SynapseForm/SynapseFormCheckboxWidget.tsx, packages/synapse-react-client/src/components/SynapseForm/SynapseFormCheckboxesWidget.tsx, packages/synapse-react-client/src/components/SynapseForm/SynapseFormRadioWidget.tsx, packages/synapse-react-client/src/components/SynapseForm/SynapseFormWrapper.stories.tsx
=> PORTALS-3246

apps/portals/elportal/src/config/resources.ts, apps/portals/elportal/src/config/routesConfig.tsx
Change ELITE portal partnersSql (order by) and update title link column
=> PORTALS-3208

packages/synapse-react-client/package.json
This is to include this small update to the chatbot (to report any progress it receives from the backend async job when processing a message).  https://github.com/Sage-Bionetworks/synapse-web-monorepo/pull/1226
=> Release SRC 3.3.15

apps/SageAccountWeb/src/App.tsx, apps/SageAccountWeb/src/components/AccountSettings.tsx, apps/SageAccountWeb/src/components/ConfigureEmail.tsx, apps/SageAccountWeb/src/components/RegisterAccount1.tsx, apps/SageAccountWeb/src/components/WebhooksManagementPage.tsx, apps/SageAccountWeb/src/style/theme.ts, packages/synapse-react-client/src/components/DialogBase.tsx, packages/synapse-react-client/src/components/HelpPopover/HelpPopover.tsx, packages/synapse-react-client/src/components/Markdown/MarkdownPopover.tsx, packages/synapse-react-client/src/components/StorybookComponentWrapper.tsx, packages/synapse-react-client/src/components/Webhook/CreateWebhookModal.tsx, packages/synapse-react-client/src/components/Webhook/WebhookDashboard.stories.ts, packages/synapse-react-client/src/components/Webhook/WebhookDashboard.test.tsx, packages/synapse-react-client/src/components/Webhook/WebhookDashboard.tsx, packages/synapse-react-client/src/components/Webhook/WebhookVerificationDialog.tsx, packages/synapse-react-client/src/components/styled/StyledTableContainer.tsx, packages/synapse-react-client/src/index.ts, packages/synapse-react-client/src/mocks/msw/handlers.ts, packages/synapse-react-client/src/mocks/msw/handlers/webhookHandlers.ts, packages/synapse-react-client/src/mocks/msw/util/BasicMockedCrudService.ts, packages/synapse-react-client/src/synapse-queries/KeyFactory.ts, packages/synapse-react-client/src/synapse-queries/webhook/useWebhook.ts, packages/synapse-react-client/src/utils/context/SynapseContext.tsx
- Add components to manage webhooks
- Add webhooks page to SageAccountWeb
- Attempt to make some SageAccountWeb theme styles consistent
=> SWC-7061 - Add WebhookDashboard component

apps/SageAccountWeb/src/components/RegisterAccount2.tsx
=> PORTALS-3242

apps/SageAccountWeb/src/App.tsx, apps/SageAccountWeb/src/components/AccountSettings.tsx, apps/SageAccountWeb/src/components/Footer.tsx, apps/SageAccountWeb/src/style/_AccountSetting.scss, packages/synapse-react-client/src/mocks/msw/handlers/featureFlagHandlers.ts, packages/synapse-types/src/FeatureFlags.ts
- Put webhooks under feature flag
- Add footer to accounts site to allow toggling experimental mode
=> Webhooks under feature flag

apps/synapse-portal-framework/sitemap/generate-sitemap.cjs, apps/synapse-portal-framework/src/components/DetailsPage/DetailsPageContentLayout.tsx, apps/synapse-portal-framework/src/components/DetailsPage/DetailsPageContext.tsx, apps/synapse-portal-framework/src/components/DetailsPage/markdown/MarkdownSynapseFromColumnData.tsx, apps/synapse-portal-framework/src/components/DetailsPage/markdown/useColumnDataMarkdownProps.ts, apps/synapse-portal-framework/src/components/transformStringIntoMarkdownProps.ts, apps/synapse-portal-framework/src/shared-config/sharedRoutes.tsx
* Changes from review
* Small fix for sitemap generator
=>  PORTALS-3195 - Changes from review 

apps/SageAccountWeb/package.json, apps/SageAccountWeb/src/AppInitializer.tsx, apps/synapse-oauth-signin/src/AppInitializer.tsx, packages/synapse-react-client/src/components/Authentication/Login.test.tsx, packages/synapse-react-client/src/components/SynapseHomepageV2/SynapseHomepageNavBar.tsx, packages/synapse-react-client/src/components/SynapseHomepageV2/__snapshots__/SynapseHomepageV2.test.tsx.snap, packages/synapse-react-client/src/utils/SynapseConstants.ts, packages/synapse-react-client/src/utils/functions/getEndpoint.ts, packages/synapse-react-client/src/utils/hooks/useDetectSSOCode.test.ts, packages/synapse-react-client/src/utils/hooks/useOneSageURL.test.ts, packages/synapse-react-client/src/utils/hooks/useOneSageURL.ts
https://sagebionetworks.jira.com/browse/SWC-7123
=> SWC-7123: When on localhost, links to OneSage should also be on localhost

packages/synapse-react-client/.storybook/storybook-vite.config.mts
No need to build the library/types
=> Fix storybook build job crashing

packages/synapse-react-client/src/components/TableColumnSchemaEditor/TableColumnSchemaEditorUtils.test.ts, packages/synapse-react-client/src/components/TableColumnSchemaEditor/TableColumnSchemaEditorUtils.ts
=> SWC-7084 - ENTITYID_LIST can have a max list length

packages/synapse-react-client/src/utils/ContentTypeUtils.test.ts, packages/synapse-react-client/src/utils/ContentTypeUtils.ts
Reimplemented utilities that will be required for the uploader to work.
=> SWC-7064 - Reimplementation of ContentTypeUtils from SWC

apps/portals/nf/src/config/synapseConfigs/tools.ts
Jira Ticket: https://sagebionetworks.jira.com/browse/PORTALS-3275?atlOrigin=eyJpIjoiYmYyMTEwMjkzNTQ1NDZkZThkZDczMWRlNDVhNWZkZTUiLCJwIjoiaiJ9
=> PORTALS-3275: move mutations header

packages/synapse-react-client/package.json
=> Release SRC 3.3.25

apps/synapse-portal-framework/src/components/DetailsPage/DetailsPage.tsx
Jira Ticket: https://sagebionetworks.jira.com/browse/PORTALS-3268?atlOrigin=eyJpIjoiMTU5YjYzYjRhZTRlNDQ3NDgxN2E4YjQxMTgzNDkzZWYiLCJwIjoiaiJ9
Fix alignment of Details page section title and help icon.
=> PORTALS-3268: Helper tool tip button not horizontally aligned with header

packages/synapse-react-client/src/style/components/_cards.scss
Jira Ticket: https://sagebionetworks.jira.com/browse/PORTALS-3278?atlOrigin=eyJpIjoiZTU1YmI5NWJiYzg3NGU1NWI3YWYzNDFkMzNlNmU4MjYiLCJwIjoiaiJ9
Before Ex:
After Ex:
=> PORTALS-3278: fix uneven spacing in metadata fields on cards

apps/portals/adknowledgeportal/src/config/resources.ts
=> Bump ADKP version resources.ts

packages/synapse-react-client/src/components/DialogBase.tsx, packages/synapse-react-client/src/components/EntityUpload/EntityUploadModal.stories.ts, packages/synapse-react-client/src/components/EntityUpload/EntityUploadModal.tsx, packages/synapse-react-client/src/components/EntityUpload/LinkToURL.tsx, packages/synapse-react-client/src/utils/hooks/useUploadFileEntity/useLinkFileEntityToURL.test.ts, packages/synapse-react-client/src/utils/hooks/useUploadFileEntity/useLinkFileEntityToURL.ts
=> SWC-7064 - Entity Upload: add Link to URL tab

packages/synapse-react-client/src/components/EntityUpload/EntityUpload.test.tsx, packages/synapse-react-client/src/components/EntityUpload/EntityUpload.tsx, packages/synapse-react-client/src/components/EntityUpload/ProjectStorageLimitAlert.stories.tsx, packages/synapse-react-client/src/components/EntityUpload/ProjectStorageLimitAlert.test.tsx, packages/synapse-react-client/src/components/EntityUpload/ProjectStorageLimitAlert.tsx, packages/synapse-react-client/src/components/ProjectStorage/ProjectDataAvailability.tsx, packages/synapse-react-client/src/components/SynapseHomepageV2/SynapseHomepageV2.tsx, packages/synapse-react-client/src/components/SynapseHomepageV2/SynapsePlans.tsx, packages/synapse-react-client/src/mocks/mock_upload_destination.ts, packages/synapse-react-client/src/mocks/msw/handlers/entityHandlers.ts, packages/synapse-react-client/src/mocks/projectStorage/mockProjectStorageLimits.ts, packages/synapse-react-client/src/utils/SynapseConstants.ts, packages/synapse-react-client/src/utils/functions/calculateFriendlyFileSize.ts, packages/synapse-react-client/src/utils/hooks/useUploadFileEntity/useTrackFileUploads.test.ts, packages/synapse-react-client/src/utils/hooks/useUploadFileEntity/useTrackFileUploads.ts, packages/synapse-react-client/src/utils/hooks/useUploadFileEntity/useUploadFileEntities.test.ts, packages/synapse-react-client/src/utils/hooks/useUploadFileEntity/useUploadFileEntities.ts, packages/synapse-react-client/src/utils/hooks/useUploadFileEntity/willUploadsExceedStorageLimit.test.ts, packages/synapse-react-client/src/utils/hooks/useUploadFileEntity/willUploadsExceedStorageLimit.ts, packages/synapse-types/src/File/UploadDestination.ts, packages/synapse-types/src/ProjectStorage.ts
- UI + logic for storage limit alerts
- Update types for ProjectStorage objects
- Use constant for Sage Offerings help docs links
=> SWC-7064 - Project storage limit alert

.github/workflows/deploy-sage-account-web-dev.yaml
This PR adds a dispatch workflow to build and deploy SageAccountWeb to the dev bucket
Depends on the OIDC role to be updated https://github.com/Sage-Bionetworks-IT/organizations-infra/pull/1274
=> IT-3849: Add workflow to deploy dev.accounts.synapse.org

apps/portals/nf/src/pages/ToolDetailsPage/ToolDetailsPageObservationsTab.tsx
Jira: https://sagebionetworks.jira.com/browse/PORTALS-3272?focusedCommentId=226872&page=com.atlassian.jira.plugin.system.issuetabpanels%3Acomment-tabpanel#comment-226872
=> PORTALS-3272-v2: remove extra natural history timeline

packages/synapse-react-client/src/components/AccessRequirementList/ManagedACTAccessRequirementRequestFlow/ResearchProjectForm/ResearchProjectForm.test.tsx, packages/synapse-react-client/src/components/AccessRequirementList/ManagedACTAccessRequirementRequestFlow/ResearchProjectForm/ResearchProjectForm.tsx, packages/synapse-react-client/src/components/TextField/TextFieldWithWordLimit.stories.ts, packages/synapse-react-client/src/components/TextField/TextFieldWithWordLimit.test.tsx, packages/synapse-react-client/src/components/TextField/TextFieldWithWordLimit.tsx, packages/synapse-react-client/src/mocks/dataaccess/MockResearchProject.ts, packages/synapse-react-client/src/theme/DefaultTheme.tsx
- Add TextFieldWithWordLimit
- Use TextFieldWithWordLimit for IDU statement in ResearchProjectForm
- Update label, placeholder text in ResearchProjectForm
- Add light validation to ResearchProjectForm to block submission.
- Update global theme to color the 'required' asterisk on inputs
https://github.com/user-attachments/assets/871a1b54-b55e-42c0-8fbe-20cee2f0e658
=> SWC-7137 - ResearchProjectForm improvements

apps/portals/adknowledgeportal/src/config/resources.ts
versioned FileView to syn11346063.64 and updated this file accordingly
=> Update resources.ts for ADKP data release 24.11

packages/synapse-react-client/src/components/Forum/DiscussionSearchResult.tsx, packages/synapse-react-client/src/components/ForumSearch/ForumSearch.stories.ts, packages/synapse-react-client/src/components/ForumSearch/ForumSearch.tsx, packages/synapse-react-client/src/style/components/_discussion-search.scss, packages/synapse-react-client/src/synapse-queries/KeyFactory.ts, packages/synapse-react-client/src/synapse-queries/forum/useForum.ts
ForumSearch:
- Fix bug where displayed search query text matched the input rather than the last search query
- Update use an infinite query instead of custom implementation
- Re-aligned Load More button to match convention
- Remove some unnecessary CSS classes & bootstrap styling
DiscussionSearchResult
- Fix data-fetching effect to update when dependencies change
- Fix data-fetching effect to set loading state before fetching the thread
- Replace proportional bootstrap grid with CSS Grid with constant width of first column
- Minor tweaks to layout of content & skeletons
=> SWC-7198 - Forum Search bug fixes and UI tweaks

apps/portals/adknowledgeportal/src/pages/StudyDetailsPage.tsx, apps/synapse-portal-framework/src/components/DetailsPage/DetailsPageContext.tsx, apps/synapse-portal-framework/src/components/DetailsPage/HeadlineWithLink.tsx
- fix bug where 'undefined' string was displayed
- fix ADKP bug where ACK_CONTEXT markdown was displayed twice instead of the specific acknowledgement statement for the study
=> PORTALS-3353

packages/synapse-react-client/src/components/OrientationBanner/OrientationBanner.tsx
Hide Orientation Banner on mobile screens
Jira: https://sagebionetworks.jira.com/browse/SWC-7166
=> SWC-7166: Hide Banner on Mobile Screens

packages/synapse-react-client/src/components/EntityUpload/EntityUpload.tsx, packages/synapse-react-client/src/utils/hooks/useUploadFileEntity/willUploadsExceedStorageLimit.test.ts, packages/synapse-react-client/src/utils/hooks/useUploadFileEntity/willUploadsExceedStorageLimit.ts, packages/synapse-types/src/File/UploadDestination.ts
=> SWC-7213 - Handle case where `projectStorageLocationUsage` is undefined

packages/synapse-react-client/src/components/entity/page/CreatedByModifiedBy.tsx
Jira Ticket: https://sagebionetworks.jira.com/browse/SWC-7187?atlOrigin=eyJpIjoiNDkxMTk5NjU2OTM0NDY3MWIwODc1OTM4MGIxYmJiNzEiLCJwIjoiaiJ9
Added padding to component:
Similar padding to components above it.
Updated:
=> SWC-7187: SRC CreatedByModifiedBy updates on mobile

packages/synapse-react-client/src/components/UserCard/Avatar.tsx, packages/synapse-react-client/src/components/UserCard/UserCardMedium.tsx, packages/synapse-react-client/src/style/base/_core.scss
Jira Ticket: https://sagebionetworks.jira.com/browse/SWC-7170
I used overrides + editing styles in Chrome to get the output below:
=> SWC-7170: SRC UserCard updates on mobile

apps/portals/elportal/src/themes/HomePageThemeProvider.tsx, packages/synapse-react-client/src/components/GenericCard/GenericCard.tsx, packages/synapse-react-client/src/components/RecentPublicationsGrid/RecentPublicationsGrid.tsx, packages/synapse-react-client/src/components/row_renderers/utils/CardFooter.tsx, packages/synapse-react-client/src/utils/functions/RegularExpressions.ts, packages/synapse-react-client/src/utils/functions/doiUtils.ts
=> Links to Titles on RecentPublicationsGrid Component

packages/synapse-react-client/src/components/DialogBase.tsx
Fixing ConfirmationDialog overflow. Waiting for Adam's input: https://sagebionetworks.jira.com/browse/SWC-7169?focusedCommentId=230439&page=com.atlassian.jira.plugin.system.issuetabpanels%3Acomment-tabpanel#comment-230439
*Update*: My Loom video to confirm things/update Adam with changes: https://www.loom.com/share/b33e639251254d4ca4a2eb2caf72ab33?replyToComment=66429327&start_and_pause=1&t=127
Adjusted padding on mobile since video.
=> SWC-7169-V2

packages/synapse-react-client/src/utils/functions/RegularExpressions.test.ts
Added some tests in RegularExpressions.test.ts to test the convertDoiToLink function.
=> convertDoiToLink tests

packages/synapse-react-client/src/components/EntityFinder/details/view/DetailsView.tsx
=> Remove check on disabled status in click handler

packages/synapse-react-client/src/components/PortalFeatureHighlights/PortalFeatureHighlights.test.tsx, packages/synapse-react-client/src/components/PortalFeatureHighlights/PortalFeatureHighlights.tsx
=> PORTALS-3312 (followup): add a fade and slide to portal feature highlight image

packages/synapse-react-client/src/components/FeaturedResearch/FeaturedResearch.tsx
Jira Ticket: https://sagebionetworks.jira.com/browse/PORTALS-3392
Grow animation added to the image of the main card in the FeaturedResearch component.
=> PORTALS-3392: "Featured Research" follow-up:  Fade in on scroll

packages/synapse-react-client/src/components/ImageCardGridWithLinks/ImageCardGridWithLinks.tsx
Jira Ticket: https://sagebionetworks.jira.com/browse/PORTALS-3391
Loom video recording: https://www.loom.com/share/73af4faa82f04e3d803132cf0d5a8a38
=> PORTALS-3391: "What We Do" follow-up: add hover over effect and expand clickable area

apps/portals/elportal/src/config/routesConfig.tsx, apps/synapse-portal-framework/src/components/SectionLayout.tsx
Jira ticket: https://sagebionetworks.jira.com/browse/PORTALS-3396?atlOrigin=eyJpIjoiNzM2N2M2NzdhYzFmNGY4Y2FjYzliMWJmYzdkMTE3Y2UiLCJwIjoiaiJ9
ImageCardGridWithLinks component's cards should link to wiki pages.
=> PORTALS-3396: New Destination Pages for "What We Do"

apps/portals/elportal/src/config/routesConfig.tsx, apps/synapse-portal-framework/src/components/SectionLayout.tsx
Copy of this branch https://github.com/Sage-Bionetworks/synapse-web-monorepo/pull/1522 with suggested changes.
=> PORTALS-3396-recovered

apps/portals/elportal/src/config/synapseConfigs/handleUpsetPlotClick.tsx
Error does not show up locally (on build or in the IDE), so it's difficult to test.  This is my initial attempt to fix
=> PORTALS-3398: fix type issue

packages/synapse-react-client/src/components/Forum/DiscussionThread.tsx, packages/synapse-react-client/src/components/Forum/ForumThreadEditor.tsx, packages/synapse-react-client/src/style/components/_discussion-forum.scss
- Remove react-bootstrap from forums components
=> PORTALS-2651 - Forums/Threads

apps/SageAccountWeb/package.json, apps/SageAccountWeb/src/components/AccountSettings.tsx, apps/SageAccountWeb/src/components/EmailConfirmationPage.tsx, apps/SageAccountWeb/src/style/_core.scss, apps/synapse-oauth-signin/package.json, apps/synapse-portal-framework/package.json, apps/synapse-portal-framework/src/components/navbar/Navbar.tsx, apps/synapse-portal-framework/src/style/_Core.scss, pnpm-lock.yaml
- Replace react-bootstrap components in apps
=> PORTALS-2651 - Apps

apps/SageAccountWeb/src/components/OAuthClientManagementPage.tsx
SWC-7181 Fix oauth management page padding and overflow on mobile
=> SWC-7181 Fix oauth management page padding and overflow on mobile

apps/portals/elportal/src/pages/HomePageV2.tsx
Jira: https://sagebionetworks.jira.com/browse/PORTALS-3418?atlOrigin=eyJpIjoiMmU5YjBmNzk4YTE1NGI3OGE2Y2JmOTNlMjBmNDkzMDYiLCJwIjoiaiJ9
=> PORTALS-3418: Make logos b&w and reposition slat

packages/synapse-react-client/package.json
To unblock work in SynapseWebClient for SWC-7242
=> Release synapse-react-client v3.4.0

apps/SageAccountWeb/src/components/PersonalAccessTokensPage.tsx, packages/synapse-react-client/src/components/AccessTokenPage/AccessTokenPage.tsx
Jira ticket: https://sagebionetworks.jira.com/browse/SWC-7180
=> SWC-7180: SageAccountWeb: PersonalAccessTokensPage updates on mobile

packages/synapse-react-client/src/components/Authentication/TwoFactorEnrollmentForm.tsx
Jira Ticket: https://sagebionetworks.jira.com/browse/SWC-7179?atlOrigin=eyJpIjoiZmFhZmVmYmE4NTNhNDNkY2JiZWQwYjQ1Yjk5NWUwYWUiLCJwIjoiaiJ9
=> SWC-7179: SageAccountWeb: TwoFactorEnrollmentForm updates on mobile

packages/synapse-react-client/src/components/FeaturedResearch/FeaturedResearch.test.tsx, packages/synapse-react-client/src/components/FeaturedResearch/FeaturedResearch.tsx, packages/synapse-react-client/src/components/PortalFeatureHighlights/PortalFeatureHighlights.tsx, packages/synapse-react-client/src/components/PortalSectionHeader/PortalSectionHeader.tsx
Jira ticket: https://sagebionetworks.jira.com/browse/PORTALS-3417
=> PORTALS-3417: (Mobile view) Adjust placement of 'Featured Research' heading

apps/SageAccountWeb/index.html, apps/SageAccountWeb/src/AppInitializer.tsx, apps/synapse-oauth-signin/src/AppInitializer.tsx, packages/synapse-react-client/src/utils/functions/getEndpoint.ts
More references to the old dev endpoints to change...
=> IT-3849: Updated portal dev endpoint

packages/synapse-react-client/src/components/ForumSearch/ForumSearch.tsx, packages/synapse-react-client/src/components/menu/ComplexMenu.tsx
Jira ticket: https://sagebionetworks.jira.com/browse/SWC-7192
=> SWC-7192: SRC ForumSearch updates on mobile

packages/synapse-react-client/package.json
Primarily to get #1584 in SWC dev deployment
=> Release synapse-react-client v3.4.2

packages/synapse-react-client/package.json
Releasing change with https://github.com/Sage-Bionetworks/synapse-web-monorepo/pull/1585 to enable merge of https://github.com/Sage-Bionetworks/SynapseWebClient/pull/5641
=> Update synapse-react-client to v3.4.3

apps/SageAccountWeb/src/components/TermsOfUsePage.tsx, packages/synapse-react-client/src/components/TermsAndConditions/TermsAndConditions.stories.ts, packages/synapse-react-client/src/components/TermsAndConditions/TermsAndConditions.test.tsx, packages/synapse-react-client/src/components/TermsAndConditions/TermsAndConditions.tsx
- fix ANOTHER terms of use on other page
- remove optional type to force caller to specify table ID
=> IT-3849 - fix more TermsAndConditions

apps/portals/elportal/src/config/explorePageRoutes.tsx
=> PORTALS-3441: update copy for ELITE portal cohort builder

apps/synapse-portal-framework/src/components/DetailsPage/utils.ts
Jira ticket: https://sagebionetworks.jira.com/browse/PORTALS-3397?atlOrigin=eyJpIjoiMDE5NDJlMjM2ZDczNGI4NzhhYmIzY2IyNTQxMWM0ZDQiLCJwIjoiaiJ9
=> PORTALS-3397: DetailPage: Jump (scroll) to section hash fragment not working

apps/portals/cancercomplexity/src/config/routesConfig.tsx, apps/synapse-portal-framework/src/components/cancercomplexity/CancerComplexityHeader.tsx, packages/synapse-types/src/FeatureFlags.ts
Creating a feature flag for the new CCKP header component: https://sagebionetworks.jira.com/browse/PORTALS-3376?atlOrigin=eyJpIjoiNjAyYWFkYjQ2ZDZjNDg3Y2FhZTMyNTIwZTg5Mzk1NTQiLCJwIjoiaiJ9
=> PORTALS-3376-feature-flag

.github/workflows/deploy-synapse-oauth-signin-dev.yml
Don't merge, need to add destination bucket and distribution ID to OIDC.
Depends on https://github.com/Sage-Bionetworks-IT/organizations-infra/pull/1344
=> IT-4313: Add deploy to dev for oauth-signin

.github/workflows/deploy-synapse-oauth-signin-dev.yml, .github/workflows/deploy-synapse-oauth-signin-staging.yml, apps/synapse-oauth-signin/.env, apps/synapse-oauth-signin/.env.development, apps/synapse-oauth-signin/.env.production, apps/synapse-oauth-signin/.env.staging, apps/synapse-oauth-signin/index.html, apps/synapse-oauth-signin/package.json, apps/synapse-oauth-signin/src/AppInitializer.tsx, apps/synapse-oauth-signin/src/vite-env.d.ts
Rely on vite build environment to set the endpoint
=> PORTALS-3459

apps/synapse-oauth-signin/src/AppInitializer.tsx, packages/synapse-react-client/src/components/Forum/DiscussionThread.tsx, packages/synapse-react-client/src/style/components/_markdown-editor.scss
Jira ticket: https://sagebionetworks.jira.com/browse/SWC-7265?atlOrigin=eyJpIjoiNTA5MTZlYThlOGQ4NDYxMmJkMThkMmRkNGNlZmMzMWEiLCJwIjoiaiJ9
Before:
After:
=> SWC-7265: SRC DiscussionThread mobile

apps/portals/cancercomplexity/src/config/synapseConfigs/datasets.ts, apps/portals/cancercomplexity/src/config/synapseConfigs/education.ts, apps/portals/cancercomplexity/src/config/synapseConfigs/tools.ts
Relevant jira tickets: https://sagebionetworks.jira.com/browse/CPO-1427 and https://sagebionetworks.jira.com/browse/PORTALS-3209.
=> Enable Citation for CCKP

apps/synapse-oauth-signin/src/OAuth2Form.tsx, apps/synapse-oauth-signin/src/test/App.test.tsx
=> SWC-7272 - do not re-encode OAuth2 state search parameter

apps/portals/cancercomplexity/src/pages/CCKPSearchPage.tsx, apps/synapse-portal-framework/src/components/HeaderSearchBox.tsx, apps/synapse-portal-framework/src/components/PortalSearch/PortalFullTextSearchField.tsx, apps/synapse-portal-framework/src/components/PortalSearch/PortalSearchPage.tsx, apps/synapse-portal-framework/src/components/PortalSearch/SearchParamAwareStandaloneQueryWrapper.tsx, apps/synapse-portal-framework/src/components/cancercomplexity/CancerComplexityHeader.tsx, packages/synapse-react-client/src/utils/functions/SqlFunctions.ts
Jira: https://sagebionetworks.jira.com/browse/PORTALS-3432
=> PORTALS-3432: [CCKP Homepage_V1] Select a role dropdown for new portal home page search component

apps/portals/nf/src/config/synapseConfigs/publications.ts, packages/synapse-react-client/src/components/CitationPopover/CitationPopover.tsx
Jira: https://sagebionetworks.jira.com/browse/PORTALS-3474?atlOrigin=eyJpIjoiMTJhYjhjNjllM2EzNDY4NTljZmVlNWY1OTcxZGI5ZjAiLCJwIjoiaiJ9
=> PORTALS-3474: Add CiteAs button to publications on NF Data Portal

packages/synapse-react-client/src/components/widgets/facet-nav/FacetNavPanel.tsx
Jira: https://sagebionetworks.jira.com/browse/PORTALS-3428?atlOrigin=eyJpIjoiMTFjNzFlZWJkMGRmNDM1OWFlMDkxMjUzNTg3MDMzY2EiLCJwIjoiaiJ9
=> PORTALS-3428: Remove labels from inside bar charts

apps/synapse-oauth-signin/src/OAuth2Form.tsx, packages/synapse-react-client/src/umd.index.ts, packages/synapse-react-client/src/utils/analytics/SearchEventTypes.ts, packages/synapse-react-client/src/utils/analytics/sendAnalyticsEvent.ts, packages/synapse-react-client/src/utils/analytics/sendSearchEvent.ts, packages/synapse-react-client/src/utils/hooks/useGoogleAnalytics.ts
- Functions & types for custom analytics events related to search
=> SWC-7258 - Custom analytics events related to search

apps/portals/cancercomplexity/src/pages/CCKPSearchPage.tsx, apps/synapse-portal-framework/src/components/cancercomplexity/CancerComplexityHeader.tsx
Jira: https://sagebionetworks.jira.com/browse/PORTALS-3432?focusedCommentId=243102&page=com.atlassian.jira.plugin.system.issuetabpanels%3Acomment-tabpanel#comment-243102
Request to change "Student" to "Trainee".
=> CCKP Search Role Mapping Update

packages/synapse-react-client/src/components/Authentication/StandaloneLoginForm.tsx
Jira: https://sagebionetworks.jira.com/browse/SWC-7182
Fix for xs screen sizes.
Before:
After:
=> SWC-7182-V2: SageAccountWeb: LoginPage Xs Screen Update

apps/portals/nf/src/config/synapseConfigs/publications.ts, packages/synapse-react-client/src/components/CitationPopover/CitationPopover.tsx, packages/synapse-react-client/src/components/GenericCard/GenericCard.tsx
Jira: https://sagebionetworks.jira.com/browse/PORTALS-3502
=> PORTALS-3502: Add Configurable Default Citation Format Option

synapse-web-monorepo.code-workspace
Create a VS Code workspace file to suggest extensions, configure sensible default settings, and preconfigure test runner extensions. This should improve DX by allowing devs to interactively run and debug tests in the IDE.
=> Add code-workspace file

apps/portals/cancercomplexity/src/config/synapseConfigs/datasets.ts
Jira: https://sagebionetworks.jira.com/browse/PORTALS-3209
=> Change CCKP default citation for cite as button to nature

apps/portals/cancercomplexity/src/config/synapseConfigs/commonProps.ts, apps/portals/cancercomplexity/src/config/synapseConfigs/datasets.ts, apps/portals/cancercomplexity/src/config/synapseConfigs/education.ts, apps/portals/cancercomplexity/src/config/synapseConfigs/publications.ts, apps/portals/cancercomplexity/src/config/synapseConfigs/tools.ts
Relevant Jira: https://sagebionetworks.jira.com/browse/PORTALS-3209?focusedCommentId=244680&page=com.atlassian.jira.plugin.system.issuetabpanels%3Acomment-tabpanel#comment-244680
Context:
Publications - existing DOI column maps to cite as
Datasets - new DOI column to map to cite as
Tools - new DOI column to map to cite as
Educational resource - new COI column to map to cite as 
Education has DOI column but no DOI data currently so citation buttons will not show up on that page until data is available.
=> CCKP: include citation for publications, add citation boilerplate texts

apps/SageAccountWeb/src/LoginPage.tsx
- Fix bad URL for 2FA reset flow
=> PORTALS-3521

packages/synapse-react-client/src/components/EntityBadgeIcons/EntityBadgeIcons.tsx, packages/synapse-react-client/src/components/entity/metadata/AnnotationsTable.tsx, packages/synapse-types/src/FeatureFlags.ts
- Enable & remove JSONSCHEMA_VALIDATION_STATUS feature flag
=> SWC-7249 - remove flag for JSONSCHEMA_VALIDATION_STATUS feature

apps/synapse-portal-framework/src/components/csbc-home-page/HomePageLinks.tsx, apps/synapse-portal-framework/src/components/csbc-home-page/assets/SchoolIconCircle.tsx
=> PORTALS-3497: add educational resources item

apps/portals/standards/src/config/resources.ts, apps/portals/standards/src/pages/StandardsDetailsPage.tsx
There's a lot of repeated code here that I would be happy to refactor, but I know @Sigfried is working on this file as well, so I'll hold off on that for now
=> feat: add cards linking to related standards and training resources

apps/portals/standards/src/config/navbarConfig.ts, apps/portals/standards/src/pages/HomePage.tsx, apps/synapse-portal-framework/src/components/standards/StandardsContributeToTheRegistry.tsx
- navlinks on home page
- StandardsContributeToTheRegistry: text clipping at narrow screen sizes
=> standards: fix homepage issues

packages/synapse-react-client/src/components/doi/CreateOrUpdateDoiModal.test.tsx, packages/synapse-react-client/src/components/doi/CreateOrUpdateDoiModal.tsx, packages/synapse-react-client/src/synapse-queries/doi/useDOI.ts
- CreateOrUpdateDoiModal: Validate data against schema before submitting
- useCreateOrUpdateDOI: Use request body to invalidate cache
=> PORTALS-3407

apps/portals/cancercomplexity/src/config/synapseConfigs/commonProps.ts, packages/synapse-react-client/src/assets/mui_components/BioChemicalPhysical.tsx
Related Jira ticket: https://sagebionetworks.jira.com/browse/PORTALS-3385?focusedCommentId=246942&page=com.atlassian.jira.plugin.system.issuetabpanels%3Acomment-tabpanel#comment-246942
=> CCKP: Remove "Data Available" text in icon tooltip for explore pages

packages/synapse-client/package.json, packages/synapse-client/src/spec/openapispecification.json, packages/synapse-react-client/src/components/dataaccess/UserAccessRequestHistory/RouteConstants.ts, packages/synapse-react-client/src/components/dataaccess/UserAccessRequestHistory/UserAccessRequestHistoryPage.test.tsx, packages/synapse-react-client/src/components/dataaccess/UserAccessRequestHistory/UserAccessRequestHistoryPage.tsx, packages/synapse-react-client/src/components/dataaccess/UserAccessRequestHistory/UserAccessRequestHistoryTable.tsx, packages/synapse-react-client/src/synapse-queries/KeyFactory.ts, packages/synapse-react-client/src/synapse-queries/dataaccess/useDataAccessSubmission.ts, packages/synapse-react-client/src/testutils/ReactQueryMockUtils.ts
SWC-7232
- Update OpenAPI spec
- Add UserAccessRequestHistoryPage + table
=> SWC-7232 - UserAccessRequestHistoryPage + table

packages/synapse-react-client/src/components/dataaccess/SubmissionPage/SubmissionPage.test.tsx
https://github.com/Sage-Bionetworks/synapse-web-monorepo/pull/1779
Add in missing assertions in test
=> code review change from #1779

apps/portals/cancercomplexity/src/config/synapseConfigs/education.ts, apps/portals/cancercomplexity/src/config/synapseConfigs/grants.ts, apps/portals/cancercomplexity/src/config/synapseConfigs/people.ts, apps/portals/cancercomplexity/src/config/synapseConfigs/publications.ts, apps/portals/cancercomplexity/src/config/synapseConfigs/tools.ts
See https://sagebionetworks.jira.com/browse/PLFM-8897?focusedCommentId=247471
=> PORTALS-3534: updated boolean mode distances on CCKP

apps/portals/nf/src/config/synapseConfigs/datasets.ts
[PORTALS-3560](https://sagebionetworks.jira.com/browse/PORTALS-3560?linkSource=email)
[PORTALS-3560]: https://sagebionetworks.jira.com/browse/PORTALS-3560?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> PORTALS-3560: configure NF dataset cards with links to download cart

apps/portals/b2ai.standards/src/config/resources.ts
Fixes #276 problem with only 5 rows showing on Explore page
=> Stopped aliasing relevantOrgNames to organizations

packages/synapse-react-client/src/components/Authentication/TwoFactorBackupCodes.test.tsx, packages/synapse-react-client/src/components/Authentication/TwoFactorBackupCodes.tsx
https://sagebionetworks.jira.com/browse/PORTALS-3134
=> PORTALS-3134

packages/synapse-react-client/src/components/SynapseTable/TablePagination.test.tsx, packages/synapse-react-client/src/components/SynapseTable/TablePagination.tsx
PORTALS-3566
Add current query.limit to page size options to avoid empty Select box
=> PORTALS-3566

packages/synapse-react-client/src/components/dataaccess/UserAccessRequestHistory/UserAccessRequestHistoryPage.tsx, packages/synapse-react-client/src/components/dataaccess/UserAccessRequestHistory/UserAccessRequestHistoryPlace.stories.tsx, packages/synapse-react-client/src/components/dataaccess/UserAccessRequestHistory/UserAccessRequestHistoryPlace.tsx
- Fix copy
- Do not show breadcrumbs on index page
=> SWC-7232 - access request history issues found in validation

packages/synapse-react-client/package.json
=> SRC 3.4.17

apps/portals/ampals/src/index.tsx
=> Hide all content in AMP-ALS site

packages/synapse-react-client/src/components/Forum/DiscussionReply.tsx, packages/synapse-react-client/src/components/Forum/DiscussionThread.tsx, packages/synapse-react-client/src/components/UserCard/UserBadge.tsx
Jira: https://sagebionetworks.jira.com/browse/SWC-7315?focusedCommentId=248102&page=com.atlassian.jira.plugin.system.issuetabpanels%3Acomment-tabpanel#comment-248102
=> SWC-7315: Fix missing 'moderator' tag on Discussion Board

apps/portals/ampals/src/config/navbarConfig.ts, apps/portals/ampals/src/config/routesConfig.tsx, apps/portals/ampals/src/pages/HomePage.tsx, apps/synapse-portal-framework/src/components/ampals/AMPALSPublishingRequirements.tsx
Jira: https://sagebionetworks.jira.com/browse/PORTALS-3562
=> PORTALS-3562: AMP-ALS Update Publishing Requirements Slat

apps/portals/adknowledgeportal/src/config/doiRedirector.ts, apps/portals/adknowledgeportal/src/config/resources.ts, apps/portals/adknowledgeportal/src/config/synapseConfigs/studies.ts, packages/synapse-react-client/package.json, packages/synapse-react-client/src/components/ChallengeSubmission/ChallengeSubmission.stories.ts, packages/synapse-react-client/src/components/CitationPopover/CitationPopover.tsx, packages/synapse-react-client/src/components/CopyToClipboardIcon.tsx, packages/synapse-react-client/src/components/GenericCard/CardUtils.tsx, packages/synapse-react-client/src/components/GenericCard/GenericCard.tsx, packages/synapse-react-client/src/components/GenericCard/PortalDOI/PortalDOI.tsx, packages/synapse-react-client/src/components/GenericCard/PortalDOI/PortalDOI.vitest.tsx, packages/synapse-react-client/src/components/GenericCard/PortalDOI/PortalDOIUtils.ts, packages/synapse-react-client/src/components/GenericCard/PortalDOI/PortalDOIUtils.vitest.ts, packages/synapse-react-client/src/components/GenericCard/SynapseCardLabel.tsx, packages/synapse-react-client/src/components/GenericCard/TableRowGenericCard.test.tsx, packages/synapse-react-client/src/components/GenericCard/TableRowGenericCard.tsx, packages/synapse-react-client/src/components/GenericCard/TableRowGenericCard.vitest.tsx, packages/synapse-react-client/src/components/GenericCard/index.ts, packages/synapse-react-client/src/components/HeaderCard.tsx, packages/synapse-react-client/src/components/HeaderCard/HeaderCardV2.tsx, packages/synapse-react-client/src/components/row_renderers/Dataset.tsx, packages/synapse-react-client/src/synapse-queries/portal/usePortal.ts, packages/synapse-react-client/src/testutils/ReactQueryMockUtils.ts, pnpm-lock.yaml
When DOIs have been configured for a portal resource:
* Show the DOI if it exists on the portal card
* Show a button to create a DOI if the user has permission to do so.
| Case | Screenshot |
|--------|--------|
| Details page, viewer | ![image](https://github.com/user-attachments/assets/0b50678d-da09-4192-bccb-2eafb92a8ea1) |
| Details page, edit | ![image](https://github.com/user-attachments/assets/adb78bb9-722d-4a3e-952f-eef8b2392dab) |
| Details page, create | ![image](https://github.com/user-attachments/assets/adc04a5e-32b5-4929-87de-968ae906c3aa) | 
| Explore page, viewer | ![image](https://github.com/user-attachments/assets/40895b03-fbd4-403c-b7d0-01c7a5d58097) |
=> PORTALS-3549 - Add DOI to portal cards

packages/synapse-react-client/src/components/AccessRequirementList/AccessRequirementList.stories.tsx, packages/synapse-react-client/src/components/AccessRequirementList/ManagedACTAccessRequirementRequestFlow/ManagedACTAccessRequirementItem.tsx
SWC-7321
Fix whitespace issue with rejected reasons in data access request dialog
=> SWC-7321 - Fix whitespace issue

apps/synapse-portal-framework/src/components/PortalSearch/PortalFullTextSearchField.tsx, packages/synapse-react-client/src/components/widgets/facet-nav/SelectionCriteriaPills.tsx, packages/synapse-react-client/src/components/widgets/facet-nav/SelectionCriteriaPills.vitest.tsx
PORTALS-3590
Fix issue with SelectionCriteriaPills UI for TextMatchesQueryFilter
Do not allow submitting an empty search term in Portals Full Text Search
=> PORTALS-3590

apps/SageAccountWeb/src/App.scss, apps/SageAccountWeb/src/components/AccountSettings.tsx, apps/SageAccountWeb/src/style/_AccountSetting.scss
Jira: https://sagebionetworks.jira.com/browse/PORTALS-3433
=> PORTALS-3433: OneSage settings page: Background changes on small screens

apps/portals/b2ai.standards/src/config/synapseConfigs/data.ts
Fixes bridge2ai/b2ai-standards-registry/issues/301
=> Show download options on explore data

apps/portals/b2ai.standards/src/config/resources.ts, apps/portals/b2ai.standards/src/config/synapseConfigs/data.ts, apps/portals/b2ai.standards/src/pages/HomePage.tsx, apps/synapse-portal-framework/src/components/b2ai.standards/StandardsHeader.tsx
Use a FTS config for both the front-page search, as well as the search on the explore page
=> PORTALS-3608: use FTS config (boolean mode with distance of 50 per Orion)

apps/portals/b2ai.standards/src/config/routesConfig.tsx
=> PORTALS-3599: add alpha version alert

packages/synapse-react-client/src/components/CardContainer/CardContainer.tsx, packages/synapse-react-client/src/components/GenericCard/CroissantButton/CroissantButton.tsx, packages/synapse-react-client/src/components/GenericCard/CroissantButton/CroissantButton.vitest.tsx, packages/synapse-react-client/src/components/GenericCard/GenericCard.tsx, packages/synapse-react-client/src/components/GenericCard/GenericCardActionButton.tsx, packages/synapse-react-client/src/components/GenericCard/TableRowGenericCard.tsx, packages/synapse-react-client/src/components/HeaderCard.tsx, packages/synapse-react-client/src/style/components/_cards.scss, packages/synapse-react-client/src/synapse-queries/croissant/useGetCroissantUrl.ts, packages/synapse-react-client/src/synapse-queries/croissant/useGetCroissantUrl.vitest.ts, packages/synapse-react-client/src/synapse-queries/entity/useGetQueryResultBundle.ts
- Add croissant button to GenericCard/HeaderCard
- Update button style/position on GenericCard
- Display card buttons in HeaderCard
=> PORTALS-3556 - Croissant button on portals cards

apps/portals/nf/src/config/synapseConfigs/datasets.ts
Jira: https://sagebionetworks.jira.com/browse/PORTALS-3598
=> PORTALS-3598: Add "cite as" button to dataset cards on NF Portal

packages/synapse-react-client/src/components/GenericCard/CroissantButton/CroissantButton.tsx
=> PORTALS-3556

apps/portals/b2ai.standards/src/config/resources.ts
=> PORTALS-3610 Use snapshot for b2ai.standards DST_denormalized

packages/synapse-react-client/src/components/ChallengeSubmission/EvaluationQueueCurrentRoundInfo.tsx, packages/synapse-react-client/src/components/ChallengeSubmission/EvaluationQueueList.tsx, packages/synapse-react-client/src/components/Evaluation/EvaluationCard.tsx, packages/synapse-react-client/src/components/StorybookComponentWrapper.tsx, packages/synapse-react-client/src/synapse-queries/KeyFactory.ts, packages/synapse-react-client/src/synapse-queries/evaluation/useEvaluation.ts, packages/synapse-react-client/src/utils/challenge/evaluation/EvaluationUtils.ts, packages/synapse-react-client/src/utils/challenge/evaluation/EvaluationUtils.vitest.ts
PORTALS-3188
Add column to the Evaluation Queue picker with round info
=> PORTALS-3188 - Evaluation Round Info tooltip

apps/portals/adknowledgeportal/src/config/resources.ts, packages/synapse-react-client/src/components/SynapseTable/export/ExternalAnalysisPlatformsConstants.tsx, packages/synapse-react-client/src/synapse-queries/entity/useExportToTerra.ts
=> PORTALS-3512: add Terra instructions, and fix pfb export name

packages/synapse-react-client/src/components/CertificationQuiz/CertificationQuiz.integration.test.tsx, packages/synapse-react-client/src/components/ImageCardGridWithLinks/ImageCardGridWithLinks.test.tsx, packages/synapse-react-client/src/components/dataaccess/UserAccessRequestHistory/UserAccessRequestHistoryPage.test.tsx, packages/synapse-react-client/src/components/doi/CreateOrUpdateDoiModal.test.tsx, packages/synapse-react-client/src/components/download_list/FolderDownloadConfirmation.test.tsx, packages/synapse-react-client/src/testutils/ReactQueryMockUtils.test.ts, packages/synapse-react-client/src/testutils/ReactQueryMockUtils.ts, packages/synapse-react-client/src/utils/hooks/useUploadFileEntity/useCreateFolderPath.test.ts, packages/synapse-react-client/src/utils/hooks/useUploadFileEntity/useCreatePathsAndGetParentId.test.ts, packages/synapse-react-client/src/utils/hooks/useUploadFileEntity/useLinkFileEntityToURL.test.ts, packages/synapse-react-client/src/utils/hooks/useUploadFileEntity/usePrepareFileEntityUpload.test.ts, packages/synapse-react-client/src/utils/hooks/useUploadFileEntity/useUploadFileEntities.test.ts
Write new react-query mock implementations with improved ergonomics for interactive tests. These new mocks can be dynamically modified mid-test for more realistic and convenient mock interactions.
=> Improve mocks for react-query wrappers

apps/portals/eliteportal/src/config/synapseConfigs/dataTable.ts, apps/portals/eliteportal/src/pages/StudyDetailsPage/StudyDataTab.tsx
Update configuration for file listing on study data page in the ELITE portal
=> PORTALS-3632

packages/synapse-react-client/src/components/SynapseTable/SearchV2.tsx, packages/synapse-react-client/src/components/ToastMessage/ToastMessage.tsx
nodeRef must be passed with child to animate using CSSTransition
=> PORTALS-3351 - Fix React 19 issue with react-transition-group

packages/synapse-react-client/src/components/SynapseTable/export/ExternalAnalysisPlatformsConstants.tsx
from https://sagebionetworks.slack.com/archives/C08MYB5CJEN/p1749501351715859?thread_ts=1749491604.705309&cid=C08MYB5CJEN
=> PORTALS-3640: update Terra platform description text

packages/synapse-react-client/src/components/ChallengeDataDownload/ChallengeDataDownload.tsx, packages/synapse-react-client/src/components/EntityFinder/EntityFinder.test.tsx, packages/synapse-react-client/src/components/EntityFinder/EntityFinder.tsx, packages/synapse-react-client/src/components/EntityFinder/EntityFinderModal.tsx, packages/synapse-react-client/src/components/EntityFinder/useEntitySelection.test.ts, packages/synapse-react-client/src/components/EntityFinder/useEntitySelection.ts, packages/synapse-react-client/src/components/SynapseTable/datasets/DatasetEditorUtils.ts, packages/synapse-react-client/src/components/SynapseTable/datasets/DatasetItemsEditor.stories.ts, packages/synapse-react-client/src/components/SynapseTable/datasets/DatasetItemsEditor.tsx, packages/synapse-react-client/src/utils/functions/ArrayUtils.test.ts, packages/synapse-react-client/src/utils/functions/ArrayUtils.ts
=> SWC-7003 - Pre-select Dataset Items in Entity Finder

packages/synapse-react-client/src/components/AccessRequirementList/AccessRequirementList.tsx, packages/synapse-react-client/src/components/AccessRequirementList/AccessRequirementListItem.tsx, packages/synapse-react-client/src/components/AccessRequirementList/ManagedACTAccessRequirementRequestFlow/ManagedACTAccessRequirementItem.test.tsx, packages/synapse-react-client/src/components/AccessRequirementList/ManagedACTAccessRequirementRequestFlow/ManagedACTAccessRequirementItem.tsx, packages/synapse-react-client/src/components/AccessRequirementList/ManagedACTAccessRequirementRequestFlow/ManagedACTAccessRequirementItemView.stories.tsx, packages/synapse-react-client/src/components/AccessRequirementList/ManagedACTAccessRequirementRequestFlow/ManagedACTAccessRequirementItemView.tsx, packages/synapse-react-client/src/utils/functions/StringUtils.test.ts, packages/synapse-react-client/src/utils/functions/StringUtils.ts
- Add UI for case where user is exempt from fulfilling an access requirement in the context of a particular object
- Enhance UI for case where access was revoked to indicate an expiration date
- Decouple fetching logic from view logic in ManagedACTAccessRequirementItem (adding ManagedACTAccessRequirementItemView component)
- Add stories for ManagedACTAccessRequirementItemView
- Fix null value issue in `normalizeNumericId`
=> SWC-6748 - Support AR Exempt state in submission UI

packages/synapse-react-client/src/components/CopyToClipboardIcon.tsx
Jira: https://sagebionetworks.jira.com/browse/PORTALS-3643
=> PORTALS-3634: Toast shown when copying citation has text that is too large

.github/actions/pnpm-setup-action/action.yml, apps/portals/b2ai.standards/src/components/ChallengesCardDeck.tsx, apps/portals/b2ai.standards/src/components/IsMatureIconMap.tsx, apps/portals/b2ai.standards/src/config/columnAliases.ts, apps/portals/b2ai.standards/src/config/resources.ts, apps/portals/b2ai.standards/src/config/synapseConfigs/data.ts, apps/portals/b2ai.standards/src/pages/GrandChallengeDataSetPage.tsx, apps/portals/b2ai.standards/src/pages/HomePage.tsx, apps/portals/b2ai.standards/src/pages/StandardsDetailsPage.tsx, package.json
- Added category to std details page header
- Changed Is Mature to Maturity
- Set pnpm version in package.json
=> B2AI issues 340 and 353

apps/portals/nf/src/config/routeConstants.ts
Fix NF routes changed unintentionally in PORTALS-3587
=> PORTALS-3676

pnpm-lock.yaml
=> PORTALS-3663

apps/synapse-portal-framework/src/style/components/_DetailsPage.scss, packages/synapse-react-client/src/style/components/_entity-metadata.scss, packages/synapse-react-client/src/style/components/_governance-dashboard.scss
Fix a few regressions introduced in #1921
=> SWC-7406 - Fix style precedence issue

packages/synapse-react-client/src/components/entity/metadata/AnnotationsTable.test.tsx, packages/synapse-react-client/src/utils/jsonschema/SchemaAnnotationUtils.test.ts, packages/synapse-react-client/src/utils/jsonschema/SchemaAnnotationUtils.ts
=> SWC-7410 - Handle error thrown by `registerSchema`

apps/portals/ampals/src/pages/resources/ForContributors.tsx
Jira: https://sagebionetworks.jira.com/browse/PORTALS-3748?assignee=712020%3Aa7fbbeb0-d7a6-443a-9dd4-246363ff09dd
=> PORTALS-3748: Please update ALS Portal Page 

apps/portals/b2ai.standards/src/config/resources.ts
This is to get rid of datasets that were earlier moved to DataSet
=> Updating DST_denormalized version to 67

packages/synapse-react-client/src/components/Goals/Goals.Desktop.tsx, packages/synapse-react-client/src/components/GoalsV2/GoalsV2.Desktop.tsx, packages/synapse-react-client/src/components/GoalsV3/GoalsV3.Desktop.tsx
Explicitly specify the target as _self in Goals component (all versions)
=> PORTALS-3773

packages/synapse-react-client/src/components/AcknowledgementsPage/AcknowledgementsDialog.tsx, packages/synapse-react-client/src/components/AcknowledgementsPage/AcknowledgementsPage.stories.ts, packages/synapse-react-client/src/components/AcknowledgementsPage/AcknowledgementsPage.tsx, packages/synapse-react-client/src/components/GoalsV2/GoalsV2.Desktop.test.tsx, packages/synapse-react-client/src/components/Markdown/MarkdownCollapse.tsx
=> PORTALS-3778, PORTALS-3763

apps/portals/cancercomplexity/src/pages/ToolsDetailsPage/ToolsDetailsPage.tsx, packages/synapse-react-client/src/components/HeaderCard.tsx, packages/synapse-types/src/FeatureFlags.ts
Jira: https://sagebionetworks.jira.com/browse/PORTALS-3741
=> PORTALS-3741: Move the CCKP toolkit out of experimental mode & onto Staging

apps/portals/adknowledgeportal/src/config/resources.ts
Update resources.ts to version 75 for data release 25.8
=> Update resources.ts to version 75 for data release 25.8

packages/synapse-react-client/package.json, packages/synapse-react-client/src/components/DataGrid/DataGridTypes.ts, packages/synapse-react-client/src/components/DataGrid/SynapseGrid.tsx, packages/synapse-react-client/src/components/DataGrid/utils/applyModelChange.test.ts, packages/synapse-react-client/src/components/DataGrid/utils/applyModelChange.ts, packages/synapse-react-client/src/components/DataGrid/utils/computeReplicaSelectionModel.test.ts, packages/synapse-react-client/src/components/DataGrid/utils/computeReplicaSelectionModel.ts, packages/synapse-react-client/src/components/DataGrid/utils/createTestModel.ts, pnpm-lock.yaml
Compute the user's selection and add it to the CRDT
=> SWC-7471 - Row selection in CRDT

packages/synapse-client/package.json, packages/synapse-client/src/SynapseClient.ts, packages/synapse-react-client/src/components/Forum/ForumPage.test.tsx, packages/synapse-react-client/src/components/Forum/ForumTable.tsx, packages/synapse-react-client/src/components/OAuthClientManagement/OAuthManagement.test.tsx, packages/synapse-react-client/src/components/OAuthClientManagement/OAuthManagement.tsx, packages/synapse-react-client/src/components/Webhook/WebhookDashboard.test.tsx, packages/synapse-react-client/src/components/Webhook/WebhookDashboard.tsx, packages/synapse-react-client/src/components/dataaccess/AccessApprovalsTable.tsx, packages/synapse-react-client/src/components/dataaccess/AccessRequestSubmissionTable.tsx, packages/synapse-react-client/src/components/dataaccess/AccessRequirementTable.tsx, packages/synapse-react-client/src/components/dataaccess/UseAccessRequirementTable.tsx, packages/synapse-react-client/src/components/dataaccess/UserAccessRequestHistory/UserAccessRequestHistoryPage.test.tsx, packages/synapse-react-client/src/components/dataaccess/UserAccessRequestHistory/UserAccessRequestHistoryTable.tsx, packages/synapse-react-client/src/components/layout/InfiniteTableLayout.tsx
- Expose curationTaskServicesClient in SynapseClient
- Refactor to create shared InfiniteTableLayout and use in components that all use a similar layout.
=> SWC-7468 - prep

apps/portals/classic/src/config/navbarConfig.ts, apps/portals/classic/src/config/resources.ts, apps/portals/classic/src/pages/HomePage.tsx
=> CLASSIC-6, CLASSIC-9, CLASSIC-12

apps/portals/classic/src/config/scripts/exportS3ProductionBucketName.sh, apps/portals/classic/src/config/scripts/exportS3StagingBucketName.sh
This PR sets up the actual values for the buckets and distributions.
=> IT-4635: Update destination bucket and distributionID for classicportal

apps/portals/b2ai.standards/src/components/D4D.tsx, apps/portals/b2ai.standards/src/pages/OrganizationDetailsPage.tsx
- @nickgros's comments here: https://github.com/Sage-Bionetworks/synapse-web-monorepo/pull/2183
=> Addressed Nick's comments
