Sage-Bionetworks/synapse-web-monorepo

apps/portals/run.sh, packages/synapse-react-client/tsconfig.build.json
- synapse-react-client: Build tsconfig `incremental: true` broke output
- portals: in build machine script, use Nx to guarantee dependencies are built
=> Fix builds

packages/synapse-react-client/jest.config.js, packages/synapse-react-client/test/lib/containers/entity/page/title_bar/EntityPageTitleBar.test.tsx
- Remove `failOnConsole` from EntityPageTitleBar test suite that is likely failing due to resources bleeding over from previous test suite.
- Include failure messages in the test report.
=> Improve test stability

packages/synapse-react-client/src/lib/containers/entity/page/CreatedByModifiedBy.tsx, packages/synapse-react-client/test/lib/containers/SynapseTable.test.tsx
We use the MUI Breadcrumbs component to render/style this content, which internally uses a flex container to store each item, so we apply `justifyContent: 'center'` to the internal `ol`.
=> SWC-6382 - Center the content of the created/modified on/by component.

packages/synapse-react-client/src/lib/style/components/_expandable_table_data.scss
No spaces in this WWWWWWW... cell
=> SWC-6375 - Add `overflow-wrap: break-word` to the expandable table data expanded state

packages/synapse-react-client/package.json
In macOS, copyfiles does not properly handle the glob unless the string is surrounded in quotes. The effect was that files deeper than 2 levels were not copied. This issue is not present on Linux, so builds published to NPM via GitHub actions were not affected.
From [copyfiles README](https://github.com/calvinmetcalf/copyfiles#readme):
> if your terminal doesn't support globstars then you can quote them
```
copyfiles -f ./foo/**/*.txt out
```
> does not work by default on a mac
> but
```
copyfiles -f "./foo/**/*.txt" out
```
> does.
=> Fix issue where copyfiles glob was not respected in macOS.

apps/portals/src/AppInitializer.tsx, apps/portals/src/Navbar.tsx, packages/synapse-react-client/demo/containers/App.tsx, packages/synapse-react-client/src/lib/containers/StorybookComponentWrapper.tsx, packages/synapse-react-client/src/lib/containers/SynapseNavDrawer.tsx, packages/synapse-react-client/src/lib/containers/auth/Login.tsx, packages/synapse-react-client/src/lib/containers/auth/Logout.tsx, packages/synapse-react-client/src/lib/utils/SynapseClient.ts, packages/synapse-react-client/stories/LoginPage.stories.ts
Remove sessionCallback from SynapseClient functions. If a callback is needed, it can be attached to the promise with `.then`/`await`.
=> SWC-6390: BREAKING CHANGE: remove sessionCallback from SynapseClient

apps/portals/src/configurations/elportal/scripts/exportS3ProductionBucketName.sh, apps/portals/src/configurations/elportal/scripts/exportS3StagingBucketName.sh
This PR sets up the names of the buckets used to deploy https://eliteportal.synapse.org .
=> IT-2660: Update S3 bucket names

packages/synapse-react-client/package.json
* Fix issue where copyfiles glob was not respected in macOS. by @nickgros in https://github.com/Sage-Bionetworks/synapse-web-monorepo/pull/27
* SWC-6390: BREAKING CHANGE: remove sessionCallback from SynapseClient by @nickgros in https://github.com/Sage-Bionetworks/synapse-web-monorepo/pull/30
* SWC-6390: Changes to support 2FA Login by @nickgros in https://github.com/Sage-Bionetworks/synapse-web-monorepo/pull/31
* SWC-6390: add useLogin hook by @nickgros in https://github.com/Sage-Bionetworks/synapse-web-monorepo/pull/35
* SWC-6390 - basic 2FA login support by @nickgros in https://github.com/Sage-Bionetworks/synapse-web-monorepo/pull/37
* SWC-6399: Inability to get or clear the session cookie should not cause the web… by @jay-hodgson in …
=> Release synapse-react-client v3.1.25

packages/synapse-react-client/package.json
* PORTALS-2527: support other links that require an intermediate screen by @jay-hodgson in https://github.com/Sage-Bionetworks/synapse-web-monorepo/pull/57
* SWC-6394 - Add 2FA recovery code generation by @nickgros in https://github.com/Sage-Bionetworks/synapse-web-monorepo/pull/59
* SWC-6407 - Fix copy by @nickgros in https://github.com/Sage-Bionetworks/synapse-web-monorepo/pull/61
* SWC-5997 - Allow non-ACT reviewers to view User Submission History by @nickgros in https://github.com/Sage-Bionetworks/synapse-web-monorepo/pull/60
* SWC-6365 by @jay-hodgson in https://github.com/Sage-Bionetworks/synapse-web-monorepo/pull/63
* SWC-6393 - Add 2FA panel for settings page by @nickgros in https://github.com/Sage-Bionetworks/synapse-web-monorepo/pull/62
* PORTALS-2579: update BarPlot (used by …
=> Release synapse-react-client v3.1.28

apps/portals/craco.config.js, apps/portals/src/AppInitializer.tsx, apps/portals/src/Navbar.tsx, apps/portals/src/_Navbar.scss, apps/portals/src/utils.ts, packages/synapse-react-client/package.json, packages/synapse-react-client/src/lib/containers/auth/TOTPForm.tsx, packages/synapse-react-client/src/lib/utils/hooks/useDetectSSOCode.ts, packages/synapse-react-client/test/lib/utils/hooks/useDetectSSOCode.test.ts, pnpm-lock.yaml
Changes I've made in synapse-oauth-signin are dependent upon the changes to useDetectSSOCode, which is how this work is related to PORTALS-2580
-----
- Refactor useDetectSSOCode so SSO redirect logic can be captured in-app
- Upgrade mui-one-time-password-input to 1.1.0 and use new `autoFocus`
- Fix dialog UI in portals
-----
Current portals login dialog needs more padding: 
after changes:
=> PORTALS-2580 - refactor for synapse-oauth-signin + misc fixes

apps/SageAccountWeb/src/App.scss, apps/SageAccountWeb/src/LoginPage.tsx, apps/SageAccountWeb/src/components/AccountCreatedPage.tsx, apps/SageAccountWeb/src/components/CurrentAffiliationPage.tsx, apps/SageAccountWeb/src/components/ProfileValidation/ORCiDButton.tsx, apps/SageAccountWeb/src/components/ProfileValidation/ProfileFieldsEditor.tsx, apps/SageAccountWeb/src/components/ProfileValidation/ProfileValidation.tsx, apps/SageAccountWeb/src/components/RegisterAccount1.tsx, apps/SageAccountWeb/src/components/SageResourcesPage.tsx, apps/SageAccountWeb/src/components/StyledComponents.ts, apps/SageAccountWeb/src/style/_Register.scss, apps/SageAccountWeb/src/style/_SourceApp.scss
- Use consistent box-shadow and border-radius for content container
- Align left panel buttons and right panel text for different logos
- Standardize logo height
- Adjust right panel text padding
- "Tertiary" link should have 20px space from button above it
- Decrease padding between logo and button in left panel to match design
- Size logos in Account Settings page
- Fix ORCID button logo
Examples of changes: 
Change | main | PORTALS-2560
:--------:|:--------:|:--------:
_/_ - logo size | ![main_logo_MTB](https://user-images.githubusercontent.com/26949006/227591064-b5d5ab0e-d38b-44fb-84cf-31693c37b46f.png) ![main_logo_SAGE](https://user-images.githubusercontent.com/26949006/227591695-00195528-df97-486d-b2f9-7214ff022d5d.png) | ![feature_logo_MTB](https://user-images.githubusercontent.com/ …
=> PORTALS-2560: polish items for login and registration workflow steps

apps/SageAccountWeb/src/AppInitializer.tsx, apps/SageAccountWeb/src/LoginPage.tsx, apps/SageAccountWeb/src/TwoFactorAuthSSOContext.tsx, apps/SageAccountWeb/src/components/ProfileValidation/ORCiDButton.tsx, apps/SageAccountWeb/src/components/RegisterAccount1.tsx, apps/portals/src/AppInitializer.tsx, apps/portals/src/Navbar.tsx, apps/portals/src/utils.ts, apps/synapse-oauth-signin/src/App.test.tsx, apps/synapse-oauth-signin/src/AppInitializer.tsx, apps/synapse-oauth-signin/src/OAuth2Form.tsx, packages/synapse-react-client/src/lib/utils/AppUtils.ts
- Add SSO + 2FA handling to SageAccountWeb
- Refactor SSO redirect utils from portals to synapse-react-client
- Use SSO redirect utils in all 3 apps
=> PORTALS-2581 - Google SSO + Synapse 2FA in SageAccountWeb

apps/SageAccountWeb/src/components/LeftRightPanel.tsx, apps/SageAccountWeb/src/components/RegisterAccount2.tsx, apps/SageAccountWeb/src/components/ResetPassword.tsx, apps/SageAccountWeb/src/style/_AccountCreatedPage.scss
Update reset password component to match design:
- Style as left-right panel
- Disable button when required values not entered in form
- Include back button when requesting password reset
. | main | feature
:----:|:----:|:----:
request reset | ![main_resetpassword_request](https://user-images.githubusercontent.com/26949006/228066944-b6a07825-0609-4e98-9e5c-c851fef9de64.png) | ![feature_resetpassword_request](https://user-images.githubusercontent.com/26949006/228066932-8f2d931d-43cf-48a2-b6eb-a4a9b1d2ec73.png)
change password | ![main_resetpassword_change](https://user-images.githubusercontent.com/26949006/228066941-a20c97de-44a6-44fe-93df-c91ec8a7e7f1.png) | ![feature_resetpassword_change](https://user-images.githubusercontent.com/26949006/228066928-4119e49d-2fd7-495b-b3d6-df7bea1e74f9.png …
=> PORTALS-2608: update reset password page design

apps/SageAccountWeb/src/components/ProfileValidation/Attestation.tsx, apps/portals/README.md, apps/portals/package.json, packages/synapse-react-client/src/lib/containers/FileUpload.tsx, packages/synapse-react-client/src/lib/containers/access_requirement_list/managedACTAccess/RequestDataAccessStep2.tsx, packages/synapse-react-client/stories/FileUpload.stories.tsx
page | main | feature
:----:|:----:|:----:
sage account web attestation | ![main_authenticated_validate](https://user-images.githubusercontent.com/26949006/229597587-ad2666fa-a85a-4727-9374-d853275fd93c.png) | ![feature_authenticated_validate](https://user-images.githubusercontent.com/26949006/229597579-a276c92d-9c9c-4994-909b-8126284a69ee.png)
access requirements list | <img width="593" alt="main_storybook_accessrequirementlist" src="https://user-images.githubusercontent.com/26949006/229597594-d05392f5-4fc5-4137-916d-b5c560b89538.png"> | <img width="590" alt="feature_storybook_accessrequirementlist" src="https://user-images.githubusercontent.com/26949006/229597585-7f3d31cc-6f73-4956-9d5b-3dc7dfa80eb8.png">
Other Changes
- Refactor FileUpload to use MUI Button rather than bootstrap button …
=> PORTALS-2567: Polish Items for Verification Step 4 (Upload)

packages/synapse-react-client/src/lib/style/components/_terms-and-conditions.scss
page | main | feature
signTermsOfUse | ![main_authenticated_signTermsOfUse](https://user-images.githubusercontent.com/26949006/229911314-90fe7086-0fde-43bb-b131-a5ca3e803e57.png) | ![feature_authenticated_signTermsOfUse](https://user-images.githubusercontent.com/26949006/229911290-e7633f1f-136f-4c56-ac57-1f5400f8f1d8.png)
validate | ![main_authenticated_validate](https://user-images.githubusercontent.com/26949006/229911329-baa09cb4-1259-400e-83b7-701597c14af3.png) | ![feature_authenticated_validate](https://user-images.githubusercontent.com/26949006/229911303-a7780485-5cce-42d9-99a9-1750667f921e.png)
=> PORTALS-2617: remove background fill color in sage pledge icons

packages/synapse-react-client/src/lib/containers/SynapseNavDrawer.tsx, packages/synapse-react-client/src/lib/style/components/_synapse-nav-drawer.scss, packages/synapse-react-client/test/lib/containers/SynapseNavDrawer.test.tsx
synapse-react-client:
- Release AR Reviewer dashboard from experimental mode
- SynapseNavDrawer: Replace ListItem w/ deprecated button prop with ListItemButton
- SynapseNavDrawer: Add/refine tests for checking which buttons are visible
=> SWC-6418 - Release AR Reviewer dashboard from experimental mode

packages/synapse-react-client/src/lib/containers/widgets/facet-nav/FacetNav.tsx
Before: 
https://user-images.githubusercontent.com/26949006/231316716-582fc1a0-6bfc-48ec-90df-561c0d32134a.mov
After: 
https://user-images.githubusercontent.com/26949006/231316722-27556467-d54f-4428-8c77-4210d84fd157.mov
=> PORTALS-2604: button for 'view all charts' should live underneath the 'search field dropdown'

.github/workflows/deploy-sage-account-web.yml
- move 'install-dependencies' step name back down to its own line
=> Re-add accidentally dropped line break

packages/synapse-react-client/src/lib/containers/GenericCard.tsx, packages/synapse-react-client/src/lib/containers/synapse_table_functions/SynapseTableCell.tsx
Use a paragraph in a number of renderers to enable the expand behavior in the context of a Table Cell (but does not impact rendering in a Card context):
=> PORTALS-2626

apps/portals/package.json, apps/portals/src/SynapseComponent.tsx, apps/portals/src/configurations/nf/routesConfig.ts, apps/portals/src/types/portal-config.ts, packages/synapse-react-client/src/lib/containers/CardContainerLogic.tsx, packages/synapse-react-client/src/lib/containers/useImmutableTableQuery.ts, packages/synapse-react-client/test/lib/utils/hooks/useImmutableTableQuery.test.tsx, pnpm-lock.yaml
See PORTALS-2621
Fix a case where CardContainerLogic did not update when the `searchParams` prop updated. The `searchParams` prop is used to create the `initQueryRequest` object, which is passed into `useImmutableTableQuery`.
Before this change, `useImmutableTableQuery` was not configured to update the query state when the `initQueryRequest` argument changed.
=> PORTALS-2621 - Fix NF stale data issue by resetting table query on prop change

packages/synapse-react-client/src/lib/containers/synapse_table_functions/SynapseTableCell.tsx
=> PORTALS-2507: all '-' within cells should be left aligned just like the content

apps/portals/src/_Core.scss, apps/portals/src/portal-components/RouteControlWrapper.tsx
page | main | feature
:----:|:----:|:----:
Explore Programs | ![main_Explore_Programs](https://user-images.githubusercontent.com/26949006/232620501-90565bdf-c1e8-4d65-91fe-74f57894261a.png) | ![feature_Explore_Programs](https://user-images.githubusercontent.com/26949006/232620488-92b6f869-f73b-48cb-b0f7-9e042bd04e2e.png)
Explore Data | ![main_Explore_Data](https://user-images.githubusercontent.com/26949006/232620494-3cac0fbe-f649-44b8-a253-edd34d4c1797.png) | ![feature_Explore_Data](https://user-images.githubusercontent.com/26949006/232620483-95354c89-0c0b-40d3-8701-947409198510.png)
=> PORTALS-2508: adjust margin to prevent tables from running off edge of screens

apps/SageAccountWeb/src/LoginPage.tsx, apps/SageAccountWeb/src/components/AccountSettings.tsx, apps/SageAccountWeb/src/components/StyledComponents.ts, apps/portals/src/Navbar.tsx, apps/synapse-oauth-signin/src/OAuth2Form.tsx, packages/synapse-react-client/src/lib/components/styled/StyledFormControl.tsx, packages/synapse-react-client/src/lib/containers/TextField.tsx, packages/synapse-react-client/src/lib/containers/auth/StandaloneLoginForm.tsx, packages/synapse-react-client/src/lib/containers/auth/TOTPForm.tsx, packages/synapse-react-client/src/lib/utils/theme/DefaultTheme.ts
In SWC-6412 I am reworking the AccessRequirementList component and submission flow. I'm using MUI where possible, so some theme updates were necessary.
- Move StyledFormControl to SRC
- Apply most StyledFormControl > InputBase styles to all InputBase components in the theme
- Use StyledFormControl in custom TextField component
- Apply 2px padding to modal content to ensure input borders and box shadow are shown; use `border-image` to hide first and last 2px of modal border
For input fields, SageAccountWeb uses StyledFormControl with an inner MUI TextField. This is flawed because TextField actually contains its own FormControl component. The input fields look fine for now (no visual change), but we should aim to fix this in the future.
Modal changes
|Before|After|
|---|---|
| <img …
=> SWC-6412 - Input, Dialog component theme changes

packages/synapse-react-client/package.json, packages/synapse-react-client/src/lib/containers/provenance/ProvenanceGraph.tsx, packages/synapse-react-client/src/lib/containers/provenance/ProvenanceGraphUtils.ts, packages/synapse-react-client/src/lib/containers/provenance/ProvenanceUtils.tsx, pnpm-lock.yaml
After the upgrade, I could not see any differences apart from these:
- Mouse cursor indicates panning, when possible
- Can pan when the cursor is over nodes (links in nodes still work)
Motivation was intermittent test failures reported here: https://github.com/wbkd/react-flow/issues/2108
I followed this migration guide, which also has more information about changes in v11 https://reactflow.dev/docs/guides/migrate-to-v11/
=> Upgrade react-flow-renderer to reactflow v11 to resolve intermittent test failures

packages/synapse-react-client/src/lib/containers/ConfirmationDialog.tsx, packages/synapse-react-client/src/lib/containers/CreateProjectModal.tsx, packages/synapse-react-client/stories/CreateProjectModal.stories.tsx, packages/synapse-react-client/test/lib/containers/CreateProjectModal.test.tsx
=> PORTALS-2624: remove bootstrap-4-backport class from CreateProjectModal

.github/actions/pnpm-setup-action/action.yml, .github/workflows/build-docs.yml, .github/workflows/build-test.yml, .github/workflows/deploy-sage-account-web.yml, .github/workflows/npmpublish.yml, .github/workflows/publish-docs.yml, packages/synapse-react-client/README.md
- Separate repo setup/dep install into local reusable action
- Split build/test/lint into separate parallel steps, making the entire process slightly faster and easier to see which step failed.
synapse-react-client:
- Remove react-scripts specific sections in README.md
=> CI improvements - Reuse project setup action and run build/test/lint in parallel

packages/synapse-react-client/src/lib/components/styled/LightTooltip.tsx, packages/synapse-react-client/src/lib/containers/ExperimentalMode.tsx, packages/synapse-react-client/src/lib/style/components/_experimental-mode.scss, packages/synapse-react-client/stories/ExperimentalMode.stories.tsx
Before: 
https://user-images.githubusercontent.com/26949006/235269863-cc1947be-ed55-4d85-aca4-f4f040d67eae.mov
After: 
https://user-images.githubusercontent.com/26949006/235743088-66cad998-735c-4d41-8f48-235383c77d9b.mov
=> PORTALS-2624: remove bootstrap-4-backport from ExperimentalMode

apps/portals/src/Navbar.tsx, apps/portals/src/configurations/arkportal/style/_style_overrides.scss, apps/portals/src/portal-components/nf/BrowseToolsPage.tsx, apps/portals/src/portal-components/nf/style/_BrowseToolsPage.scss, packages/synapse-react-client/demo/containers/playground/ButtonDemo.tsx, packages/synapse-react-client/src/lib/components/styled/WideButton.tsx, packages/synapse-react-client/src/lib/containers/CardContainer.tsx, packages/synapse-react-client/src/lib/containers/home_page/goals/Goals.Desktop.tsx, packages/synapse-react-client/src/lib/containers/home_page/goals/Goals.Mobile.tsx, packages/synapse-react-client/src/lib/containers/markdown/widget/MarkdownButton.tsx, packages/synapse-react-client/src/lib/containers/row_renderers/Funder.tsx, packages/synapse-react-client/src/lib/containers/synapse_form_wrapper/SynapseFormSubmissionsGrid.tsx, packages/synapse-react-client/src/lib/containers/widgets/facet-nav/FacetNav.tsx, packages/synapse-react-client/src/lib/style/bootstrap4_backports/_base-import.scss, packages/synapse-react-client/src/lib/style/components/_cards.scss, packages/synapse-react-client/src/lib/style/components/_goals.scss, packages/synapse-react-client/src/lib/style/components/facet_nav/_facet-nav.scss, packages/synapse-react-client/src/lib/style/components/synapse_form_wrapper/_synapse-form-wrapper.scss, packages/synapse-react-client/src/lib/utils/theme/palette/Palettes.ts, packages/synapse-react-client/stories/Button.stories.tsx, packages/synapse-react-client/stories/CardContainerLogic.stories.ts, packages/synapse-react-client/stories/SynapseFormSubmissionsGrid.stories.tsx, packages/synapse-react-client/test/lib/containers/markdown/__snapshots__/MarkdownSynapse.integration.test.tsx.snap, packages/synapse-react-client/test/lib/containers/synapse_form_wrapper/SynapseFormSubmissionsGrid.integration.test.tsx
Updates:
- Convert bootstrap `btn-wide` buttons to MUI styled WideButton components
- Remove `btn-wide` class
- Add stories for `Funder` and `SynapseFormSubmissionsGrid`
- Convert bootstrap components to MUI in `SynapseFormSubmissionsGrid`
- Convert bootstrap buttons to MUI in Portals `Navbar`
=> PORTALS-2624: convert bootstrap btn-wide buttons to styled MUI buttons

apps/portals/src/configurations/elportal/routesConfig.ts, packages/synapse-react-client/src/lib/utils/theme/palette/Palettes.ts
=> PORTALS-2656: fix secondary color contrast color

packages/synapse-react-client/src/lib/containers/ModalDownload.FormSchema.ts, packages/synapse-react-client/src/lib/containers/ModalDownload.tsx, packages/synapse-react-client/stories/ModalDownload.stories.ts
step | main | feature
1 | <img width="677" alt="main_ModalDownload_1" src="https://github.com/Sage-Bionetworks/synapse-web-monorepo/assets/26949006/670d087d-58a2-410d-bd16-29b3037e6d5c"> | <img width="645" alt="feature_ModalDownload_1" src="https://github.com/Sage-Bionetworks/synapse-web-monorepo/assets/26949006/bb66aef8-95e3-47d9-8101-e4015e2fddca">
2 | <img width="722" alt="main_ModalDownload_2" src="https://github.com/Sage-Bionetworks/synapse-web-monorepo/assets/26949006/f7497c36-fba8-4960-9625-7eaf4b92eca6"> | <img width="648" alt="feature_ModalDownload_2" src="https://github.com/Sage-Bionetworks/synapse-web-monorepo/assets/26949006/d16f9152-d856-4ef8-8c8d-8d735798b2ad">
=> PORTALS-2624: refactor ModalDownload to use MUI components

packages/synapse-react-client/src/lib/containers/AddToDownloadListV2.tsx, packages/synapse-react-client/src/lib/containers/EntityLink.tsx, packages/synapse-react-client/src/lib/containers/table/SynapseTable.tsx, packages/synapse-react-client/src/lib/style/base/_core.scss, packages/synapse-react-client/src/lib/template_style/_theme.scss
=> PORTALS-2624: refactor SynapseTable modal view to use MUI components

apps/SageAccountWeb/package.json, apps/portals/package.json, apps/synapse-oauth-signin/package.json, package.json, packages/synapse-react-client/package.json, pnpm-lock.yaml
- In SRC we're using Plotly.js v2, so bump that to the most recent v2 release in all packages
- Fix plotly types packages to avoid conflict
- Add test:ci so the Nx parallel runner doesn't enter interactive mode locally, and coverage will be collected in CI
=> Add test:ci, align plotly versions

apps/SageAccountWeb/src/components/ProfileAvatar.tsx, apps/SageAccountWeb/src/style/_ProfileAvatar.scss, apps/SageAccountWeb/src/style/theme.ts, packages/synapse-react-client/src/lib/containers/ConfirmationDialog.tsx, packages/synapse-react-client/src/lib/containers/discussion_forum/SubscribersModal.tsx
component | main | feature
SubscribersModal | <img width="1628" alt="main_SubscribersModal" src="https://github.com/Sage-Bionetworks/synapse-web-monorepo/assets/26949006/1275036f-f6cb-4df9-b7a8-7ea19208252e"> | <img width="1629" alt="feature_SubscribersModal" src="https://github.com/Sage-Bionetworks/synapse-web-monorepo/assets/26949006/a6bbe770-f499-4b85-8391-5427a0c23dc2">
ProfileAvatar | <img width="1352" alt="main_ProfileAvatar" src="https://github.com/Sage-Bionetworks/synapse-web-monorepo/assets/26949006/a261d252-8457-4d23-aebe-dc5497278c01"> | <img width="1348" alt="feature_ProfileAvatar" src="https://github.com/Sage-Bionetworks/synapse-web-monorepo/assets/26949006/5cf90b8b-73d0-4fa4-bf7f-c6ae992492a0">
=> PORTALS-2624: refactor SubscribersModal and ProfileAvatar to use MUI components

packages/synapse-react-client/src/components/Authentication/TOTPForm.tsx
=> trivial fix for 2fa verification code input

apps/portals/src/configurations/elportal/routesConfig.ts
=> EC-123: append another wiki page to the Data Access route

.github/workflows/deploy-to-chromatic.yml, packages/synapse-react-client/.storybook/preview-head.html, packages/synapse-react-client/.storybook/preview.jsx, packages/synapse-react-client/stories/SubsectionRowRenderer.stories.ts
- Update action to reference the pull request ref so the actual changes get deployed and tested
- Load Lato font in Storybook preview-head, since it looks like UI tests commonly get flagged as changed when the font doesn't load in time for the screenshot. See https://www.chromatic.com/docs/resource-loading
- Update SubsectionRowRenderer demo to use existing table. The previous table used in the demo no longer exists, and when that happens we show a skeleton that uses a random number to determine its appearance, which is obviously not stable for snapshots.
=> Stabilize a few UI checks in Chromatic

.github/workflows/deploy-to-chromatic.yml
See https://www.chromatic.com/docs/branching-and-baselines
Currently, screenshot diffs have a baseline of a very early commit because we aren't marking changes as 'accepted'.
If we auto-accept the changes on main, then the screenshot diffs in a PR will always diff between the PR and main branch (unless a UI change was accepted in an ancestor commit in the PR nearer than `main`).
=> Auto-accept changes on `main` to set an accurate baseline

.github/workflows/deploy-to-chromatic.yml, README.md
One way to reduce our snapshot usage is to only run the snapshots on ready-to-review PRs. If you don't yet need snapshots/deployment, mark your PR as a draft.
=> Don't run chromatic deploy on draft PRs

packages/synapse-react-client/.storybook/preview.jsx, packages/synapse-react-client/mocks/mockWiki.ts, packages/synapse-react-client/src/components/AccessRequirementList/AccessRequirementList.tsx, packages/synapse-react-client/src/components/AccessRequirementList/AccessRequirementListUtils.ts, packages/synapse-react-client/src/components/AccessRequirementList/ManagedACTAccessRequirementRequestFlow/DataAccessRequestAccessorsFilesForm.tsx, packages/synapse-react-client/src/components/AccessRequirementList/ManagedACTAccessRequirementRequestFlow/DocumentTemplate.tsx, packages/synapse-react-client/src/components/AccessRequirementList/ManagedACTAccessRequirementRequestFlow/ManagedACTAccessRequirementFormWikiWrapper.tsx, packages/synapse-react-client/src/components/AccessRequirementList/ManagedACTAccessRequirementRequestFlow/ResearchProjectForm.tsx, packages/synapse-react-client/src/components/StorybookComponentWrapper.tsx, packages/synapse-react-client/stories/RejectDataAccessRequestModal.stories.ts, packages/synapse-react-client/stories/SubmissionPage.stories.tsx, packages/synapse-react-client/stories/SubscriptionPage.stories.ts, packages/synapse-react-client/stories/SynapseFormSubmissionsGrid.stories.tsx, packages/synapse-react-client/stories/data-access-request/AccessRequirementList.stories.tsx, packages/synapse-react-client/stories/data-access-request/CertificationRequirement.stories.tsx, packages/synapse-react-client/stories/data-access-request/RequestDataAccessStep1.stories.tsx, packages/synapse-react-client/stories/data-access-request/RequestDataAccessStep2.stories.tsx, packages/synapse-react-client/stories/data-access-request/TwoFactorAuthEnabledRequirement.stories.tsx, packages/synapse-react-client/stories/data-access-request/ValidationRequirement.stories.tsx, packages/synapse-react-client/test/containers/AccessRequirementList/DataAccessRequestAccessorsFilesForm.test.tsx, packages/synapse-react-client/test/containers/AccessRequirementList/ResearchProjectForm.test.tsx
- Show ManagedACTAccessRequirement wiki content if screen size is large enough
- Add Storybook parameter to set default stack, and set default stack to `mock` for those stories where we have configured mock data
[Demo Story](https://6464de5f2e01a2af614b79c7-bzzlyjkwgx.chromatic.com/?path=/story/governance-data-access-request-flow-accessrequirementlist--has-unmet-requirements)
=> SWC-6432: Show wiki instructions with forms for ManagedACTAccessRequirement

packages/synapse-react-client/src/components/dataaccess/AccessRequirementDashboard.tsx, packages/synapse-react-client/src/components/styled/InputSizedButton.tsx, packages/synapse-react-client/src/components/styled/index.ts, packages/synapse-react-client/src/theme/DefaultTheme.tsx
- Add validation to "Filter by Project" field in AccessRequirementDashboard
- Extract "InputSizedButton" which can be kept up-to-date with input height
- Change MuiInput error border to outline to prevent minor content shifts
=> SWC-6466: Validation for AccessRequirementDashboard project input

.github/workflows/deploy-to-chromatic.yml
Our Chromatic trial has expired so we are now limited to 5000 snapshots per month. The Chromatic deployments are not necessarily useful for every PR, so one measure we can take to stay close to our limit is to explicitly enable the Chromatic deployment and UI Snapshot tests for those PRs where a developer or reviewer knows they would be particularly useful.
Once this PR is merged, to trigger a Chromatic deployment, a PR author or reviewer can apply the "chromatic" label in GitHub (applied to this issue for clarity). Once applied, a job will be triggered that deploys the latest commit to Chromatic.
Jobs will not be automatically triggered on new commits after the label is applied; to trigger additional runs on the same PR, remove and re-apply the "chromatic" label again.
For an example, …
=> Run chromatic builds for PRs when "chromatic" label is applied

apps/portals/src/configurations/adknowledgeportal/synapseConfigs/target_enabling_resources.ts, apps/portals/src/configurations/crc-researcher/synapseConfigs/hidden.ts, apps/portals/src/configurations/crc-researcher/synapseConfigs/potential.ts, apps/portals/src/configurations/crc-researcher/synapseConfigs/uncategorized.ts, packages/synapse-react-client/src/components/QueryVisualizationWrapper.tsx, packages/synapse-react-client/src/components/QueryWrapperPlotNav/QueryWrapperPlotNav.tsx, packages/synapse-react-client/src/components/SynapseTable/SynapseTable.tsx, packages/synapse-react-client/stories/QueryWrapperPlotNav.stories.ts
- Move isRowSelectionVisible to QueryVisualizationWrapper from SynapseTableProps
In order for other table components to be aware of row selection (such as TopLevelControls or DownloadOptions), row visibility must be exposed through context, rather than props provided exclusively to the SynapseTable component.
=> PORTALS-2701 - refactor location of `isRowSelectionVisible`

.github/workflows/npmpublish.yml, packages/markdown-it-synapse/package.json, packages/synapse-react-client/.storybook/preview-head.html
- add back IIFE/UMD distribution
- If version did not increment, `pnpm publish` should include `--dry-run`
=> fix markdown-it-synapse publish and deployment

packages/synapse-react-client/src/components/DownloadCart/DownloadListTable.tsx, packages/synapse-types/src/DownloadListV2/DownloadListItemResult.ts
Related to: https://sagebionetworks.jira.com/browse/SWC-6332
* Updated type `DownloadListItemResult` to allow versionNumber to be optional
* In `DownloadListTable.tsx`, call entityVersionNumber.toString() only when entityVersionNumber is not null. If entityVersionNumber is null, then exclude it from prop.
=> [bug fix]: set version number as optional in DownloadListItemResult

.github/workflows/build-and-deploy-app.yml
There's an error when the deploy-app run, this variable is handled by GHA, not shell (typo).
=> PORTALS-2622: Fix substitution

apps/portals/src/configurations/cancercomplexity/resources.ts, apps/portals/src/configurations/cancercomplexity/routeControlWrapperProps.ts, apps/portals/src/configurations/cancercomplexity/routesConfig.ts, apps/portals/src/configurations/cancercomplexity/synapseConfigs/education.ts, apps/portals/src/configurations/cancercomplexity/synapseConfigs/index.ts
More information about the proposed feature in the parent ticket [here](https://sagebionetworks.jira.com/browse/CPO-512)
TL;DR -
Add a new section called "Educational Resources" to CCKP, which will display information about education-related SOPs generated by the MC2 Center community
CC: @aclayton555 
**Explore Page**
**Details Page**
> **Note**: @aclayton555 is working on marking the education portal table as open-data
=> CPO-690: add new module called "Educational Resources"

apps/SageAccountWeb/package.json, apps/portals/package.json, apps/portals/src/utils.ts, apps/synapse-oauth-signin/package.json, pnpm-lock.yaml
react-use is no longer maintained: https://github.com/streamich/react-use/issues/1974
Some maintainers have migrated to @react-hookz/web, which also has a guide for migrating from react-use to @react-hookz/web
=> replace react-use with @react-hookz/web

packages/synapse-react-client/src/components/EntityFinder/EntityFinderModal.tsx, packages/synapse-react-client/src/components/dataaccess/AccessRequirementDashboard.tsx
Ann suggested that the current (two-pane) view was confusing. It isn't intuitive to use the two-pane view to pick all projects, since you have to pick the "fake" folder of "All projects" before you can pick a project.
Using the "treeOnly" view simplifies the interface, and makes selecting a project more intuitive.
=> SWC-6501: Use treeOnly Entity Finder for access requirement related project selection

.github/workflows/deploy-to-chromatic.yml, packages/synapse-react-client/.storybook/main.ts, packages/synapse-react-client/package.json, pnpm-lock.yaml
[TurboSnap](https://www.chromatic.com/docs/turbosnap) uses the commit history + Vite build to attempt to reduce the snapshots taken by only snapshotting changed stories.
=> Enable Turbosnap to reduce Chromatic snapshot usage

packages/synapse-react-client/src/utils/hooks/usePreFetchResource.ts, packages/synapse-react-client/test/utils/hooks/usePreFetchResource.integration.test.tsx
Use react-query cache to dedupe requests file content using presigned URLs, such as profile pictures.
=> SWC-6506 - Don't fetch duplicate profile pictures

packages/synapse-react-client/src/utils/hooks/useCommittedState.ts, packages/synapse-react-client/test/utils/hooks/useCommittedState.test.ts
useCommittedState will be used to track two versions of a query request in state. This could be useful for any form with an intermediate set of changes that should all be committed in one transaction.
=> PORTALS-2752 - add useCommittedState hook

packages/synapse-react-client/src/components/useImmutableTableQuery.ts, packages/synapse-react-client/src/components/widgets/facet-nav/SelectionCriteriaPills.tsx, packages/synapse-react-client/src/utils/functions/deepLinkingUtils.ts, packages/synapse-react-client/src/utils/functions/queryUtils.ts, packages/synapse-react-client/test/containers/QueryWrapper.test.tsx, packages/synapse-react-client/test/containers/queryUtils.test.ts, packages/synapse-react-client/test/utils/hooks/useImmutableTableQuery.test.tsx
Refactoring / improvements related to PORTALS-2752 - query state management must be overhauled, so I made a few changes to streamline side effects and improve UX
- onChange will be invoked when setState is called internally. Before, it was wrapped in `useEffect` where we had logic to prevent it from running conditionally on the first render. `useEffect` is the wrong mechanism for this kind of behavior
- Deep linking (URL search params) code will always synchronize with the current query.
- If the current query matches the initial query, and is deep linking, then the URL search parameter will be removed
- Remove extraneous query parameters like null values and extra arrays to better match queries for deep linking and cache hits
Also fix PORTALS-2758 - lockedColumn matching should be …
=> PORTALS-2752 , PORTALS-2758 - refactor QueryWrapper deep linking/onChange, fix lockedColumn issue, drop extraneous query params

packages/synapse-react-client/src/components/FullTextSearch.tsx, packages/synapse-react-client/src/components/SynapseTable/SqlEditor.tsx, packages/synapse-react-client/src/style/components/_query-wrapper-plot-nav.scss, packages/synapse-react-client/src/style/components/_query-wrapper-text-input.scss
Changed FullTextSearch and SqlEditor components to match SDS style and put info button inside the input. While these changes were not explicitly called out in designs, it supports PORTALS-2636 by having the end of the input align with the right edge of the components
Also updated CSS margins for many components
|Component|Before|After|
|---|---|---|
|FullTextSearch|![image](https://github.com/Sage-Bionetworks/synapse-web-monorepo/assets/17580037/e4868143-53b7-49d0-831b-13b6335608e0) |![image](https://github.com/Sage-Bionetworks/synapse-web-monorepo/assets/17580037/89b1bbf6-504c-4269-bfb2-7be1036938ec) |
| SqlEditor | ![image](https://github.com/Sage-Bionetworks/synapse-web-monorepo/assets/17580037/c4efe8c2-f534-41cf-b7e3-2eb2e368350d)| …
=> PORTALS-2634, PORTALS-2636 - SDS for FullTextSearch, SqlEditor, Explore alignment fixes

apps/portals/src/portal-components/RouteControlWrapper.tsx, apps/portals/src/utils.ts
=> PORTALS-2634, PORTALS-2636: TopLevelControls/TotalQueryResults appears to be full width in portals

apps/portals/src/configurations/arkportal/style/_style_overrides.scss, apps/portals/src/configurations/crc-researcher/style/_style_overrides.scss, apps/portals/src/configurations/digitalhealth/style/_style_overrides.scss, apps/portals/src/portal-components/RouteControlWrapper.tsx, apps/portals/src/utils.ts, packages/synapse-react-client/src/components/DirectDownload/DirectDownload.tsx, packages/synapse-react-client/src/components/GenericCard/GenericCard.tsx, packages/synapse-react-client/src/components/IconSvg/IconSvg.tsx, packages/synapse-react-client/src/components/QueryWrapperPlotNav/FilterAndView.tsx, packages/synapse-react-client/src/components/SynapseTable/SynapseTable.tsx, packages/synapse-react-client/src/components/SynapseTable/SynapseTableCell/JSON/JSONArrayRenderer.tsx, packages/synapse-react-client/src/components/SynapseTable/SynapseTableCell/JSON/JSONTableCellRenderer.tsx, packages/synapse-react-client/src/components/SynapseTable/SynapseTableCell/JSON/__snapshots__/JSONTableCellRenderer.test.tsx.snap, packages/synapse-react-client/src/components/SynapseTable/SynapseTableCell/SynapseTableCell.tsx, packages/synapse-react-client/src/components/SynapseTable/TablePagination.tsx, packages/synapse-react-client/src/components/SynapseTable/TopLevelControls/TopLevelControls.tsx, packages/synapse-react-client/src/components/widgets/facet-nav/FacetNav.tsx, packages/synapse-react-client/src/components/widgets/facet-nav/FacetNavPanel.tsx, packages/synapse-react-client/src/components/widgets/query-filter/EnumFacetFilter.tsx, packages/synapse-react-client/src/style/base/_core.scss, packages/synapse-react-client/src/style/components/_cards.scss, packages/synapse-react-client/src/style/components/_expandable_table_data.scss, packages/synapse-react-client/src/style/components/_query-wrapper-plot-nav.scss, packages/synapse-react-client/src/style/components/facet_nav/_facet-nav-panel.scss, packages/synapse-react-client/src/style/components/facet_nav/_facet-nav.scss, packages/synapse-react-client/src/style/components/query_filter/_enum-facet-filter.scss, packages/synapse-react-client/test/containers/widgets/facet-nav/FacetNavPanel.test.tsx
QueryWrapperPlotNav:
- Remove old FacetNav loading spinner and replace with a cleaner one in FilterAndView
- Use grid column gap instead of margin to set space between QueryWrapperPlotNav components
SynapseTable:
- Update many table styles
- Use MUI icons as in design
- Remove bootstrap `.table` classes
- Remove SRC_noBorderTop class and adjust portals custom styles to accomodate
- Separate table pagination component from overflow wrapper
FacetNavPanel:
- Use MUI icons
EnumFacetFilter:
- Use MUI icon for dropdown mode
- Replace bootstrap dropdown with MUI implementation
SynapseTableCell
- JSON cells should always be wrapped in a `Typography` (`p`)
- Wrap `DirectDownload` in `p` and style with primary color
- USERID and Links should use `Link` instead of `a`
- Numerics aligned right and …
=> PORTALS-2639 - QueryWrapperPlotNav/SynapseTable style updates

apps/portals/src/configurations/elportal/synapseConfigs/cohortbuilder.ts, packages/synapse-react-client/src/components/QueryContext/QueryContext.tsx, packages/synapse-react-client/src/components/QueryWrapper/QueryWrapper.tsx, packages/synapse-react-client/src/components/QueryWrapper/useTableRowSelection.test.tsx, packages/synapse-react-client/src/components/QueryWrapper/useTableRowSelection.ts, packages/synapse-react-client/src/components/SynapseTable/SynapseTable.tsx
PORTALS-2771 references a case where there is no `rowId`, which breaks 'selected' checkbox state. Add a new helper to determine this state. When defined, we should reference the `rowSelectionPrimaryKey` (so add it for the corresponding EL Portal Cohort Builder case). If there's no specified primary key, gracefully fall back to using rowId or the `id` column when it is appropriate, using deep comparison of Row objects as a last resort.
One goal that is considered, though not yet attained, is to allow users to maintain a cohort selection between sessions. Since data in the portal may change over time, using a primary key is more resilient than using deep equality. However, this is still not perfect; we don't save column models, so this would still break if the index of the primary key …
=> PORTALS-2771 - primary key equality check to determine row selection

apps/portals/src/configurations/elportal/synapseConfigs/cohortbuilder.ts, packages/synapse-react-client/src/components/widgets/facet-nav/SelectionCriteriaPills.tsx
PORTALS-2773
Also needed to modify SelectionCriteriaPills to handle cases where we have a filter where a column model is not present, since these filters are applied to columns on the table/view referenced in the definingSql.
=> PORTALS-2773 - fix cohort builder applied filters

packages/synapse-react-client/src/synapse-queries/KeyFactory.ts, packages/synapse-react-client/src/utils/functions/StringUtils.ts
SWC apparently sets `accessToken` to `null`, which is an unhandled case (only `undefined` was handled)
=> Fix null case for hashCode

packages/synapse-react-client/src/components/ProjectViewCarousel/ProjectViewCard.tsx, packages/synapse-react-client/src/components/ProjectViewCarousel/ProjectViewCarousel.tsx, packages/synapse-react-client/src/style/components/_project-view-card.scss
It looks ok in SWC because the MUI styles are loaded before the SRC styles, so the correct styles override the bad styles. I reimplemented the components using MUI to prevent this issue from occuring if the load order were to change.
=> SWC-6510 - Fix ProjectViewCard styling, use MUI

packages/synapse-react-client/src/components/QueryWrapper/QueryWrapperLoadingScreen.tsx, packages/synapse-react-client/src/components/QueryWrapperPlotNav/FilterAndView.tsx, packages/synapse-react-client/src/components/StandaloneQueryWrapper/StandaloneQueryWrapper.tsx
Depends on #429 
[Screencast from 08-28-2023 05:07:59 PM.webm](https://github.com/Sage-Bionetworks/synapse-web-monorepo/assets/17580037/d8c36bcd-4016-4237-af10-d6d9fbebf928)
=> SWC-6520 - Extract new component QueryWrapperLoadingScreen and re-use in StandaloneQueryWrapper

packages/synapse-react-client/src/umd.index.ts, packages/synapse-react-client/src/utils/functions/index.ts
Allows HttpClient and BackendDestinationEnum to be called when evaluating JS in the browser page in a Playwright test, e.g. `window.SRC.HttpClient.doGet(...)`
=> SWC-6531: expose HttpClient and BackendDestinationEnum in UMD, allow BackendDestinationEnum to be used as value

.github/workflows/build-test.yml
Using a larger runner brings our `test` job worst-case time to around 17m: https://github.com/Sage-Bionetworks/synapse-web-monorepo/actions/runs/6030039839/job/16360992278?pr=455
With the regular runner we were consistently seeing times >30min
=> PORTALS-2793 - Use a larger runner, add a 1hr timeout, and remove the existing parallel job limit

packages/synapse-react-client/src/components/UserOrTeamBadge/UserOrTeamBadge.tsx
`UserOrTeamBadge` provides two 'interfaces' so the userGroupHeader data can be either provided or fetched (via react-query) using a principalId. This bug only occurred when data was fetched, but the faulty logic existed to manage both scenarios.
The data was stored in `useState`. Due to incorrect logic in an effect, the data was NOT updated when the fetched data changed due to the `principalId` changing.
We can remove the effect and just pick the correct object inline and the bug is resolved.
=> SWC-6552 - Fix UserOrTeamBadge showing stale data

packages/synapse-react-client/src/components/QueryVisualizationWrapper/QueryVisualizationWrapper.integration.test.tsx, packages/synapse-react-client/src/components/QueryVisualizationWrapper/QueryVisualizationWrapper.tsx, packages/synapse-react-client/src/components/SynapseTable/SynapseTable.integration.test.tsx, packages/synapse-react-client/src/components/SynapseTable/SynapseTableRenderers.tsx, packages/synapse-react-client/src/utils/functions/queryUtils.ts, packages/synapse-react-client/src/utils/types/UniqueFacetIdentifier.ts, packages/synapse-react-client/test/containers/queryUtils.test.ts
* don't show JSON subcolumn facet controls in SynapseTable
* Add new utilities getCorrespondingColumnForFacet, getCorrespondingSelectedFacet
* Allow supplying a JSONPath in QueryVisualizationContext.getColumnDisplayName
=> SWC-6549 - New utilities for getting subcolumn information

packages/synapse-react-client/src/components/SchemaDrivenAnnotationEditor/AnnotationEditorUtils.test.ts, packages/synapse-react-client/src/components/SchemaDrivenAnnotationEditor/AnnotationEditorUtils.ts, packages/synapse-react-client/src/components/SchemaDrivenAnnotationEditor/SchemaDrivenAnnotationEditor.tsx, packages/synapse-react-client/src/components/SchemaDrivenAnnotationEditor/SchemaDrivenAnnotationsEditor.integration.test.tsx, packages/synapse-react-client/src/components/SchemaDrivenAnnotationEditor/widget/SelectWidget.tsx, packages/synapse-react-client/src/components/entity/metadata/AnnotationsTable.integration.test.tsx, packages/synapse-react-client/src/components/entity/metadata/AnnotationsTable.tsx, packages/synapse-react-client/src/synapse-client/SynapseClient.ts, packages/synapse-react-client/src/synapse-queries/KeyFactory.ts, packages/synapse-react-client/src/synapse-queries/entity/useEntity.ts, packages/synapse-react-client/src/utils/functions/EntityTypeUtils.ts, packages/synapse-types/src/Entity/Entity.ts, packages/synapse-types/src/OAuthClient.ts, packages/synapse-types/src/Table/Dataset.ts, packages/synapse-types/src/Table/QueryFilter.ts, packages/synapse-types/src/Table/SubmissionView.ts, packages/synapse-types/src/Table/Table.ts, packages/synapse-types/src/Table/TableEntity.ts, packages/synapse-types/src/Table/View.ts, packages/synapse-types/src/TrashedEntity.ts
- AnnotationsTable now shows derived annotations and shows a warning when derived annotations may be pending. The warning allows the end user to refetch the data
- Fix issue where top level null values would not be cleared before they were sent to Synapse, resulting in the update annotations call being rejected
- Update Annotations form to clean the formData onBlur so UI validation is more likely to match platform validation.
- Update getEntityJSON service call to allow fetching derived annotations
- Update query key/invalidation behavior to handle new `includeDerivedAnnotations` boolean parameter
- Do NOT fetch derived annotations in editor
- Add test.todo for AnnotationsTable since the entire component is pending design review
- Move AnnotationEditorUtilsTest to `src` to be typechecked …
=> SWC-6580 - Show derived annotations in AnnotationsTable component

packages/synapse-react-client/src/components/TableColumnSchemaEditor/TableColumnSchemaEditorUtils.test.ts, packages/synapse-react-client/src/components/TableColumnSchemaEditor/TableColumnSchemaEditorUtils.ts, packages/synapse-react-client/src/components/TableColumnSchemaEditor/TableColumnSchemaFormReducer.test.ts, packages/synapse-react-client/src/components/TableColumnSchemaEditor/TableColumnSchemaFormReducer.ts
This PR contains the bulk of the business logic for managing data in the Table Column Schema form in SWC-6548
=> SWC-6548 - Add utils and reducer for TableColumnSchemaEditor

packages/synapse-react-client/src/style/components/_submission-page.scss
Fixes SWC-6594
Before change: 
After change:
=> SWC-6594 - Fix grid blowout on review submission page

packages/synapse-react-client/src/components/Markdown/MarkdownCollapse.stories.ts, packages/synapse-react-client/src/components/Markdown/MarkdownCollapse.tsx
=> PORTALS-2513: restyle MarkdownCollapse, move to mui (remove bootstrap)

packages/synapse-react-client/src/components/Skeleton/SkeletonTable.tsx, packages/synapse-react-client/src/components/TableColumnSchemaEditor/ColumnModelForm.tsx, packages/synapse-react-client/src/components/TableColumnSchemaEditor/TableColumnSchemaEditor.integration.test.tsx, packages/synapse-react-client/src/components/TableColumnSchemaEditor/TableColumnSchemaEditor.stories.ts, packages/synapse-react-client/src/components/TableColumnSchemaEditor/TableColumnSchemaEditor.tsx, packages/synapse-react-client/src/components/TableColumnSchemaEditor/TableColumnSchemaForm.tsx, packages/synapse-react-client/src/mocks/entity/mockFileView.ts, packages/synapse-react-client/src/mocks/query/syn17328596.ts, packages/synapse-react-client/src/theme/DefaultTheme.tsx, packages/synapse-react-client/src/theme/palette/Palettes.ts
- Add TableColumnSchemaForm component, which allows creating and modifying Synapse Table column schema data
- Add TableColumnSchemaEditor, which loads column model data and inserts it into TableColumnSchemaForm
- Update `neutral` palette use gray 700 as a base color, which makes buttons look more interactive
- Change TextField background color when field is disabled
https://github.com/Sage-Bionetworks/synapse-web-monorepo/assets/17580037/063c7861-5ba5-4ca3-a7ee-f4575161caf9
=> SWC-6548 - Add TableColumnSchemaEditor

.github/workflows/deploy-to-chromatic.yml
Dependabot is creating these and I think that's what's burning through many of our free snapshots
=> Don't run Chromatic workflow for unlabeled pull_request_target events

packages/synapse-react-client/package.json
Release of 3.1.62 failed, but was fixed by #557
=> Bump synapse-react-client to v3.1.63

packages/synapse-react-client/src/components/TableColumnSchemaEditor/ColumnModelForm.tsx, packages/synapse-react-client/src/components/TableColumnSchemaEditor/TableColumnSchemaEditorUtils.test.ts, packages/synapse-react-client/src/components/TableColumnSchemaEditor/TableColumnSchemaEditorUtils.ts, packages/synapse-react-client/src/components/TableColumnSchemaEditor/TableColumnSchemaForm.tsx, packages/synapse-react-client/src/components/TableColumnSchemaEditor/TableColumnSchemaFormReducer.test.ts, packages/synapse-react-client/src/components/TableColumnSchemaEditor/TableColumnSchemaFormReducer.ts
- Fix vertical alignment for default column data
- Expose and stub `validate` handle
- Improve readability of some logic
- Minimum specified maximumSize should be 1, not 0
- For STRING columns, maximum specified maximumSize should be 1000, not 50
=> SWC-6610 - small tweaks/fixes for TableColumnSchemaForm

.github/workflows/codeql.yml
Our dependabot PRs all fail because they run CodeQL on the `push` action. These CodeQL jobs fail because write access to the repo is required, and these PRs are granted `readonly` access.
Requiring that the pushed branch is `main` should clean these up.
=> Only run CodeQL push action on main branch to fix dependabot PR failures

packages/synapse-react-client/src/components/TimelinePlot/TimelinePlotSpeciesSelector.tsx
When querying for species for the timeline viz, ignore observations that have a null observationTime.
=> PORTALS-2853

.github/actions/pnpm-setup-action/action.yml, packages/synapse-react-client/src/components/JSONArrayEditor/JSONArrayEditor.tsx, packages/synapse-react-client/src/components/JSONArrayEditor/JSONArrayEditorModal.test.tsx, packages/synapse-react-client/src/components/JSONArrayEditor/JSONArrayEditorModal.tsx, packages/synapse-react-client/src/components/SchemaDrivenAnnotationEditor/CustomFormContext.ts, packages/synapse-react-client/src/components/SchemaDrivenAnnotationEditor/SchemaDrivenAnnotationEditor.tsx, packages/synapse-react-client/src/components/SchemaDrivenAnnotationEditor/template/ArrayFieldTemplate.tsx, packages/synapse-react-client/src/components/SchemaDrivenAnnotationEditor/template/ButtonTemplate.tsx, packages/synapse-react-client/src/components/SchemaDrivenAnnotationEditor/template/ErrorListTemplate.tsx, packages/synapse-react-client/src/components/TableColumnSchemaEditor/ColumnModelForm.tsx, packages/synapse-react-client/src/components/TableColumnSchemaEditor/ColumnModelFormFields/DefaultValueField.test.tsx, packages/synapse-react-client/src/components/TableColumnSchemaEditor/ColumnModelFormFields/DefaultValueField.tsx, packages/synapse-react-client/src/components/TableColumnSchemaEditor/ColumnModelFormFields/RestrictedValuesField.test.tsx, packages/synapse-react-client/src/components/TableColumnSchemaEditor/ColumnModelFormFields/RestrictedValuesField.tsx, packages/synapse-react-client/src/components/TableColumnSchemaEditor/TableColumnSchemaEditor.integration.test.tsx, packages/synapse-react-client/src/components/TableColumnSchemaEditor/TableColumnSchemaEditor.stories.ts, packages/synapse-react-client/src/components/TableColumnSchemaEditor/TableColumnSchemaEditor.tsx, packages/synapse-react-client/src/components/TableColumnSchemaEditor/TableColumnSchemaEditorUtils.test.ts, packages/synapse-react-client/src/components/TableColumnSchemaEditor/TableColumnSchemaEditorUtils.ts, packages/synapse-react-client/src/components/TableColumnSchemaEditor/TableColumnSchemaFormReducer.test.ts, packages/synapse-react-client/src/components/TableColumnSchemaEditor/TableColumnSchemaFormReducer.ts, packages/synapse-react-client/src/components/entity/metadata/EntityModal.tsx, packages/synapse-react-client/src/theme/DefaultTheme.tsx
SWC-6611
- Add `DefaultValueField` and `RestrictedValuesField` components where the form field varies on column type
- Move custom animation props to theme for consistency/simplicity
- Use columnModels from table bundle instead of query in (unused) editor component
- Reset restricted/default value on column type change
- Disallow default values for _LIST types since they don't work on the backend
- Changes to RJSF custom ArrayFieldTemplate to allow empty arrays
https://github.com/Sage-Bionetworks/synapse-web-monorepo/assets/17580037/d5acad29-d91d-4031-99c8-65f215f5796d
=> SWC-6611 - ColumnType-aware fields in TableColumnSchemaForm 

packages/synapse-react-client/src/components/JSONArrayEditor/JSONArrayEditor.tsx, packages/synapse-react-client/src/components/JSONArrayEditor/JSONArrayEditorModal.tsx, packages/synapse-react-client/src/components/JSONArrayEditor/useParseCsv.ts, packages/synapse-react-client/src/components/TableColumnSchemaEditor/ColumnModelForm.tsx, packages/synapse-react-client/src/components/TableColumnSchemaEditor/ColumnModelFormFields/DefaultValueField.test.tsx, packages/synapse-react-client/src/components/TableColumnSchemaEditor/ColumnModelFormFields/DefaultValueField.tsx, packages/synapse-react-client/src/components/TableColumnSchemaEditor/ColumnModelFormFields/MultiValueField.test.tsx, packages/synapse-react-client/src/components/TableColumnSchemaEditor/ColumnModelFormFields/MultiValueField.tsx, packages/synapse-react-client/src/components/TableColumnSchemaEditor/ImportTableColumnsButton.tsx, packages/synapse-react-client/src/components/TableColumnSchemaEditor/TableColumnSchemaEditor.integration.test.tsx, packages/synapse-react-client/src/components/TableColumnSchemaEditor/TableColumnSchemaEditor.stories.ts, packages/synapse-react-client/src/components/TableColumnSchemaEditor/TableColumnSchemaEditor.tsx, packages/synapse-react-client/src/components/TableColumnSchemaEditor/TableColumnSchemaEditorUtils.test.ts, packages/synapse-react-client/src/components/TableColumnSchemaEditor/TableColumnSchemaEditorUtils.ts, packages/synapse-react-client/src/components/TableColumnSchemaEditor/TableColumnSchemaForm.tsx, packages/synapse-react-client/src/components/TableColumnSchemaEditor/TableColumnSchemaFormReducer.test.ts, packages/synapse-react-client/src/components/TableColumnSchemaEditor/TableColumnSchemaFormReducer.ts, packages/synapse-react-client/src/components/TableColumnSchemaEditor/Validators/ColumnModelValidator.ts
- Validate and parse form data with Zod on submission
- Render Zod error messages in fields where an error exists after submission
- Use Zod inferred types to describe input form data (update ColumnModelFormData/JsonSubColumnModelFormData)
- Rename RestrictedValuesField to MultiValueField and genericize the type value
- Allow default values for LIST columns
- Change DefaultValueField to show custom for BOOLEAN and DATE columns. LIST columns will now use MultiValueField
- Number fields changed to text fields to allow entering any valid value, such as strings like "Infinity" for DOUBLE columns
- Refactor CSV parsing logic out of JSONArrayEditor and modify functionality to parse the data as non-strings if the passed JSON schema does not specify string items
=> SWC-6612 - Integrate validation with Table Column Schema Form

packages/synapse-react-client/src/components/EntityHeaderTable/EntityHeaderTable.integration.test.tsx, packages/synapse-react-client/src/components/EntityHeaderTable/EntityHeaderTable.tsx, packages/synapse-react-client/src/components/EntityHeaderTable/useEntityHeaderTableState.ts
- Allow hiding text field for entering values via prop
- Allow overriding entity finder config
- Allow overriding "entity" copy
- Fix eslint warnings
=> SWC-6627 - Extend EntityHeaderTable for use in view scope editor

packages/synapse-react-client/demo/containers/playground/ToastDemo.tsx, packages/synapse-react-client/demo/containers/playground/WidgetDemo.tsx, packages/synapse-react-client/src/components/AccessRequirement/ImposeRestrictionDialog/ImposeRestrictionDialog.tsx, packages/synapse-react-client/src/components/AccessRequirementList/ManagedACTAccessRequirementRequestFlow/DataAccessRequestAccessorsEditor.tsx, packages/synapse-react-client/src/components/ChallengeSubmission/EvaluationQueueList.tsx, packages/synapse-react-client/src/components/ChallengeSubmission/SubmissionCommitList.tsx, packages/synapse-react-client/src/components/ChallengeSubmission/SubmissionDirectoryList.tsx, packages/synapse-react-client/src/components/ChallengeTeamWizard/ChallengeTeamTable.tsx, packages/synapse-react-client/src/components/widgets/RadioGroup.test.tsx, packages/synapse-react-client/src/components/widgets/RadioGroup.tsx, packages/synapse-react-client/src/components/widgets/query-filter/RangeFacetFilterUI.tsx
- Allow passing a ReactNode label
- Allow disabling the group
- Make `id` optional, and use `useId` to generate a unique ID when one is not provided
In SWC-6627 we will be reimplementing the ability to add evaluations to a SubmissionView. The existing UI uses a radio group. We will want to disable the radio group inputs while the data changes, e.g. loading new pages
=> SWC-6627 - Improvements for custom RadioGroup

packages/synapse-react-client/src/components/EntityHeaderTable/EntityHeaderTable.tsx, packages/synapse-react-client/src/components/Markdown/MarkdownPopover.stories.tsx, packages/synapse-react-client/src/components/Markdown/MarkdownPopover.tsx, packages/synapse-react-client/src/components/styled/LightTooltip.tsx, packages/synapse-react-client/src/theme/ThemeProvider.tsx, packages/synapse-react-client/src/theme/index.ts, packages/synapse-react-client/src/theme/mergeTheme.test.tsx, packages/synapse-react-client/src/theme/mergeTheme.ts, packages/synapse-react-client/src/utils/context/FullContextProvider.tsx, packages/synapse-react-client/stories/stubs/Tooltip/MuiTooltip.stories.tsx, packages/synapse-react-client/stories/stubs/Tooltip/MuiTooltip.tsx
- Fix issue where LightTooltip / MarkdownPopover / HelpPopover links would be white-on-white bg
- MarkdownPopover: Only allow one open popover at a time (match Bootstrap behavior)
- MarkdownPopover: Make close-on-click the default behavior
- Add stories for Tooltip
- Add light interaction tests in Tooltip and MarkdownPopover stories
- Relocated `mergeTheme` function to optimize Vite fast refresh
=> SWC-6627 - Tooltip improvements

.eslintrc.cjs, .github/workflows/end-to-end-test-portals.yml, apps/portals/.gitignore, apps/portals/e2e/README.md, apps/portals/e2e/configs/bannersConfig.ts, apps/portals/e2e/configs/exploreConfig.ts, apps/portals/e2e/configs/routesConfig.ts, apps/portals/e2e/explore.spec.ts, apps/portals/e2e/helpers/banners.ts, apps/portals/e2e/helpers/portalInfo.ts, apps/portals/e2e/homepage.spec.ts, apps/portals/e2e/view_github_report.sh, apps/portals/package.json, apps/portals/playwright.config.ts, apps/portals/tsconfig.json, pnpm-lock.yaml
- Use Playwright for e2e testing of Portals 
- Add general e2e tests for all Portals for Homepage links and Explore tabs 
- Run e2e tests on push/PR to main Sage branch and on all pushes to forked repos. See example workflow [here](https://github.com/Sage-Bionetworks/synapse-web-monorepo/actions/runs/7252816010)
- Download and review e2e report with traces by following [these steps](https://github.com/hallieswan/synapse-web-monorepo/tree/PORTALS-2872/apps/portals/e2e#ci)
=> PORTALS-2872: add end-to-end testing for Portals

packages/synapse-react-client/src/components/AccessRequirementRelatedProjectsList/AccessRequirementRelatedProjectsList.stories.ts, packages/synapse-react-client/src/components/AccessRequirementRelatedProjectsList/AccessRequirementRelatedProjectsList.tsx, packages/synapse-react-client/src/components/AccessRequirementRelatedProjectsList/index.ts, packages/synapse-react-client/src/components/EntityLink.tsx, packages/synapse-react-client/src/components/index.ts, packages/synapse-react-client/src/umd.index.ts, packages/synapse-types/src/AccessRequirement/AccessRequirementSearch.ts
Will be used in SWC to display a list of associated projects on each AR page. See SWC changes [here](https://github.com/Sage-Bionetworks/SynapseWebClient/pull/5247).
=> SWC-6618: create list of associated projects for an AR

packages/synapse-react-client/src/components/AccessRequirementList/AccessRequirementList.tsx, packages/synapse-react-client/src/components/AccessRequirementList/AccessRequirementListItem.tsx, packages/synapse-react-client/src/components/DownloadCart/MeetAccessRequirementCard.integration.test.tsx, packages/synapse-react-client/src/components/DownloadCart/MeetAccessRequirementCard.tsx, packages/synapse-react-client/src/components/dataaccess/AccessRequirementTable.integration.test.tsx, packages/synapse-react-client/src/components/dataaccess/AccessRequirementTable.tsx, packages/synapse-react-client/src/mocks/mockAccessRequirements.ts, packages/synapse-react-client/src/mocks/msw/handlers/accessRequirementHandlers.ts, packages/synapse-react-client/src/utils/types/IsType.ts, packages/synapse-types/src/AccessRequirement/ACTAccessRequirement.ts, packages/synapse-types/src/AccessRequirement/ACTAccessRequirementInterface.ts, packages/synapse-types/src/AccessRequirement/AccessRequirement.ts, packages/synapse-types/src/AccessRequirement/AccessRequirementSearch.ts, packages/synapse-types/src/AccessRequirement/LockAccessRequirement.ts, packages/synapse-types/src/AccessRequirement/ManagedACTAccessRequirement.ts, packages/synapse-types/src/AccessRequirement/SelfSignAccessRequirement.ts, packages/synapse-types/src/AccessRequirement/SelfSignAccessRequirementInterface.ts, packages/synapse-types/src/AccessRequirement/TermsOfUseAccessRequirement.ts
I mapped the AR concrete type to a display value, which is shown in the AR table. If there is an established mapping or a better approach, happy to use that instead! 
- org.sagebionetworks.repo.model.SelfSignAccessRequirement -> Click-Wrap
- org.sagebionetworks.repo.model.ManagedACTAccessRequirement -> Managed
- org.sagebionetworks.repo.model.ACTAccessRequirement -> Basic
- org.sagebionetworks.repo.model.LockAccessRequirement -> Lock
- org.sagebionetworks.repo.model.TermsOfUseAccessRequirement -> Terms of Use
=> SWC-6617: add AR type column to AR table in ACT dashboard

packages/synapse-react-client/src/style/components/_synapse-homepage.scss
=> SWC-6628: left align ProjectViewCarousel text on home page

packages/synapse-react-client/src/components/EntityHeaderTable/DebouncedInput.tsx, packages/synapse-react-client/src/components/EntityHeaderTable/EntityHeaderTable.integration.test.tsx, packages/synapse-react-client/src/components/EntityHeaderTable/EntityHeaderTable.stories.ts, packages/synapse-react-client/src/components/EntityHeaderTable/EntityHeaderTable.tsx, packages/synapse-react-client/src/components/EntityHeaderTable/Filter.tsx, packages/synapse-react-client/src/mocks/entity/index.ts, packages/synapse-react-client/src/mocks/entity/mockFileEntity.ts, packages/synapse-react-client/src/mocks/entity/mockProject.ts, packages/synapse-react-client/src/mocks/faker/generateFakeEntity.ts
- Move filter inputs above table
- Change sort icon to always be visible if table can be sorted
- Handle case where filters would not be cleared if items were removed to cause the filter controls to be hidden
- Update styling to get closer to design
- Fix prop signature for DebouncedInput to accept `label`
|Before|After|
|---|---|
| <img width="939" alt="image" src="https://github.com/Sage-Bionetworks/synapse-web-monorepo/assets/17580037/7cd6c2d5-afc3-43cd-9300-25e6695a1a0f"> | <img width="939" alt="image" src="https://github.com/Sage-Bionetworks/synapse-web-monorepo/assets/17580037/f72bd0c1-40a8-4249-bf63-7d49387d8c13"> |
=> SWC-6627 - EntityHeaderTable style updates + small fixes

.github/workflows/npmpublish.yml, packages/markdown-it-synapse/README.md, packages/synapse-types/LICENSE, packages/synapse-types/README.md, packages/synapse-types/package.json
See passing npmpublish dryrun for `@sage-bionetworks/synapse-types` [here](https://github.com/Sage-Bionetworks/synapse-web-monorepo/actions/runs/7415916429/job/20179937481)
Note: failing e2e tests are fixed in #634
=> SWC-6529: publish @sage-bionetworks/synapse-types package

packages/synapse-react-client/src/components/EvaluationFinder/EvaluationFinder.stories.tsx, packages/synapse-react-client/src/components/EvaluationFinder/EvaluationFinder.test.tsx, packages/synapse-react-client/src/components/EvaluationFinder/EvaluationFinder.tsx, packages/synapse-react-client/src/components/Markdown/MarkdownPopover.tsx, packages/synapse-react-client/src/components/styled/LightTooltip.tsx, packages/synapse-react-client/src/components/widgets/Checkbox.test.tsx, packages/synapse-react-client/src/components/widgets/Checkbox.tsx, packages/synapse-react-client/src/synapse-client/SynapseClient.ts, packages/synapse-react-client/src/synapse-queries/InfiniteQueryUtils.test.ts, packages/synapse-react-client/src/synapse-queries/InfiniteQueryUtils.ts, packages/synapse-react-client/src/synapse-queries/KeyFactory.ts, packages/synapse-react-client/src/synapse-queries/entity/useEntity.ts, packages/synapse-react-client/src/synapse-queries/evaluation/useEvaluation.ts, packages/synapse-react-client/src/synapse-queries/trash/useTrashCan.ts, packages/synapse-react-client/src/synapse-queries/user/useFavorites.ts, packages/synapse-react-client/src/synapse-queries/user/useGetUserTeams.ts, packages/synapse-react-client/src/utils/APIConstants.ts, packages/synapse-react-client/src/utils/hooks/useGetInfoFromIds.ts, packages/synapse-types/src/Evaluation/GetEvaluationParameters.ts
- Add EvaluationFinder, which will be used to choose evaluations for a SubmissionView
- Update MarkdownPopover to not propagate click and prevent default behavior, fixing a case where opening a popover would toggle the checkbox in the EvaluationFinder
- Update Checkbox to allow passing any ReactNode as a label
- Update and reuse logic for `getNextPageParam` for infinite queries where the response is a PaginatedResults object
- Change SynapseClient.getEvaluations signature to allow passing any parameters
https://github.com/Sage-Bionetworks/synapse-web-monorepo/assets/17580037/6de1bd04-a55f-47b6-abfb-9e085061481c
=> SWC-6627 - Add EvaluationFinder

packages/synapse-react-client/src/components/EntityViewScopeEditor/EntityViewMaskEditor.stories.tsx, packages/synapse-react-client/src/components/EntityViewScopeEditor/EntityViewMaskEditor.test.tsx, packages/synapse-react-client/src/components/EntityViewScopeEditor/EntityViewMaskEditor.tsx, packages/synapse-react-client/src/components/EntityViewScopeEditor/EntityViewScopeEditor.stories.tsx, packages/synapse-react-client/src/components/EntityViewScopeEditor/EntityViewScopeEditor.test.tsx, packages/synapse-react-client/src/components/EntityViewScopeEditor/EntityViewScopeEditor.tsx, packages/synapse-react-client/src/utils/functions/EntityTypeUtils.ts
https://github.com/Sage-Bionetworks/synapse-web-monorepo/assets/17580037/ce53dc63-ed51-4463-bf89-ad18173b603e
=> SWC-6627 - Add EntityViewMaskEditor and EntityViewScopeEditor

packages/synapse-react-client/src/components/CreateTableViewWizard/TableTypeSelection.test.tsx, packages/synapse-react-client/src/components/CreateTableViewWizard/TableTypeSelection.tsx, packages/synapse-react-client/src/components/CreateTableViewWizard/ViewTypeSelection.test.tsx, packages/synapse-react-client/src/components/CreateTableViewWizard/ViewTypeSelection.tsx, packages/synapse-react-client/src/components/EntityHeaderTable/EntityHeaderTable.tsx, packages/synapse-react-client/src/components/SqlDefinedTableEditor/SqlDefinedTableEditor.test.tsx, packages/synapse-react-client/src/components/SqlDefinedTableEditor/SqlDefinedTableEditor.tsx, packages/synapse-react-client/src/components/TableColumnSchemaEditor/ColumnModelFormFields/DefaultValueField.tsx, packages/synapse-react-client/src/components/WizardChoiceButton/WizardChoiceButton.tsx, packages/synapse-react-client/src/components/WizardChoiceButton/WizardChoiceButtonDescription.tsx, packages/synapse-react-client/src/components/WizardChoiceButton/WizardChoiceButtonGroup.stories.tsx, packages/synapse-react-client/src/components/WizardChoiceButton/WizardChoiceButtonGroup.tsx
- Add WizardChoiceButton
- Add TableTypeSelection, ViewTypeSelection
- Add SqlDefinedTableEditor
- DefaultValueField: fallback to `undefined` in case `value` is null, which is not a valid input value
- EntityHeaderTable: Number of skeleton/loading rows should match number of refs passed
|Feature|Screenshot|
|---|---|
|TableTypeSelection (WizardChoiceButton)| <img width="825" alt="image" src="https://github.com/Sage-Bionetworks/synapse-web-monorepo/assets/17580037/2a44f1f5-c49c-4a40-8245-d2a1f5ecad54"> |
|ViewTypeSelection (WizardChoiceButton)| <img width="825" alt="image" src="https://github.com/Sage-Bionetworks/synapse-web-monorepo/assets/17580037/344cbfaf-3b64-4d88-9345-6ed3843382e9"> |
|SqlDefinedTableEditor| <img width="831" alt="image" …
=> SWC-6627 - Add WizardChoiceButton, TableTypeSelection, ViewTypeSelection, SqlDefinedTableEditor

packages/synapse-react-client/src/assets/mui_components/Other.tsx, packages/synapse-react-client/src/components/GenericCard/GenericCard.tsx, packages/synapse-react-client/src/components/IconList.tsx, packages/synapse-react-client/src/components/IconList/IconList.stories.ts, packages/synapse-react-client/src/style/base/_icons.scss
=> PORTALS-2880: increase size of data icons in generic card

packages/synapse-react-client/src/components/HasAccess/HasAccessV2.integration.test.tsx, packages/synapse-react-client/src/components/HasAccess/HasAccessV2.tsx, packages/synapse-react-client/src/components/SynapseTable/SynapseTableRenderers.tsx
https://github.com/Sage-Bionetworks/synapse-web-monorepo/assets/26949006/5b32f799-2c96-4de8-a0ee-4ec54ffd02b5
https://github.com/Sage-Bionetworks/synapse-web-monorepo/assets/26949006/767506a3-b97d-4477-b9c8-5363a2ebafa5
https://github.com/Sage-Bionetworks/synapse-web-monorepo/assets/26949006/caa0e87f-c298-48ec-8cd1-69e496a23e44
https://github.com/Sage-Bionetworks/synapse-web-monorepo/assets/26949006/8ae58c45-3d7d-4146-b8fc-f82d26fa3c6d
https://github.com/Sage-Bionetworks/synapse-web-monorepo/assets/26949006/c569093e-ba77-41e2-93a2-410e10f0dc86
https://github.com/Sage-Bionetworks/synapse-web-monorepo/assets/26949006/0f8e0fd5-cd7f-4f21-aa38-da97c752bb01
main: 
feature:
=> PORTALS-2768: only show icon, no text in SynapseTable access column

apps/portals/src/configurations/elportal/synapseConfigs/cohortbuilder.ts, packages/synapse-react-client/src/components/QueryVisualizationWrapper/QueryVisualizationWrapper.tsx, packages/synapse-react-client/src/components/QueryWrapperPlotNav/QueryWrapperPlotNav.stories.tsx, packages/synapse-react-client/src/components/QueryWrapperPlotNav/QueryWrapperPlotNav.tsx, packages/synapse-react-client/src/components/SynapseTable/SynapseTable.integration.test.tsx, packages/synapse-react-client/src/components/SynapseTable/SynapseTableRenderers.tsx
PORTALS-2912 
- Add helpConfiguration for table columns
- Surface help text on table column headers
- Add help text to ID column in EL Cohort Builder participants table
=> PORTALS-2912 - Add helpConfiguration for table columns

.eslintrc.cjs, apps/portals/src/portal-components/crc-researcher/ParticipantsBarPlot.tsx, apps/portals/src/portal-components/crc-researcher/StatusLineChart.tsx, apps/portals/src/portal-components/crc-researcher/SurveysCompletedPlots.tsx, package.json, packages/synapse-react-client/src/components/DialogBase.tsx, packages/synapse-react-client/src/components/DownloadCart/RequestDownloadCard.tsx, packages/synapse-react-client/src/components/Forum/DiscussionReply.tsx, packages/synapse-react-client/src/components/Plot/BarPlot.tsx, packages/synapse-react-client/src/components/Plot/DotPlot.tsx, packages/synapse-react-client/src/components/SynapseHomepage/SynapsePriceTableCell.tsx, packages/synapse-react-client/src/components/TimelinePlot/TimelinePlotSpeciesSelector.tsx, packages/synapse-react-client/src/components/widgets/ElementWithTooltip.tsx
This ESLint rule prevents us from specifying new objects as default props in components, which are re-created on each new render cycle, which can lead to performance issues. Note that default primitive values (which are effectively compared by value by React) are unaffected.
I also added the `quiet` option to the root `lint` script, which will cause the command to only output errors instead of errors and warnings, which is more useful in CI.
=> Add error lint rule "react/no-object-type-as-default-prop"

packages/synapse-react-client/src/components/AccessRequirement/AddConditionsForUseButton/AddConditionsForUseButton.integration.test.tsx, packages/synapse-react-client/src/components/HasAccess/HasAccessV2.integration.test.tsx, packages/synapse-react-client/src/components/TableColumnSchemaEditor/TableColumnSchemaEditor.integration.test.tsx, packages/synapse-react-client/src/components/entity/metadata/EntityModal.integration.test.tsx, packages/synapse-react-client/src/components/entity/metadata/EntityModal.tsx, packages/synapse-react-client/src/components/entity/metadata/MetadataTable.integration.test.tsx, packages/synapse-react-client/src/components/entity/page/title_bar/EntityPageTitleBar.integration.test.tsx, packages/synapse-react-client/src/components/entity/page/title_bar/EntityTitleBarVersionInfo.integration.test.tsx, packages/synapse-react-client/src/components/entity/page/title_bar/TitleBarProperties.integration.test.tsx, packages/synapse-react-client/src/mocks/msw/handlers/entityHandlers.ts, packages/synapse-react-client/test/containers/EntityBadgeIcons.integration.test.tsx
PORTALS-2817 and PORTALS-2818
- Add confirmation dialog when closing the annotations editor
- Expose new prop `onEditModeChanged` and synchronize with `useEffect`. Will be used to toggle `GlobalApplicationState.setIsEditing` in SWC
- Improve modal title
- Remove weird cancel button that turns into the confirm cancel button
=> PORTALS-2817, PORTALS-2818 - Fixes for EntityModal (Annotation Editor v2)

packages/synapse-react-client/src/components/widgets/facet-nav/FacetNavPanel.tsx, packages/synapse-react-client/src/components/widgets/facet-nav/PlotsContainer.tsx
Temporary improvement for PORTALS-2916
Also fix an issue where facets would appear full-width instead of in a grid
=> PORTALS-2916 - Temporarily simplify the colors used in facet plots until the palette is improved

packages/synapse-react-client/src/components/dataaccess/AccessApprovalsTable.integration.test.tsx, packages/synapse-react-client/src/components/dataaccess/AccessApprovalsTable.tsx, packages/synapse-react-client/src/mocks/MockAccessApprovals.ts
Fix a case where `fetchNextPage` was never called, and fixed tests that made it seem like this worked.
I don't think this significantly impacted production, I think few users (if any) have enough approvals to hit the page limit (which I think is 50).
=> Fix issue where pagination did not work for the AccessApprovalsTable

apps/SageAccountWeb/src/App.tsx, apps/SageAccountWeb/src/AppInitializer.tsx, apps/SageAccountWeb/src/components/OAuthClientManagementPage.tsx, apps/SageAccountWeb/src/components/PersonalAccessTokensPage.tsx, apps/SageAccountWeb/src/components/ProfileAvatar.tsx, apps/SageAccountWeb/src/components/SageResourcesPage.tsx, apps/SageAccountWeb/src/components/SourceApp.tsx, apps/SageAccountWeb/src/components/useSourceApp.tsx, apps/SageAccountWeb/src/components/useSourceAppConfigs.tsx, packages/synapse-react-client/src/components/OAuthClientManagement/OAuthManagement.integration.test.tsx, packages/synapse-react-client/src/components/OAuthClientManagement/OAuthManagement.tsx
- Store SourceAppConfig in context to apply a particular SourceApp + Theme to an entire subtree
- Use synapse.org theme for OAuthClientManagementPage and PersonalAccessTokensPage
- Clean up related effects between `useSourceApp` and `AppInitializer` and put them in the new `SourceAppProvider
=> PORTALS-2670 - Use Synapse theme/config for PersonalAccessToken, OAuth2 Client pages

packages/synapse-react-client/src/components/AccessRequirementList/AccessRequirementList.stories.tsx, packages/synapse-react-client/src/components/AccessRequirementList/RequirementItem/SelfSignAccessRequirementItem.stories.tsx, packages/synapse-react-client/src/components/AccessRequirementList/RequirementItem/SelfSignAccessRequirementItem.tsx, packages/synapse-react-client/src/components/AccessRequirementList/RequirementItem/UnmanagedACTAccessRequirementItem.stories.tsx, packages/synapse-react-client/src/components/ChallengeRegisterButton/ChallengeRegisterButton.tsx, packages/synapse-react-client/src/components/ChallengeSubmission/ChallengeSubmission.tsx, packages/synapse-react-client/src/components/ChallengeTeamWizard/ChallengeTeamWizard.test.tsx, packages/synapse-react-client/src/components/ChallengeTeamWizard/ChallengeTeamWizard.tsx, packages/synapse-react-client/src/components/GoogleMap/GoogleMap.integration.test.tsx, packages/synapse-react-client/src/components/SynapseTable/SynapseTableCell/SynapseTableCell.integration.test.tsx, packages/synapse-react-client/src/mocks/challenge/mockChallenge.ts, packages/synapse-react-client/src/mocks/msw/handlers.ts, packages/synapse-react-client/src/mocks/msw/handlers/accessRequirementHandlers.ts, packages/synapse-react-client/src/mocks/msw/handlers/challengeHandlers.ts, packages/synapse-react-client/src/mocks/msw/handlers/teamHandlers.ts, packages/synapse-react-client/src/mocks/msw/handlers/userProfileHandlers.ts, packages/synapse-react-client/src/mocks/msw/handlers/wikiHandlers.ts, packages/synapse-react-client/src/mocks/team/mockTeam.ts, packages/synapse-react-client/src/mocks/user/mock_user_profile.ts, packages/synapse-react-client/src/mocks/usergroup/mockUserGroup.ts, packages/synapse-react-client/src/synapse-client/SynapseClient.ts, packages/synapse-react-client/src/synapse-queries/KeyFactory.ts, packages/synapse-react-client/src/synapse-queries/dataaccess/useAccessRequirements.ts, packages/synapse-react-client/src/synapse-queries/team/useTeamMembers.ts, packages/synapse-react-client/src/synapse-queries/user/useGetUserTeams.ts, packages/synapse-types/src/AccessApproval.ts
- Add `CreateAccessApprovalRequest` type, update `AccessApproval` properties to be required if they are always returned by the result object. Update types and objects to fix compile errors
- Rename `useGetUserSubmissionTeamsInfinite` to `useGetUserSubmissionTeams` -- it did not use `useInfiniteQuery`
- Add `useAddMemberToTeam` mutation
- Update cache invalidation for `useDeleteTeamMembership` to include membership status query
- Add useGetAccessRequirementStatuses for querying the current user's status across an array of ARs
- Move team, usergroup mocks to different files
- Add handlers for teams, challenges, access requirements
=> PORTALS-2936 - Update types, mocks, handlers

packages/synapse-react-client/src/components/AccessRequirementList/AccessRequirementList.tsx, packages/synapse-react-client/src/components/ChallengeDetailPage/ChallengeDetailPage.stories.ts, packages/synapse-react-client/src/components/ChallengeDetailPage/ChallengeDetailPage.tsx, packages/synapse-react-client/src/components/ChallengeRequirementsModal/ChallengeRequirementsModal.integration.test.tsx, packages/synapse-react-client/src/components/ChallengeRequirementsModal/ChallengeRequirementsModal.tsx, packages/synapse-react-client/src/components/ChallengeTeamWizard/ChallengeTeamWizard.tsx
See PORTALS-2936
- Add ChallengeRequirementsModal, which shows AccessRequirements. Once all ARs have been met, the user can 'register' by clicking the button to join the participant team
- Update ChallengeDetailPage to use the new ChallengeRequirementsModal instead of AccessRequirementList.
- Fix issue where closing the AR modal without accepting would still trigger joining the participant team
- Fix issue where the ChallengeTeamWizard would be shown even if the user was a member of the participant team.
https://github.com/Sage-Bionetworks/synapse-web-monorepo/assets/17580037/df414b44-21b9-48d4-ad8c-ec187d88df7e
=> PORTALS-2936 - Add new ChallengeRequirementsModal

packages/synapse-react-client/src/components/AccessRequirementList/ManagedACTAccessRequirementRequestFlow/ResearchProjectForm/ResearchProjectForm.tsx, packages/synapse-react-client/src/components/ChallengeDataDownload/ChallengeDataTable.tsx, packages/synapse-react-client/src/components/ChallengeSubmission/ChallengeSubmission.tsx, packages/synapse-react-client/src/components/ChallengeSubmission/ChallengeSubmissionStepper.tsx, packages/synapse-react-client/src/components/ChallengeSubmission/SubmissionDirectoryList.tsx, packages/synapse-react-client/src/components/ChallengeTeamWizard/ChallengeTeamWizard.tsx, packages/synapse-react-client/src/components/EntityFinder/details/view/DetailsView.tsx, packages/synapse-react-client/src/components/StepperDialog/StepperDialog.stories.tsx, packages/synapse-react-client/src/components/StepperDialog/StepperDialog.tsx, packages/synapse-react-client/src/synapse-client/SynapseClient.ts, packages/synapse-react-client/src/synapse-queries/KeyFactory.ts, packages/synapse-react-client/src/synapse-queries/entity/useEntity.ts, packages/synapse-react-client/src/synapse-queries/subscription/useSubscription.ts, packages/synapse-react-client/src/synapse-queries/user/useUserBundle.ts
- Removed all uses of `onSuccess`, `onSettled`, `onError` query options, which are removed in @tanstack/react-query v5
- Clean up a few cases where we should be using the QueryKey KeyFactory
=> SWC-6545 - Refactor to remove deprecated query options

packages/synapse-react-client/src/components/AccessRequirementList/ManagedACTAccessRequirementRequestFlow/DataAccessRequestAccessorsFilesForm/DataAccessRequestAccessorsFilesForm.test.tsx, packages/synapse-react-client/src/components/AccessRequirementList/ManagedACTAccessRequirementRequestFlow/ResearchProjectForm/ResearchProjectForm.test.tsx, packages/synapse-react-client/src/components/Authentication/Login.test.tsx, packages/synapse-react-client/src/components/ChallengeTeamWizard/ChallengeTeamWizard.test.tsx, packages/synapse-react-client/src/components/CreateTableViewWizard/CreateTableViewWizard.integration.test.tsx, packages/synapse-react-client/src/components/DownloadCart/DownloadListTable.test.tsx, packages/synapse-react-client/src/components/EvaluationFinder/EvaluationFinder.test.tsx, packages/synapse-react-client/src/components/FeaturedToolsList/FeaturedToolsList.test.tsx, packages/synapse-react-client/src/components/Forum/ForumPage.integration.test.tsx, packages/synapse-react-client/src/components/Forum/ForumPage.stories.ts, packages/synapse-react-client/src/components/HasAccess/HasAccessV2.integration.test.tsx, packages/synapse-react-client/src/components/SynapseTable/SynapseTable.integration.test.tsx, packages/synapse-react-client/src/components/TimelinePlot/TimelinePlotSpeciesSelector.test.tsx, packages/synapse-react-client/src/components/dataaccess/AccessRequestSubmissionTable.integration.test.tsx, packages/synapse-react-client/src/mocks/discussion/mock_discussion.ts, packages/synapse-react-client/src/mocks/msw/handlers/discussionHandlers.ts, packages/synapse-react-client/src/mocks/msw/handlers/subscriptionHandlers.ts, packages/synapse-react-client/src/synapse-client/SynapseClient.ts, packages/synapse-react-client/src/synapse-queries/forum/useForum.ts, packages/synapse-react-client/src/testutils/TestingLibraryUtils.tsx
- Modify many tests so they pass before/after react-query upgrade. Most cases just required waiting for the DOM to update before inspecting elements
- Change test wrapper to merge prop overrides with defaults instead of replacing
- Change ForumPage tests to use MSW
- Configure handlers for discussions and subscriptions
- Fix return type for `SynapseClient.createMembershipInvitation`, `SynapseClient.createMembershipRequest`
=> SWC-6545 - Prep tests for react-query upgrade

packages/synapse-react-client/src/components/ChallengeTeamWizard/ChallengeTeamSearch.tsx
PORTALS-2937
The input field submits the `form` component on enter. This search field doesn't do anything when pressing enter (the search updates on keypress), so I don't think a `form` element is really necessary here
=> PORTALS-2937

packages/synapse-react-client/src/components/CardContainer/CardContainer.tsx, packages/synapse-react-client/src/components/CardContainerLogic/CardContainerLogic.stories.ts, packages/synapse-react-client/src/style/components/row_renderers/_observation-card.scss
card | main | feature
observation | <img width="552" alt="main_observation_cards" src="https://github.com/Sage-Bionetworks/synapse-web-monorepo/assets/26949006/2914cfc9-bf37-4038-8516-9850472968f9"> | <img width="549" alt="feature_observation_cards" src="https://github.com/Sage-Bionetworks/synapse-web-monorepo/assets/26949006/e81d26b4-48f8-41d3-8033-a909e9bf724b">
dataset | <img width="551" alt="main_dataset_cards" src="https://github.com/Sage-Bionetworks/synapse-web-monorepo/assets/26949006/9292bd5a-e0ce-4074-be0a-7c521abf2842"> | <img width="551" alt="feature_dataset_cards" src="https://github.com/Sage-Bionetworks/synapse-web-monorepo/assets/26949006/a8505827-b6a7-4a75-a0db-01894af742c4"> 
study / publication | <img width="554" alt="main_study_publication_cards" …
=> PORTALS-2915: set max width for observation cards and left align View More button

apps/portals/src/portal-components/DetailsPage/_DetailsPage.scss
Digital Health detail pages are not overflowing --
https://github.com/Sage-Bionetworks/synapse-web-monorepo/assets/26949006/2c0ea938-dd3c-4a91-9005-0ec359f0e35e
but TOC is still sticky in Challenge portal -- 
https://github.com/Sage-Bionetworks/synapse-web-monorepo/assets/26949006/0d62d9b1-1ed4-4c48-a5cf-d9567b2bbf44
=> PORTALS-2982: make TOC 'sticky', but prevent overflow in digitalhealth detail pages

packages/synapse-react-client/src/components/CertificationQuiz/CertificationQuiz.integration.test.tsx, packages/synapse-react-client/src/components/MissingQueryResultsWarning/MissingQueryResultsWarning.tsx, packages/synapse-react-client/src/components/OAuthClientManagement/CreateOAuthClient.integration.test.tsx, packages/synapse-react-client/src/components/QueryVisualizationWrapper/NoContentPlaceholder.tsx, packages/synapse-react-client/src/components/QueryVisualizationWrapper/QueryVisualizationWrapper.tsx, packages/synapse-react-client/src/components/SchemaDrivenAnnotationEditor/SchemaDrivenAnnotationsEditor.integration.test.tsx, packages/synapse-react-client/src/components/StorybookComponentWrapper.tsx, packages/synapse-react-client/src/components/SynapseTable/SynapseTable.integration.test.tsx, packages/synapse-react-client/src/components/SynapseTable/SynapseTable.tsx, packages/synapse-react-client/src/components/SynapseTable/datasets/DatasetItemsEditor.integration.test.tsx, packages/synapse-react-client/src/components/SynapseTable/datasets/DatasetItemsEditor.tsx, packages/synapse-react-client/src/components/ToastMessage/ToastMessage.tsx, packages/synapse-react-client/src/components/download_list/TableQueryDownloadConfirmation.test.tsx, packages/synapse-react-client/src/synapse-queries/QueryFilterUtils.test.ts, packages/synapse-react-client/src/synapse-queries/QueryFilterUtils.ts, packages/synapse-react-client/src/synapse-queries/entity/useEntity.ts, packages/synapse-react-client/src/synapse-queries/entity/useExportToCavatica.test.tsx, packages/synapse-react-client/src/utils/functions/EntityTypeUtils.ts
- Change invalidation logic so table query data is reset (cached data is removed and listeners are notified), fixing SWC-6722
- Do not `await` retrieval of new table query data after an update that triggers cache invalidation, fixing SWC-6674
- NoContentPlaceholder component should be shown when query offset is null/undefined, fixing SWC-6725
- Change Dataset editor toast messages to only show one prompt to save at a time, and hide the toast when the user initiates the request to save changes.
=> SWC-6725, SWC-6722, SWC-6674 - Fix table cache issues

packages/synapse-react-client/src/components/MissingQueryResultsWarning/MissingQueryResultsWarning.integration.test.tsx, packages/synapse-react-client/src/components/MissingQueryResultsWarning/MissingQueryResultsWarning.tsx
Do not show MissingQueryResultsWarning if the visible result count is greater than the number of items. The mismatch should never happen, but this safeguards against a case where one of the data sources is outdated.
=> SWC-6727 / PLFM-8326

apps/portals/src/configurations/genie/synapseConfigs/genieBPCData.ts, apps/portals/src/configurations/genie/synapseConfigs/genieData.ts
since it might be confused with the dataset version
=> GENIE: set the visible column count to hide the currentVersion column

packages/synapse-react-client/src/components/ChallengeSubmission/AvailableEvaluationQueueList.stories.tsx, packages/synapse-react-client/src/components/ChallengeSubmission/AvailableEvaluationQueueList.test.tsx, packages/synapse-react-client/src/components/ChallengeSubmission/AvailableEvaluationQueueList.tsx, packages/synapse-react-client/src/mocks/entity/mockEvaluationQueue.ts
=> SWC-6753: prevent Available Evaluation Lists from collapsing twice

apps/portals/src/configurations/cancercomplexity/synapseConfigs/mc2supplement.ts
Following work by @jay-hodgson to add a hidden page to CCKP to share results from the M2 Digital Pathology supplement, this PR makes a minor adjustment to also preview the image thumbnail as well as the fuse mask.
This is an initial PR to scope a further change to this page to optimise for digital pathology qc data sharing.
=> Add thumbnail column preview to mc2supplement.ts

packages/markdown-it-synapse/package.json
Attempt to trigger auto-release without changing version
=> Bump markdown-it-synapse to v1.1.14

packages/markdown-it-synapse/package.json
Will cause an error, but allows triggering an automatic release in the next bump
=> Revert markdown-it-synapse version to 1.1.13

apps/SageAccountWeb/src/components/ResetPassword.tsx, apps/SageAccountWeb/src/style/_core.scss, packages/synapse-react-client/src/components/ChangePassword/ChangePassword.tsx, packages/synapse-react-client/src/components/ChangePassword/ChangePasswordWithToken.integration.test.tsx, packages/synapse-react-client/src/components/ChangePassword/ChangePasswordWithToken.stories.tsx, packages/synapse-react-client/src/components/ChangePassword/ChangePasswordWithToken.tsx, packages/synapse-react-client/src/components/ChangePassword/index.ts, packages/synapse-react-client/src/components/ChangePassword/useChangePasswordFormState.tsx, packages/synapse-react-client/src/synapse-client/SynapseClient.ts, packages/synapse-react-client/src/synapse-queries/auth/useChangePassword.ts
- Add component to support changing password with a reset token
- Refactor existing ChangePassword component to share logic for 2FA via custom hook
=> SWC-6766 - Add ChangePasswordWithToken component, use in SageAccountWeb

packages/synapse-react-client/src/components/EntitySubjectsSelector/EntitySubjectsSelector.stories.tsx, packages/synapse-react-client/src/components/EntitySubjectsSelector/EntitySubjectsSelector.test.tsx, packages/synapse-react-client/src/components/EntitySubjectsSelector/EntitySubjectsSelector.tsx, packages/synapse-react-client/src/components/EntitySubjectsSelector/index.ts, packages/synapse-react-client/src/components/SetAccessRequirementCommonFields/SetAccessRequirementCommonFields.stories.tsx, packages/synapse-react-client/src/components/SetAccessRequirementCommonFields/SetAccessRequirementCommonFields.test.tsx, packages/synapse-react-client/src/components/SetAccessRequirementCommonFields/SetAccessRequirementCommonFields.tsx, packages/synapse-react-client/src/components/SetAccessRequirementCommonFields/index.ts, packages/synapse-react-client/src/components/SetBasicAccessRequirementFields/AccessRequirementWikiInstructions.test.tsx, packages/synapse-react-client/src/components/TeamSubjectsSelector/TeamBadgeOrError.tsx, packages/synapse-react-client/src/components/TeamSubjectsSelector/TeamSubjectsSelector.stories.tsx, packages/synapse-react-client/src/components/TeamSubjectsSelector/TeamSubjectsSelector.test.tsx, packages/synapse-react-client/src/components/TeamSubjectsSelector/TeamSubjectsSelector.tsx, packages/synapse-react-client/src/components/TeamSubjectsSelector/index.ts, packages/synapse-react-client/src/mocks/mockAccessRequirements.ts, packages/synapse-react-client/src/mocks/msw/handlers/accessRequirementHandlers.ts, packages/synapse-react-client/src/mocks/msw/handlers/teamHandlers.ts, packages/synapse-react-client/src/synapse-client/SynapseClient.ts, packages/synapse-react-client/src/synapse-queries/dataaccess/useAccessRequirements.ts, packages/synapse-react-client/src/testutils/MarkdownSynapseUtils.ts
type | SWC | SRC
create entity AR | <img width="860" alt="SWC-6730_createEntityAR_SWC" src="https://github.com/Sage-Bionetworks/synapse-web-monorepo/assets/26949006/5ce36223-18af-4bbb-96a9-216ae90f2fcc"> | <img width="711" alt="SWC-6730_createEntityAR_SRC" src="https://github.com/Sage-Bionetworks/synapse-web-monorepo/assets/26949006/cd13d3f1-e69b-4df2-a103-807fc5bb5f0b">
create team AR | <img width="844" alt="SWC-6730_createTeamAR_SWC" src="https://github.com/Sage-Bionetworks/synapse-web-monorepo/assets/26949006/f6b2143b-d729-4493-8a33-2b8ca658eb52"> | <img width="716" alt="SWC-6730_createTeamAR_SRC" src="https://github.com/Sage-Bionetworks/synapse-web-monorepo/assets/26949006/565343ae-f1d3-420d-8f4e-b6b3ae2a1345">
edit entity AR | <img width="838" …
=> SWC-6730c: add step to set common AR fields

apps/synapse-oauth-signin/src/test/App.test.tsx, packages/synapse-react-client/src/utils/hooks/useDetectSSOCode.test.ts, packages/synapse-react-client/src/utils/hooks/useDetectSSOCode.ts
Should fix PORTALS-3073 where we should return an arbitrary `state` searchParam to an OAuth2 client that is using Synapse as an OIDC identity provider
=> PORTALS-3073 - do not parse state during OAuth sign in

packages/synapse-react-client/src/components/EntityHeaderTable/EntityHeaderTable.tsx, packages/synapse-react-client/src/components/EntityHeaderTable/EntityHeaderTableCellRenderers.tsx, packages/synapse-react-client/src/components/Forum/ForumPage.stories.ts, packages/synapse-react-client/src/components/Forum/ForumPage.tsx, packages/synapse-react-client/src/components/Forum/ForumTable.tsx, packages/synapse-react-client/src/components/OAuthClientManagement/OAuthManagement.tsx, packages/synapse-react-client/src/components/SynapseTable/SynapseTableRenderers.tsx, packages/synapse-react-client/src/components/styled/ColumnHeader.tsx, packages/synapse-react-client/src/components/styled/StyledTableContainer.tsx, packages/synapse-react-client/src/components/trash/TrashCanList.integration.test.tsx, packages/synapse-react-client/src/components/trash/TrashCanList.tsx, packages/synapse-react-client/src/style/components/_discussion-forum.scss, packages/synapse-react-client/src/synapse-queries/trash/useTrashCan.ts
SynapseTable
- Extract column header component for reuse
EntityHeaderTable
- Extract table styles into styled component for reuse
TrashCanList, OAuthManagement, ForumTable
- Refactor to use react-table and remove reference to `'react-bootstrap'`
|Component|Screenshot|
|---|---|
|TrashCanList|![image](https://github.com/Sage-Bionetworks/synapse-web-monorepo/assets/17580037/8e13ce5c-4cf9-4735-841f-4c5440d176d5)|
|OAuthManagement| ![image](https://github.com/Sage-Bionetworks/synapse-web-monorepo/assets/17580037/e9610bea-d272-4f30-a26f-cf4921ba1443) |
|ForumPage|![image](https://github.com/Sage-Bionetworks/synapse-web-monorepo/assets/17580037/860e7d8c-d287-4549-b820-226e890c3d2b)|
|SynapseTable (affected by refactoring)|![image](https://github.com/Sage-Bionetworks/synapse-web-monorepo/assets/1 …
=> PORTALS-2651 - Replace a few Bootstrap tables with custom styling + TanStack React Table

packages/synapse-react-client/src/synapse-client/HttpClient.ts
Fixes SWC-6777
The encoding issue occurred on data submission, so this will not fix historical data.
=> SWC-6777 - Specify UTF-8 encoding in Content-Type on POST/PUT

apps/portals/src/configurations/cancercomplexity/routesConfig.ts, apps/portals/src/configurations/cancercomplexity/synapseConfigs/grants.ts
More information about the proposed feature in the parent ticket [here](https://sagebionetworks.jira.com/browse/CPO-943)
CC: @aclayton555 
* Add two secondary labels to the grant card: NIH Reporter Link, Grant Start Date
* Add new "Related Educational Resources" section
Educational resource with no associating grant number:
Educational resource with associating grant number + updated grant Details Page:
=> CPO-943: Update Grant card + details page

packages/synapse-react-client/src/utils/hooks/useLogin.test.tsx, packages/synapse-react-client/src/utils/hooks/useLogin.ts
Fix case where trailing hash was transformed and then added to the twoFaToken
=> SWC-6985 - Fix bug where Safari users + 2FA cannot log in / reset 2FA

apps/portals/cancercomplexity/src/config/synapseConfigs/publications.ts
* configure the `doi` column to render as a link on the portal (otherwise, "https" is seen)
**Before**
**After**
=> CPO-fix: configure `doi` column as a link

packages/synapse-react-client/src/components/QueryContext/QueryContext.tsx, packages/synapse-react-client/src/components/QueryWrapper/QueryWrapper.tsx, packages/synapse-react-client/src/components/QueryWrapper/useQueryWrapperPaginationControls.test.tsx, packages/synapse-react-client/src/components/widgets/query-filter/EnumFacetFilter/EnumFacetFilter.tsx, packages/synapse-react-client/src/utils/hooks/useImmutableTableQuery/useImmutableTableQuery.test.tsx, packages/synapse-react-client/src/utils/hooks/useImmutableTableQuery/useImmutableTableQuery.ts, packages/synapse-react-client/src/utils/hooks/useImmutableTableQuery/useTableQueryReducer.ts
Tracking component rerenders demo:
Before:
https://github.com/user-attachments/assets/e48d0458-bb1f-44e7-ad91-c3a90a68fe73
After:
https://github.com/user-attachments/assets/7a0699b0-644d-47ff-8b13-84100723167d
=> PORTALS-2970 - allow resetting debounce timer without recreating query

apps/synapse-portal-framework/sitemap/generate-sitemap.cjs
sitemap.xml is currently broken.  Here's an example entry from the NF sitemap.xml, which is an invalid route and invalid URL:
```
<url>
<loc>https://"nf".synapse.org/DetailsPage?abbreviation=GFF</loc>
<lastmod>2024-07-03T16:12:31.279Z</lastmod>
</url>
```
=> PORTALS-3199: external recommendation to fix sitemap.xml to fix SEO

.github/workflows/build-test.yml
Back in February, GitHub increased the `ubuntu-latest` runner from 2 cores to 4 cores. The only difference between the public runner and the current one is the SSD volume size, which we don't need.
=> Use ubuntu-latest for test

.github/actions/pnpm-setup-action/action.yml, .github/workflows/build-test.yml, .gitignore, apps/SageAccountWeb/package.json, apps/synapse-oauth-signin/package.json, apps/synapse-portal-framework/package.json, package.json, packages/synapse-react-client/README.md, packages/synapse-react-client/package.json, packages/vite-config/src/vitest-config.ts, pnpm-lock.yaml
Save the Nx build cache into a GitHub actions cache to reduce the total number of builds. 
The motivation is that when building the new `openapi-generator`-based Synapse client, I am frequently seeing 403s when the openapi-generator NPM package attempts to pull the openapi-generator JAR from Maven central. An issue to track this is here: https://github.com/OpenAPITools/openapi-generator-cli/issues/802 , but we can reduce the number of times this can fail by storing the Nx cache in a GitHub actions cache.
Note that Nx warns that this may leave us susceptible to cache poisoning: https://nx.dev/troubleshooting/unknown-local-cache , but I think if we only use this cache for checks, and not for deployment, this is low risk.
This should also reduce the total number of minutes of GitHub actions …
=> Upgrade Nx, set up Nx cache sharing for CI job steps

apps/SageAccountWeb/src/components/AccountSettings.tsx
Rejection reasons often have new lines, so update to use `whitespace: pre-line` style
=> SWC-6923 - Fix formatting of validation rejection reasons

apps/SageAccountWeb/src/hooks/useMaybeRedirectToSignTermsOfService.ts
useMaybeRedirectToSignTermsOfService should return a `useState` variable to trigger a re-render, rather than the current value of a ref.
This fixes SWC e2e tests. 10/10 passed in chromium & ff, 9/10 passed in webkit with one timeout
=> fix cases where you may not be redirected on the root route

apps/SageAccountWeb/src/components/SignUpdatedTermsOfUsePage.tsx, packages/synapse-react-client/src/utils/AppUtils/AppUtils.ts
redirect within OneSage may have happened without triggering a page reload
=> SWC-7127 - edge case

packages/synapse-react-client/src/utils/hooks/useUploadFileEntity/useCreateFolderPath.test.ts, packages/synapse-react-client/src/utils/hooks/useUploadFileEntity/useCreateFolderPath.ts, packages/synapse-react-client/src/utils/hooks/useUploadFileEntity/useCreatePathsAndGetParentId.test.ts, packages/synapse-react-client/src/utils/hooks/useUploadFileEntity/useCreatePathsAndGetParentId.ts, packages/synapse-react-client/src/utils/hooks/useUploadFileEntity/usePrepareFileEntityUpload.test.ts, packages/synapse-react-client/src/utils/hooks/useUploadFileEntity/usePrepareFileEntityUpload.ts, packages/synapse-react-client/src/utils/hooks/useUploadFileEntity/useTrackFileUploads.test.ts, packages/synapse-react-client/src/utils/hooks/useUploadFileEntity/useTrackFileUploads.ts, packages/synapse-react-client/src/utils/hooks/useUploadFileEntity/useUploadFileEntities.test.ts, packages/synapse-react-client/src/utils/hooks/useUploadFileEntity/useUploadFileEntities.ts
- Handle case where a FileEntity is directly updated (e.g. from the entity page) and the user should not be prompted.
- Minor refactoring
=> SWC-7064 - Handle case where a FileEntity is directly updated

packages/synapse-react-client/src/synapse-client/SynapseClient.ts, packages/synapse-react-client/src/utils/AppUtils/AppUtils.ts
When the accounts site will be created, the cookie will be set on a domain like `accounts.dev.sagebase.org`. Manually set the domain to `.dev.sagebase.org` so it will work on `portal-dev.dev.sagebase.org`.
=> fix cookie on dev domain

packages/synapse-react-client/src/synapse-queries/KeyFactory.ts, packages/synapse-react-client/src/synapse-queries/entity/useEntity.ts, packages/synapse-react-client/src/utils/hooks/useUploadFileEntity/useCreateFolderPath.test.ts, packages/synapse-react-client/src/utils/hooks/useUploadFileEntity/useCreateFolderPath.ts
Improves the performance of the case where a folder with many items is uploaded by using the react-query cache when looking up whether an entity exists, and fetching it to check if it's a folder.
For example, if you upload these files:
```
folder_1/folder_2/.../folder_m/file_1.txt
folder_1/folder_2/.../folder_m/file_2.txt
...
folder_1/folder_2/.../folder_m/file_n.txt
```
without a cache, we would call `POST entity/child` and `GET /entity/id` $m * n$ times.
With the cache, these will only be called $m$ times.
=> SWC-7064 - Optimize creating many dirs by using cache for entity lookup

apps/portals/nf/src/pages/OrganizationDetailsPage/OrganizationDetailsPage.tsx, apps/synapse-portal-framework/src/App.tsx, apps/synapse-portal-framework/src/utils/useDocumentTitleFromRoutes.ts, packages/markdown-it-synapse-table/package.json, packages/synapse-client/package.json, packages/synapse-react-client/package.json, packages/synapse-types/package.json, packages/vite-config/package.json
- fix NF portal OrganizationDetailsPage to pass searchParams along since there are multiple lookup keys
- add hook to dynamically set document.title
- add clean jobs that remove tsbuildinfo
=> PORTALS-3195

apps/portals/nf/src/pages/DatasetDetailsPage.tsx, apps/portals/nf/src/pages/InitiativeDetailsPage.tsx, apps/portals/nf/src/pages/OrganizationDetailsPage/OrganizationDetailsPage.tsx, apps/synapse-portal-framework/src/components/DetailsPage/DetailsPage.tsx, apps/synapse-portal-framework/src/components/DetailsPage/DetailsPageDocumentMetadata.tsx, apps/synapse-portal-framework/src/components/Explore/ExploreWrapper.tsx, apps/synapse-portal-framework/src/components/Explore/ExploreWrapperTabs.tsx, apps/synapse-portal-framework/src/types/portal-util-types.ts, apps/synapse-portal-framework/src/utils/useSetCanonicalUrl.ts
...and a few details pages
One hypothesis is that Google is not indexing pages in our portals because they do not identify them as unique. Adding the canonical URL to the document head could help Google dedifferentiate duplicate pages, and also identify unique pages.
=> PORTALS-3195 - add canonical URL tags to Explore pages 

apps/portals/arkportal/tsconfig.json, apps/portals/bsmn/tsconfig.json, apps/portals/cancercomplexity/tsconfig.json, apps/portals/challengeportal/tsconfig.json, apps/portals/digitalhealth/tsconfig.json, apps/portals/elportal/tsconfig.json, apps/portals/genie/tsconfig.json, apps/portals/nf/tsconfig.json, apps/portals/stopadportal/tsconfig.json, apps/synapse-portal-framework/tsconfig.json
- Fix erroneous tsconfig paths that caused one package to use the build artifacts and another to use source code, leading to the app using 2 different copies of the same React context
- Fill in missing tsconfig references in portals projects
=> PORTALS-3344 - fix reference issue causing mismatched artifact usage

apps/SageAccountWeb/src/App.scss
add a min height to the logo container to prevent the layout from shifting when the logo loads
=> SageAccountWeb: add a min height to the logo container

packages/synapse-client/README.md, packages/synapse-client/package.json
Fetching the list of versions queries search.maven.org, which can experience downtime. This request is unnecessary to run unless changing the version of the generator tool.
=> Remove openapi-generator version configuration step

packages/synapse-react-client/src/components/CardContainerLogic/CardContainerLogic.tsx, packages/synapse-react-client/src/components/FeaturedDataTabs/QueryPerFacetPlotsCard.tsx, packages/synapse-react-client/src/components/FeaturedDataTabs/SingleQueryFacetPlotsCards.tsx, packages/synapse-react-client/src/components/QueryWrapperPlotNav/QueryWrapperPlotNav.tsx, packages/synapse-react-client/src/components/StandaloneQueryWrapper/StandaloneQueryWrapper.tsx
- QueryWrapper component should always be reset via key when the initial query changes.
See https://legacy.reactjs.org/blog/2018/06/07/you-probably-dont-need-derived-state.html#recommendation-fully-uncontrolled-component-with-a-key
=> PORTALS-3364 - Fix QueryWrapper stale state bug

packages/synapse-react-client/src/components/UserProfileLinks/UserProfileLinks.tsx
Jira ticket: https://sagebionetworks.jira.com/browse/SWC-7172
Increase height:
=> SWC-7172: SRC UserProfileLinks updates on mobile

packages/synapse-react-client/src/components/ChangePassword/ChangePassword.stories.tsx, packages/synapse-react-client/src/components/RecentPublicationsGrid/RecentPublicationsGrid.stories.tsx, packages/synapse-react-client/src/components/StorybookComponentWrapper.tsx
Add `withRouter` parameter to Storybook to optionally configure a router per-story
Fix the ChangePassword stories by adding a memory router
=> Fix router issue in Storybook

packages/synapse-react-client/src/style/base/_core.scss
Jira: https://sagebionetworks.jira.com/browse/SWC-7221
=> SWC-7221: SRC UserCards don't stretch for 2-column grid layout on some devices

packages/synapse-react-client/src/components/FeaturedResearch/FeaturedResearch.test.tsx, packages/synapse-react-client/src/components/FeaturedResearch/FeaturedResearch.tsx
In a thread with Milan and Adam, we have discussed removing tags and affiliation like so:
=> FeaturedResearch Component Update: Removing Tags and Affiliation

packages/synapse-react-client/src/components/entity/page/title_bar/EntityPageTitleBar.tsx, packages/synapse-react-client/src/components/menu/ComplexMenu.tsx
Jira ticket: https://sagebionetworks.jira.com/browse/SWC-7186?atlOrigin=eyJpIjoiZmRhODg4MjIyYmU3NGRhYjk1ODU5MTcxNDM1NTg2YmIiLCJwIjoiaiJ9
=> SWC-7186: SRC EntityPageTitleBar updates on mobile

packages/synapse-react-client/src/components/DownloadCart/ActionRequiredCard/ActionRequiredCard.tsx
SWC-7222 Make the ActionRequiredCardContainer a single column on mobile to prevent horizontal overflow
=> SWC-7222 Fix mobile Access Action Required tab in Download Car

packages/synapse-react-client/package.json, packages/synapse-react-client/src/components/Evaluation/EvaluationCard.test.tsx, packages/synapse-react-client/src/components/Evaluation/EvaluationCard.tsx, packages/synapse-react-client/src/components/Evaluation/EvaluationEditor.tsx, packages/synapse-react-client/src/components/Evaluation/EvaluationEditorPage.tsx, packages/synapse-react-client/src/components/Evaluation/EvaluationRoundEditor.test.tsx, packages/synapse-react-client/src/components/Evaluation/EvaluationRoundEditor.tsx, packages/synapse-react-client/src/components/Evaluation/EvaluationRoundEditorDropdown.tsx, packages/synapse-react-client/src/components/Evaluation/EvaluationRoundEditorList.test.tsx, packages/synapse-react-client/src/components/Evaluation/EvaluationRoundEditorList.tsx, packages/synapse-react-client/src/components/Evaluation/round_limits/EvaluationRoundLimitOptions.tsx, packages/synapse-react-client/src/components/Evaluation/round_limits/EvaluationRoundLimitOptionsList.tsx, packages/synapse-react-client/src/style/components/evaluation_queue/_evaluation-editor.scss, packages/synapse-react-client/src/style/components/evaluation_queue/_evaluation-round-editor.scss, pnpm-lock.yaml
- Remove react-bootstrap from Evaluations components
- Remove JestMockPromise
=> PORTALS-2651 - Evaluations

packages/synapse-react-client/src/components/ChallengeSubmission/AvailableEvaluationQueueList.stories.tsx, packages/synapse-react-client/src/components/EntityFinder/details/view/DetailsView.test.tsx, packages/synapse-react-client/src/components/EntityFinder/details/view/table/EntityFinderVersionCell.tsx, packages/synapse-react-client/src/components/Markdown/MarkdownEditor.tsx, packages/synapse-react-client/src/components/ProvenanceGraph/ProvenanceGraph.stories.tsx, packages/synapse-react-client/src/components/ProvenanceGraph/ProvenanceGraph.tsx, packages/synapse-react-client/src/components/QuerySortSelector.tsx, packages/synapse-react-client/src/components/SubsectionRowRenderer/SubsectionRowRenderer.tsx, packages/synapse-react-client/src/components/SynapseForm/SynapseFormWrapper.stories.tsx, packages/synapse-react-client/src/components/SynapseNavDrawer/SynapseNavDrawer.tsx, packages/synapse-react-client/src/components/SynapseTable/datasets/DatasetEditorVersionCell.tsx, packages/synapse-react-client/src/components/SynapseTable/datasets/DatasetItemsEditor.test.tsx, packages/synapse-react-client/src/style/components/_markdown.scss, packages/synapse-react-client/src/style/components/_synapse-nav-drawer.scss, packages/synapse-react-client/src/style/components/synapse_form_wrapper/_synapse-form-wrapper.scss
Replace usages of react-bootstrap across various components
=> PORTALS-2651 - various components

apps/portals/elportal/src/pages/HomePageV2.tsx, apps/synapse-portal-framework/src/components/elportal/ELContributeYourData.tsx, apps/synapse-portal-framework/src/components/elportal/ELGettingStarted.tsx, apps/synapse-portal-framework/src/components/elportal/ELSupportedByNIH.tsx, packages/synapse-react-client/src/components/FeaturedDataTabs/FacetPlotsCard.tsx, packages/synapse-react-client/src/components/FeaturedDataTabs/FeaturedDataTabs.tsx, packages/synapse-react-client/src/components/FeaturedResearch/FeaturedResearch.tsx, packages/synapse-react-client/src/components/GoalsV2/GoalsV2.Desktop.tsx, packages/synapse-react-client/src/components/GoalsV2/GoalsV2.tsx, packages/synapse-react-client/src/components/ImageCardGridWithLinks/ImageCardGridWithLinks.tsx, packages/synapse-react-client/src/components/Plot/UpsetPlot.tsx, packages/synapse-react-client/src/components/PortalFeatureHighlights/PortalFeatureHighlights.tsx, packages/synapse-react-client/src/components/PortalFeaturedPartners/PortalFeaturedPartners.tsx, packages/synapse-react-client/src/components/PortalSectionHeader/PortalSectionHeader.stories.tsx, packages/synapse-react-client/src/components/PortalSectionHeader/PortalSectionHeader.test.tsx, packages/synapse-react-client/src/components/PortalSectionHeader/PortalSectionHeader.tsx, packages/synapse-react-client/src/components/PortalSectionHeader/index.ts, packages/synapse-react-client/src/components/RecentPublicationsGrid/RecentPublicationsGrid.tsx, packages/synapse-react-client/src/components/index.ts
Jira: https://sagebionetworks.jira.com/browse/PORTALS-3405
The majority of the new components used a similar section header so I created a reusable component out of it.
=> PORTALS-3405: Consistent styling and mobile responsiveness review

apps/portals/standards/src/config/synapseConfigs/data.ts, packages/synapse-react-client/src/components/QueryWrapperPlotNav/QueryWrapperPlotNav.tsx, packages/synapse-react-client/src/components/widgets/facet-nav/PlotsContainer.tsx
PORTALS-3410 - Allows portals to create bar charts in addition to pie charts by exposing plotType as a prop to PlotsContainer.
=> PORTALS-3410 - Make plotType customizable

packages/synapse-react-client/src/components/widgets/query-filter/EnumFacetFilter/EnumFacetFilter.stories.tsx, packages/synapse-react-client/src/components/widgets/query-filter/EnumFacetFilter/EnumFacetFilterOption.tsx
SWC-7229 - Use overflowWrap: 'anywhere' to break long strings without spaces or hypens
=> SWC-7229 - Fix overflow on EnumFacetFilter

.github/workflows/deploy-ark-portal.yml, .github/workflows/deploy-bsmn-portal.yml, .github/workflows/deploy-cancercomplexity-portal.yml, .github/workflows/deploy-digitalhealth-portal.yml, .github/workflows/deploy-elite-portal.yml, .github/workflows/deploy-genie-portal.yml, .github/workflows/deploy-nf-portal.yml, .github/workflows/deploy-standards-portal.yml, .github/workflows/deploy-stopad-portal.yml
This PR adds GH workflows deployments for all the portals (AdKnowledge and Challenges already existed).
Don't merge. Need to disable jobs on Jenkins.
=> Add deployment to staging for portals

apps/portals/arkportal/src/config/style/_style_overrides.scss, apps/portals/elportal/src/pages/HomePageV2.tsx, packages/synapse-react-client/src/components/Goals/Goals.tsx, packages/synapse-react-client/src/components/GoalsV2/GoalsV2.Desktop.tsx, packages/synapse-react-client/src/components/GoalsV2/GoalsV2.tsx, packages/synapse-react-client/src/components/styled/EvenlyDistributedWrappedContainer.stories.tsx, packages/synapse-react-client/src/components/styled/EvenlyDistributedWrappedContainer.test.ts, packages/synapse-react-client/src/components/styled/EvenlyDistributedWrappedContainer.tsx, packages/synapse-react-client/src/style/components/_goals.scss
- Update Goals v1 desktop to support layout of 5+ items
- Add new EvenlyDistributedWrappedContainer component to evenly distribute items across multiple flex wrappers such that no row has just one item. I do not believe that these constraints are possible to implement with pure CSS, so this component handles splitting and rendering multiple flex containers to display content in a 'balanced' layout.
Demo:
[Screencast from 02-17-2025 12:36:49 PM.webm](https://github.com/user-attachments/assets/98c81844-6543-4eda-afb3-720d0e7e6368)
Example layout in ARK Portal:
=> PORTALS-3423

apps/SageAccountWeb/src/components/AccountSettings.tsx
PORTALS-3422 - Fix a regression created in [PR1526](https://github.com/Sage-Bionetworks/synapse-web-monorepo/pull/1526) by removing the webhooks menu entry when not in experimental mode.
=> PORTALS-3422 - use showWebhooks to display or hide webhooks menu entry

apps/SageAccountWeb/index.html, apps/SageAccountWeb/src/AppInitializer.tsx, apps/portals/adknowledgeportal/index.html, apps/portals/arkportal/index.html, apps/portals/bsmn/index.html, apps/portals/cancercomplexity/index.html, apps/portals/challengeportal/index.html, apps/portals/digitalhealth/index.html, apps/portals/elportal/index.html, apps/portals/genie/index.html, apps/portals/nf/index.html, apps/portals/standards/index.html, apps/portals/stopadportal/index.html, apps/synapse-oauth-signin/src/AppInitializer.tsx, packages/synapse-react-client/README.md, packages/synapse-react-client/src/components/StorybookComponentWrapper.tsx, packages/synapse-react-client/src/utils/functions/getEndpoint.test.ts, packages/synapse-react-client/src/utils/functions/getEndpoint.ts
Change endpoint override global variable to not be inside of SRC. When synapse-react-client is imported as SRC using a namespace import (`import * as SRC from synapse-react-client`), `SRC` becomes an immutable object, making it impossible to set an override.
Do not merge, a corresponding PR in SWC must also be created and merged in coordination with this PR.
=> SWC-7242 - Update endpoint override var

apps/portals/adknowledgeportal/src/config/routesConfig.tsx, apps/synapse-portal-framework/src/components/RedirectWithQuery.tsx
PORTALS-3429
- Update `Navigate` calls to use `replace: true` if used in a redirect context
=> PORTALS-3429

.github/workflows/sonarqube-scan.yml, sonar-project.properties
Add minimal sonarqube scan workflow and properties file. Need to add `SONAR_TOKEN` secret to repo and have IT import this repository into Sage's SonarCloud account.
=> PORTALS-3435: Add automated SonarCloud scans

apps/SageAccountWeb/src/LoginPage.tsx, apps/SageAccountWeb/src/components/RegisterAccount1.tsx, packages/synapse-react-client/src/components/SystemUseNotification/SystemUseNotification.tsx
Jira ticket: https://sagebionetworks.jira.com/browse/SWC-7182?atlOrigin=eyJpIjoiNWNiYjZkYjM0MmE3NDE0YTgyMTBlNDViN2NkZGFkNGIiLCJwIjoiaiJ9
=> SWC-7182: SageAccountWeb: LoginPage updates on mobile

.github/workflows/sonarqube-scan.yml, packages/synapse-react-client/sonar-project.properties, sonar-project.properties
for SonarQube monorepo scans, each project can be analyzed separately by providing individual configs and a project-specific key.
=> move SonarQube config into project directories instead of monorepo root

packages/synapse-react-client/src/utils/SynapseConstants.ts, packages/synapse-react-client/src/utils/hooks/useOneSageURL.test.ts
- Fix stack hop caused by mismatched `repo-prod` vs `repo-dev` backend URL (compared in useOneSageURL hook)
- Fill in missing tests for useOneSageURL
=> PORTALS-3473

.github/workflows/sonarqube-scan-pr.yml
Add a workflow to run sonarcloud scans from a PR using the main repo's sonar-pr environment to get the sonar token. This is necessary to securely run workflows from forks.
=> Workflow to run sonarcloud scan on PR

.github/workflows/sonarqube-scan-pr.yml
@tschaffter the original workflow failed because I assigned the env variable incorrectly using `:` instead of `=`
=> PORTALS-3435: use  instead of  to assign -Dsonar.pullrequest.key

.github/workflows/sonarqube-scan-pr.yml
While the sonar scan is now running on PR and commenting its analysis, it has yet to pick up code changes. Perhaps passing branch information in addition to the PR number will give the scan the information it needs to compare code.
=> PORTALS-3435: pass target and source branch to sonar scan to pick up changed files

apps/portals/adknowledgeportal/src/config/scripts/exportS3ProductionBucketName.sh, apps/portals/adknowledgeportal/src/config/scripts/exportS3StagingBucketName.sh, apps/portals/arkportal/src/config/scripts/exportS3ProductionBucketName.sh, apps/portals/arkportal/src/config/scripts/exportS3StagingBucketName.sh, apps/portals/bsmn/src/config/scripts/exportS3ProductionBucketName.sh, apps/portals/bsmn/src/config/scripts/exportS3StagingBucketName.sh, apps/portals/cancercomplexity/src/config/scripts/exportS3ProductionBucketName.sh, apps/portals/cancercomplexity/src/config/scripts/exportS3StagingBucketName.sh, apps/portals/challengeportal/src/config/scripts/exportS3ProductionBucketName.sh, apps/portals/challengeportal/src/config/scripts/exportS3StagingBucketName.sh, apps/portals/digitalhealth/src/config/scripts/exportS3ProductionBucketName.sh, apps/portals/digitalhealth/src/config/scripts/exportS3StagingBucketName.sh, apps/portals/elportal/src/config/scripts/exportS3ProductionBucketName.sh, apps/portals/elportal/src/config/scripts/exportS3StagingBucketName.sh, apps/portals/genie/src/config/scripts/exportS3ProductionBucketName.sh, apps/portals/genie/src/config/scripts/exportS3StagingBucketName.sh, apps/portals/nf/src/config/scripts/exportS3ProductionBucketName.sh, apps/portals/nf/src/config/scripts/exportS3StagingBucketName.sh, apps/portals/standards/src/config/scripts/exportS3ProductionBucketName.sh, apps/portals/standards/src/config/scripts/exportS3StagingBucketName.sh, apps/portals/stopadportal/src/config/scripts/exportS3ProductionBucketName.sh, apps/portals/stopadportal/src/config/scripts/exportS3StagingBucketName.sh
This PR adds an environment variable to specify the distribution ID for each portal (staging and prod).
Another PR will modify run.sh to create an invalidation for the distribution.
=> PLFM-3499: Add env var for distribution id

apps/portals/cancercomplexity/src/config/synapseConfigs/education.ts, apps/portals/cancercomplexity/src/config/synapseConfigs/tools.ts
I forgot to update the default citation format to 'nature' for the education and tools pages.
=> default citation to nature for education and tools

packages/synapse-react-client/src/components/Forum/DiscussionReply.tsx, packages/synapse-react-client/src/components/Forum/DiscussionThread.tsx, packages/synapse-react-client/src/umd.index.ts
=> Small styling tweaks and include DiscussionThread component in SynapseComponents

apps/portals/adknowledgeportal/src/config/navbarConfig.ts, apps/portals/ampals/src/config/navbarConfig.ts, apps/portals/arkportal/src/config/navbarConfig.ts, apps/portals/bsmn/src/config/navbarConfig.ts, apps/portals/cancercomplexity/src/config/navbarConfig.ts, apps/portals/challenges/src/config/navbarConfig.ts, apps/portals/digitalhealth/src/config/navbarConfig.ts, apps/portals/eliteportal/src/config/navbarConfig.ts, apps/portals/genie/src/config/navbarConfig.ts, apps/portals/nf/src/config/navbarConfig.ts, apps/portals/standards/src/config/navbarConfig.ts, apps/portals/stopadportal/src/config/navbarConfig.ts, apps/synapse-portal-framework/src/components/navbar/Navbar.tsx, packages/synapse-types/src/FeatureFlags.ts
Enable the PORTALS nav item on ELITE, do not show on other portals (for now).
I think the flag can also be removed from the stack builder (like [the AR modal wizard flag](https://github.com/Sage-Bionetworks/Synapse-Stack-Builder/pull/701/files)), since undefined should be the same as 'false'.
=> PORTALS-3157

apps/portals/standards/src/pages/HomePage.tsx
=> Standards Registry: Katie suggested using "relevantOrgName" (organizations) rather than responsibleOrgName

packages/synapse-react-client/src/components/EntityDownloadConfirmation/EntityDownloadConfirmation.tsx, packages/synapse-react-client/src/components/GenericCard/GenericCard.tsx
This PR fixes bad logic that prevented the Download button to trigger download cart logic. Also, it spaces card buttons horizontally instead of vertically
=> Portals 3386 f/u - Fix download cart button

packages/synapse-react-client/src/components/Markdown/MarkdownSynapse.test.tsx, packages/synapse-react-client/src/components/Markdown/MarkdownSynapse.tsx
Fix bug where MarkdownSynapse would not re-process markdown when the `markdown` prop changed.
=> PORTALS-3552

packages/synapse-react-client/jest.config.cjs, packages/synapse-react-client/sonar-project.properties
Point the sonar properties to an `lcov` reporter for SRC `test:coverage` to get coverage analysis. This may need to be merged and scanned on the main branch for [the report to show up](https://sonarcloud.io/project/overview?id=sage-bionetworks_synapse-web-monorepo_src).
=> Portals 3553 - Add test coverage to sonar scan

apps/portals/cancercomplexity/src/config/synapseConfigs/commonProps.ts
Related Jira (refer to Jineta's comment here): https://sagebionetworks.jira.com/browse/PORTALS-3385?focusedCommentId=247116&page=com.atlassian.jira.plugin.system.issuetabpanels%3Acomment-tabpanel#comment-247116 
Jineta requested that some tags keep the 'data' part of the tooltip text (applied to all explore pages):
bioChemicalPhysical data
clinical data
epigenomeProfiling data
expressionProfiling data
genomeProfiling data
imaging data
proteomics data
spatialProfiling data
=> CCKP: Update tooltip text for some icons

packages/synapse-react-client/src/components/EntityDownloadConfirmation/EntityDownloadConfirmation.tsx
check that the entity concrete type exists to avoid flickering button when users lack permission to read a dataset
=> PORTALS-3386: download cart button bug fix

apps/SageAccountWeb/src/components/ProfileValidation/ProfileFieldsEditor.tsx, packages/synapse-react-client/src/components/RORInstitutionField/RORInstitutionField.test.tsx, packages/synapse-react-client/src/components/RORInstitutionField/RORInstitutionField.tsx
https://github.com/Sage-Bionetworks/synapse-web-monorepo/pull/1760
- Pass `error` along to RORInstitutionField
- useFakeTimers in test with debounced API call
=> code review changes from #1760

packages/synapse-react-client/src/components/GoalsV3/GoalsV3.tsx
Related Jira: https://sagebionetworks.jira.com/browse/PORTALS-3445?focusedCommentId=247278
Content not centered on extra large screens.
Before:
After:
=> AMP ALS: Center Our ALS Resources Content on XL screens

apps/portals/b2ai.standards/src/config/columnAliases.ts, apps/portals/b2ai.standards/src/config/resources.ts, apps/portals/b2ai.standards/src/config/synapseConfigs/data.ts, apps/portals/b2ai.standards/src/pages/HomePage.tsx, apps/portals/b2ai.standards/src/pages/StandardsDetailsPage.tsx
- Uses hard-coded links. Need to fix later -- see https://github.com/bridge2ai/b2ai-standards-registry/issues/284
- Changed facetting to org name instead of description.
=> Fixes GC links from Home page

packages/synapse-react-client/src/components/GenericCard/TableRowGenericCard.tsx
Address a follow-up suggestion during validation
=> PORTALS-3387: Remove 'account required' text from 'how to download' label

packages/synapse-react-client/src/components/FullTextSearch/FullTextSearch.test.tsx, packages/synapse-react-client/src/components/FullTextSearch/FullTextSearchUtils.ts
Updated logic to calculate distance based on splitting search string using non-word characters (and filtering out empty strings).  This works for real-world cases, such as "Gene expression data, somatic mutation calls (VCF files from Mutect2 plus Platypus), copy-number calls (Sequenza and QDNAseq), the fraction of mutated microsatellites (MSIsensor), ATAC-seq insertion counts and allele counts of somatic SNVs in all sample types."
=> PORTALS-3567

packages/synapse-react-client/src/components/GenericCard/GenericCard.tsx, packages/synapse-react-client/src/components/HeaderCard.tsx, packages/synapse-react-client/src/components/row_renderers/utils/CardFooter.tsx
The "HOW TO DOWNLOAD" link works on a dataset card, but not in the dataset details page for CCKP. This fixes the issue by passing `cardTopContent` to `CardFooter` and `HeaderCard`.
=> Portals 3387: Fix download cart link on details page

apps/portals/b2ai.standards/src/config/resources.ts
Instead of hard-coding DST_denormalized version, use a materialized view to select from the most recent version and change MV definition when needed. So data update won't require PR.
=> Dst denormalized current

packages/synapse-react-client/src/synapse-client/HttpClient.ts
https://www.rfc-editor.org/rfc/rfc9110#field.content-type
utf8 is not a valid alias (but seems to be accepted!)
=> PORTALS-3572: set to valid utf-8 charset

apps/portals/nf/src/config/synapseConfigs/datasets.ts
The download cart button has been added. Now adding support for data type icons after the NF backend schema changed the dataType column to stringList
=> PORTALS-3560 Add config for dataType buttons on dataset cards.

packages/synapse-react-client/src/style/components/synapse_form_wrapper/_synapse-form-wrapper.scss
Jira: https://sagebionetworks.jira.com/browse/PORTALS-3245
Should be safe to remove line height styling and have it default like the other texts in the form. Images below show the three texts that are affected.
=> PORTALS-3245: stopadportal: Text wrapping oddly on Full Application > Submit screen

apps/portals/ampals/src/index.tsx
Reverts Sage-Bionetworks/synapse-web-monorepo#1821
We should be OK show this content in staging, since it is not indexed by Google
=> Revert "Hide all content in AMP-ALS site"

apps/portals/cancercomplexity/src/pages/DatasetsDetailsPage.tsx, apps/portals/cancercomplexity/src/pages/EducationalResourcesDetailsPage.tsx, apps/portals/cancercomplexity/src/pages/PublicationsDetailsPage.tsx, apps/portals/cancercomplexity/src/pages/ToolsDetailsPage.tsx
It was previously assumed that CCKP resources had a 1:1 relationship with grants.  But now there are resources that are linked to multiple grants, e.g. this [publication](https://www.cancercomplexity.synapse.org/Explore/Publications/DetailsPage?pubMedId=36280719) is linked to 2 grants: CA210173 and CA268083
This PR will address the need to show multiple grant cards as needed.
EDIT: the IN operator is now being used to list "Related Publications" on the Tools Details Page too
=> [fix] Update the SQL operator for Related Grants

packages/synapse-react-client/src/components/Plot/Plot.tsx, packages/synapse-react-client/src/components/Plot/safe-react-plotly-factory.ts
SWC-7329
Use workaround for browser-bundling + server-side ESM quirk in esbuild.
See https://github.com/evanw/esbuild/issues/2480#issuecomment-1970337003 for more info & workaround reference
=> SWC-7329 - Fix import issue in dev mode

apps/synapse-portal-framework/src/components/b2ai.standards/StandardsHeader.tsx
Some of the current search example terms don't currently work (they don't return any results) on the Standards Explorer site.
I'd like to remove them for now.
=> Trim list of searchExampleTerms for Bridge2AI Standards Explorer

apps/portals/b2ai.standards/package.json, apps/portals/b2ai.standards/src/components/IsMatureIconMap.tsx, apps/portals/b2ai.standards/src/config/resources.ts, apps/portals/b2ai.standards/src/config/synapseConfigs/data.ts, packages/synapse-react-client/src/components/CardContainerLogic/CardContainerLogic.tsx, packages/synapse-react-client/src/components/GenericCard/CardUtils.tsx, packages/synapse-react-client/src/components/GenericCard/SynapseCardLabel.test.tsx, packages/synapse-react-client/src/components/GenericCard/SynapseCardLabel.tsx, packages/synapse-react-client/src/components/SynapseTable/SynapseTableCell/SynapseTableCell.tsx, pnpm-lock.yaml
PORTALS-3613
For https://github.com/bridge2ai/b2ai-standards-registry/issues/300
- Add MapValueToReactComponentConfig to SynapseCardLabel, which provides a way to generically map a table value to a React Component implementation
- Add IsMatureIconMap component and integrate into Standards Portal as a MapValueToReactComponentConfig
=> PORTALS-3613

apps/portals/b2ai.standards/src/config/resources.ts, apps/portals/b2ai.standards/src/pages/StandardsDetailsPage.tsx
- This is for https://github.com/bridge2ai/b2ai-standards-registry/issues/309
- Updated DST-denormalized to v55
=> Added dataTypes as facet, col, and details page metadata

packages/synapse-react-client/src/components/SynapseHomepageV2/SynapseHomepageV2.tsx, packages/synapse-react-client/src/components/SynapseHomepageV2/__snapshots__/SynapseHomepageV2.test.tsx.snap
Jira: https://sagebionetworks.jira.com/browse/SWC-7256?atlOrigin=eyJpIjoiNTQwYmQ0OGVhZDQ1NDIxN2E2ZWM0Y2E4Yzc5YTI4MzgiLCJwIjoiaiJ9
Featured Datasets on mobile had really big padding so I reduced it a little:
=> SWC-7256: "We partner with scientific leaders" needs more space at the top

packages/synapse-react-client/src/components/FeaturedToolsList/FeaturedToolsList.test.tsx, packages/synapse-react-client/src/components/Plot/SynapsePlot.test.tsx
Import moved in React 19, but we should use the `@testing-library/react` alias
=> PORTALS-3351 - Replace imports to `react-dom/test-utils`

packages/synapse-react-client/src/components/AclEditor/useUpdateAcl.test.ts, packages/synapse-react-client/src/components/AclEditor/useUpdateAcl.ts, packages/synapse-react-client/src/components/Dialog/ConfirmCloseWithoutSavingDialog.tsx, packages/synapse-react-client/src/components/EntityAclEditor/EntityAclEditorModal.tsx, packages/synapse-react-client/src/components/doi/CreateOrUpdateDoiModal.test.tsx, packages/synapse-react-client/src/components/doi/CreateOrUpdateDoiModal.tsx, packages/synapse-react-client/src/utils/context/FullContextProvider.tsx, packages/synapse-react-client/src/utils/context/GlobalIsEditingContext.tsx
- Add context to synchronize React with global editing state
- Use isEditing context in ACL Editors
- Use isEditing context in DOI editor
- Add confirmation to closing EntityAclEditorModal if dirty
- Add confirmation to closing DOI modal (not currently tracking dirty state)
=> SWC-7055 - Track global editing state

apps/synapse-portal-framework/src/shared-config/DoiRedirectRoute.tsx, packages/synapse-client/src/util/waitForAsyncResult.test.ts, packages/synapse-client/src/util/waitForAsyncResult.ts, packages/synapse-react-client/src/components/GenericCard/PortalDOI/PortalDOI.test.tsx, packages/synapse-react-client/src/components/GenericCard/PortalDOI/PortalDOI.tsx, packages/synapse-react-client/src/components/doi/CreateOrUpdateDoiModal.tsx
- waitForAsyncResult should throw error when fetching async job status
- In portal redirector, use `objectId` search param to match backend
- Show the correct DOI URL in the Portal UI
=> PORTALS-3658 - Fix issues with Portal DOIs

packages/synapse-react-client/src/SWC.index.ts, packages/synapse-react-client/src/components/AccountLevelBadges/AccountLevelBadges.tsx, packages/synapse-react-client/src/components/EntityBadgeIcons/EntityBadgeIcons.tsx, packages/synapse-react-client/src/components/EntityIcon.tsx, packages/synapse-react-client/src/components/EntityUpload/EntityUploadModal.tsx, packages/synapse-react-client/src/components/Evaluation/EvaluationCard.tsx, packages/synapse-react-client/src/components/Evaluation/EvaluationEditorPage.tsx, packages/synapse-react-client/src/components/Forum/DiscussionThread.tsx, packages/synapse-react-client/src/components/HasAccess/HasAccessV2.tsx, packages/synapse-react-client/src/components/HelpPopover/HelpPopover.tsx, packages/synapse-react-client/src/components/Markdown/MarkdownGithub.tsx, packages/synapse-react-client/src/components/OAuthClientManagement/OAuthManagement.tsx, packages/synapse-react-client/src/components/Skeleton/SkeletonButton.tsx, packages/synapse-react-client/src/components/SqlDefinedTableEditor/SqlDefinedTableEditorModal.tsx, packages/synapse-react-client/src/components/SynapseFooter/SynapseFooter.tsx, packages/synapse-react-client/src/components/SynapseHomepageV2/HomepageStyles.ts, packages/synapse-react-client/src/components/SynapseHomepageV2/SynapseHomepageV2.tsx, packages/synapse-react-client/src/components/SynapseHomepageV2/SynapseInActionItem.tsx, packages/synapse-react-client/src/components/SynapseHomepageV2/SynapsePlan.tsx, packages/synapse-react-client/src/components/SynapseHomepageV2/SynapsePlanContent.tsx, packages/synapse-react-client/src/components/SynapseHomepageV2/SynapsePlansPage.tsx, packages/synapse-react-client/src/components/SynapseNavDrawer/SynapseNavDrawer.tsx, packages/synapse-react-client/src/components/SynapseTable/datasets/DatasetItemsEditor.tsx, packages/synapse-react-client/src/components/dataaccess/RejectProfileValidationRequestModal.tsx, packages/synapse-react-client/src/components/doi/CreateOrUpdateDoiModal.tsx, packages/synapse-react-client/src/components/download_list/FolderDownloadConfirmation.tsx, packages/synapse-react-client/src/components/entity/metadata/EntityModal.tsx, packages/synapse-react-client/src/components/entity/page/CreatedByModifiedBy.tsx, packages/synapse-react-client/src/components/trash/TrashCanList.tsx, packages/synapse-react-client/src/types/vite.d.ts
- Lazy-load each React component, so Vite will code-split and reduce the initial bundle size
- Remove unused React components from SWC bundle
=> SWC-6990 - Optimize bundle size

packages/synapse-react-client/src/components/row_renderers/utils/CardFooter.tsx, packages/synapse-react-client/src/style/components/_cards.scss
Jira: https://sagebionetworks.jira.com/browse/PORTALS-3657?atlOrigin=eyJpIjoiOWVjMWUyZDNkYTU3NDIzMWJjMWZkODc2Zjk3YjIyMmYiLCJwIjoiaiJ9
Before:
After:
=> PORTALS-3657: NF Data Portal: Text wrapping issue in study card secondary labels

apps/portals/adknowledgeportal/src/pages/Contribute/Contribute-FormSubmission.tsx, apps/portals/stopadportal/src/pages/FormSubmissionPage.tsx, packages/synapse-react-client/src/components/SynapseForm/SynapseFormWrapper.stories.tsx, packages/synapse-react-client/src/components/SynapseForm/SynapseFormWrapper.test.tsx, packages/synapse-react-client/src/components/SynapseForm/SynapseFormWrapper.tsx, packages/synapse-react-client/src/components/SynapseForm/useGetFormPropsFromSearchParams.ts
Fix issues in SynapseForm where search params were no longer passed to the component.
We used to always inject the URLSearchParams as props to top-level portals components. This recently changed, breaking these components where these params must now be manually passed.
=> PORTALS-3686, PORTALS-3687

apps/SageAccountWeb/.env.localhost, packages/synapse-react-client/.storybook/preview.tsx, packages/synapse-react-client/src/components/DataGrid/DataGrid.tsx, packages/synapse-react-client/src/components/DataGrid/DataGridWebSocket.ts, packages/synapse-react-client/src/components/DataGrid/useDataGridWebsocket.ts, packages/synapse-react-client/src/components/SynapseTable/SynapseTableCell/JSON/ComplexJSONRenderer.tsx, packages/synapse-react-client/src/components/SynapseTable/SynapseTableCell/JSON/__snapshots__/JSONTableCellRenderer.test.tsx.snap, packages/synapse-react-client/src/utils/functions/getEndpoint.ts
- Use replicaId from server
- Use ComplexJSONRenderer to display model snapshot
- Update ComplexJSONRenderer so 'expand'/'collapse' text is also interactive
- Add config options to Storybook to use localhost as a Synapse backend.
=> Minor data grid demo story improvements

apps/synapse-portal-framework/src/components/RedirectDialog.tsx, apps/synapse-portal-framework/src/pages/FileEntityPage/SynapseFileEntityPageProperties.tsx
- When a property has no value, do not show the property row.
Before:
After:
- Recognize when we are already on the FileEntity page. Since the provenance graph is displayed there, clicking a node should trigger the default redirect behavior to the appropriate Synapse page.
=> PORTALS-3702: Portals FileEntity Page: Cleanup Properties and Provenance Node Click

apps/synapse-portal-framework/src/pages/FileEntityPage/FileEntityPage.tsx, apps/synapse-portal-framework/src/pages/FileEntityPage/SynapseFileEntityLinkCard.tsx
Jira: https://sagebionetworks.jira.com/browse/PORTALS-3705
1) Entire SynapseFileEntityLinkCard component is now a clickable link
2) Reduced margins for file name in header of file entity pages as per Adam's request
Before: 
After:
=> PORTALS-3705: Portals FileEntity Page: Make Entire View FileEntity on Synapse.org component clickable

apps/portals/ampals/package.json, apps/portals/ampals/src/components/AmpAlsAccessColumn.tsx, apps/portals/ampals/src/config/synapseConfigs/datasets.tsx, apps/portals/ampals/src/types.d.ts, packages/synapse-react-client/src/components/HasAccess/AccessIcon.tsx, packages/synapse-react-client/src/components/HasAccess/HasAccessV2.tsx, packages/synapse-react-client/src/components/SynapseTable/SynapseTable.tsx, pnpm-lock.yaml
PORTALS-3669
- Add ability to supply custom columns to SynapseTable
- Create custom access column for ALS portal datasets based on dataset source
=> PORTALS-3669 - Custom access column for ALS portal

package.json, packages/synapse-react-client/package.json, pnpm-lock.yaml
- Upgrade `react-hot-toast`. Verified https://github.com/timolins/react-hot-toast/issues/170 (issue with `goober`) does not reproduce
- Remove remaining `overrides` that were added to address security alerts. Verified (via `pnpm why`) that we did not regress to dependency versions with known vulnerabilities after removing each override (`word-wrap`, `semver`, `postcss`, `elliptic`, `cross-spawn`)
Depends on #2083
=> Remove unnecessary overrides 

apps/portals/nf/src/config/resources.ts
This pull request updates the list of enabled analysis platforms in the `resources.ts` configuration file. The change re-enables both `pluto` and `terra` platforms for use, while removing the development-only `plutodev` entry.
Configuration updates:
* Replaced `plutodev` with `pluto` and added `terra` to the `enabledAnalysisPlatforms` array in `resources.ts`, making these platforms available for analysis.
=> switch to pluto and add terra

packages/synapse-react-client/package.json, packages/synapse-react-client/src/components/DataGrid/SynapseGrid.tsx, pnpm-lock.yaml
This PR updates json-joy to the latest version to fix an issue where querying a arr node returned the error `NOT_ARR`. It makes a few compatibility updates with the updated API.
It also fixes the insertion and editing of grid data by properly querying the new nested data structure.
=> SWC-7430: Fix grid row insertion

apps/synapse-portal-framework/src/components/RedirectDialog.tsx
Note that FileEntity Synapse.org links will go to the portal FileEntity page
=> PORTALS-3675: set the redirect dialog delay to a consistent 10 seconds

packages/synapse-react-client/src/components/EntityCitation/EntityCitation.test.tsx
Was originally using findByText but the test was flaky because the citation loads asynchronously + text might be split across multiple elements. Using waitFor + getByText seems to fix it. It might be because findByText is for if the text is fully contained in a single DOM element but in our case the citation text might be split across multiple nested elements.
=> PORTALS-3746: Flaky test in synapse-react-client

packages/synapse-react-client/src/components/HeaderCard/HeaderCardV2.tsx
Added space between title and subtitle in HeaderCardV2. This improves appearance for both Org and Standards details pages
=> Fixes https://github.com/bridge2ai/b2ai-standards-registry/issues/373

apps/portals/ampals/src/pages/HomePage.tsx, packages/synapse-react-client/src/components/RssFeedCards/RssFeedCards.tsx
Fixed RSS feed URL for AMP ALS WordPress site, but still encountering a CORS error (locally anyway).
Verified this URL redirects properly for other sites that use a WP RSS feed.
=> AMPALS-59: update WP rss feed URL

packages/synapse-react-client/src/components/DataGrid/columns/AutocompleteColumn.tsx
Fix issue where users typing a value into an enum column and then selecting a drop-down value did not update the cell's value.
=> PORTALS-3848: Fix grid enum select

packages/synapse-react-client/src/components/DataGrid/SynapseGrid.tsx, packages/synapse-react-client/src/components/DataGrid/utils/getCellClassName.test.ts, packages/synapse-react-client/src/components/DataGrid/utils/getCellClassName.ts, packages/synapse-react-client/src/style/components/_data-grid-extra.scss
Store the selected cells in state and add CSS to keep them highlighted when the grid loses focus. This allows the users to see which cells are highlighted when interacting with the chatbot.
=> SWC 7500 - show cell selection when grid is not focused
